### ISSUE TITLE
Known interpreter identification issues.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1027]
Sometimes Pex may fail to identify and use an interpreter it finds on a system. This can often be due to the vagaries of how various operating systems and their packaging systems configure and install python. This issue tracks these known issues and workarounds.

**Comment by jsirois** [comment]
Ubuntu systems are known to leave out (portions of) the `distutils` stdlib from their "standard" python package. For example, on Ubunutu 20.4 and many older Ubuntu distributions, installing the `python3` package is not enough, you must also install `python3-distlib`. The error seen when only `python3` is installed will look something like the error seen below in the 'Skipped the following broken interpreters:' section:
```
Could not find a compatible interpreter.

Examined the following working interpreters:
1.) /usr/bin/python2.7 CPython==2.7.18

Skipped the following broken interpreters:
1.) /usr/bin/python3.8:
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/workspace/pex/interpreter.py", line 24, in <module>
    from pex.third_party.packaging import markers, tags
  File "/workspace/pex/vendor/_vendored/packaging/packaging/tags.py", line 7, in <module>
    import distutils.util
ModuleNotFoundError: No module named 'distutils.util'

No working interpreter compatible with the requested constraints was found:
  CPython>=3.7
```

**Comment by cupen** [comment]
My envs.
* archlinux
* python3.10 
```
$ wget https://github.com/pantsbuild/pants/releases/download/release_2.10.0/pants.2.10.0.pex
$ ./pants.2.10.0.pex --version
Failed to find compatible interpreter on path /home/cupen/.nimble/bin:/home/cupen/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/home/cupen/.dotnet/tools:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/cupen/go/bin/:/home/cupen/.local/bin:/bin:/bin.


Examined the following working interpreters:
1.) /usr/bin/python3.10 CPython==3.10.4
2.)  /usr/bin/python2.7 CPython==2.7.18

Skipped the following broken interpreters:
1.) /usr/bin/python3.7:
InterpreterNotFound('The interpreter path /usr/bin/python3.7 does not exist.')

(See https://github.com/pantsbuild/pex/issues/1027 for a list of known breaks and workarounds.)

No working interpreter compatible with the requested constraints was found:
  Version matches CPython>=3.7,<3.10
```

**Comment by stuhood** [comment]
> My envs.
>     * archlinux
>     * python3.10

To close the loop: as you discovered on [the other issue](https://github.com/pantsbuild/pants/issues/14908): Pants only supports running with Python 3.7 - 3.9 currently, so this issue probably isn't related.
