### ISSUE TITLE
NotADirectoryError when zip_safe=True

### ISSUE THREAD

**Issue by ZdenekM** [pantsbuild/pex#1035]
With pants 2.0.0b0 I started to getting this:

```
Traceback (most recent call last):
  File "/home/zdenal/arcor2_repos/arcor2/dist/src.python.arcor2.scripts/upload_builtin_objects.pex/.bootstrap/pex/pex.py", line 423, in execute
  File "/home/zdenal/arcor2_repos/arcor2/dist/src.python.arcor2.scripts/upload_builtin_objects.pex/.bootstrap/pex/pex.py", line 356, in _wrap_coverage
  File "/home/zdenal/arcor2_repos/arcor2/dist/src.python.arcor2.scripts/upload_builtin_objects.pex/.bootstrap/pex/pex.py", line 387, in _wrap_profiling
  File "/home/zdenal/arcor2_repos/arcor2/dist/src.python.arcor2.scripts/upload_builtin_objects.pex/.bootstrap/pex/pex.py", line 474, in _execute
  File "/home/zdenal/arcor2_repos/arcor2/dist/src.python.arcor2.scripts/upload_builtin_objects.pex/.bootstrap/pex/pex.py", line 576, in execute_entry
  File "/home/zdenal/arcor2_repos/arcor2/dist/src.python.arcor2.scripts/upload_builtin_objects.pex/.bootstrap/pex/pex.py", line 584, in execute_module
  File "/usr/lib/python3.8/runpy.py", line 210, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zdenal/arcor2_repos/arcor2/dist/src.python.arcor2.scripts/upload_builtin_objects.pex/arcor2/scripts/upload_builtin_objects.py", line 15, in <module>
  File "/home/zdenal/arcor2_repos/arcor2/dist/src.python.arcor2.scripts/upload_builtin_objects.pex/arcor2/scripts/upload_builtin_objects.py", line 10, in main
  File "/home/zdenal/arcor2_repos/arcor2/dist/src.python.arcor2.scripts/upload_builtin_objects.pex/arcor2/object_types/upload.py", line 29, in upload_def
NotADirectoryError: [Errno 20] Not a directory: '/home/zdenal/arcor2_repos/arcor2/dist/src.python.arcor2.scripts/upload_builtin_objects.pex/arcor2/object_types/logic_actions.py'
```

With 2.0.0a3 the same PEX can be executed just fine. Also when I add ``zip_safe=False``` to ```python_binary``` target, the error is gone (with b0). The faulty pex file can be found [here](https://drive.google.com/file/d/1rtAPW_0_QwBaJCyRCKBv453fRNx_zHtT/view?usp=sharing).

**Comment by Eric-Arellano** [comment]
Zdenek explained that this was broken in Pants 2.0.0a3 when setting `zip_safe=True`. In beta0, Pants changed the default to `zip_safe=True`, so it makes sense that this broke. It's not clear to me why zip safe doesn't work here, though.

**Comment by jsirois** [comment]
@ZdenekM without access to your code I can't say for sure, but looking at these 2 lines:
```
  File ".../upload_builtin_objects.pex/arcor2/object_types/upload.py", line 29, in upload_def
NotADirectoryError: [Errno 20] Not a directory: '.../upload_builtin_objects.pex/arcor2/object_types/logic_actions.py'
```
It seems clear these is code in arcor2/object_types/upload.py that assumes sibling files will be on a normal filesystem and not inside a zip file. Typically this means you're using `open(...)`, `os.chdir`, etc. If that guess is right it just means your code is not zip safe and you'll need to mark it as such.

Can you confirm the code in `upload_def` is in fact trying to use filesystem APIs?

**Comment by Eric-Arellano** [comment]
Zdenek shared the repository in an unrelated issue in Slack in the past. See https://github.com/robofit/arcor2 and make sure you’re on the devel branch, which is what uses Pants. 

Thanks for taking a look at this issue!

**Comment by jsirois** [comment]
OK, yes line 29 is using a filesystem operation - `open`:
https://github.com/robofit/arcor2/blob/devel/src/python/arcor2/object_types/upload.py#L29

I'm going to close this as answered. Please speak up @ZdenekM if the reason your code is not zip safe is unclear.

**Comment by jsirois** [comment]
If you do want to be zip safe, I think you could probably switch from using inspect.getfile + open to using inspect.getsource https://docs.python.org/3/library/inspect.html#inspect.getsource

**Comment by ZdenekM** [comment]
Thanks for the clarification and for the tip with `inspect.getsource` - I will give it a try.
