### ISSUE TITLE
pex fails (inside conda environment) with Python 3.6

### ISSUE THREAD

**Issue by christopherfrieler** [pantsbuild/pex#1066]
Hello,

I'm getting a strange error when trying to run pex inside a conda environment with python 3.6.12:

> $> pex
Traceback (most recent call last):
  File "/var/folders/xp/6yltnt017r34nwvz2j6yzkzsprvtg_/T/tmpsip20vm8/.bootstrap/pex/pex.py", line 423, in execute
  File "/var/folders/xp/6yltnt017r34nwvz2j6yzkzsprvtg_/T/tmpsip20vm8/.bootstrap/pex/pex.py", line 356, in _wrap_coverage
  File "/var/folders/xp/6yltnt017r34nwvz2j6yzkzsprvtg_/T/tmpsip20vm8/.bootstrap/pex/pex.py", line 387, in _wrap_profiling
  File "/var/folders/xp/6yltnt017r34nwvz2j6yzkzsprvtg_/T/tmpsip20vm8/.bootstrap/pex/pex.py", line 477, in _execute
  File "/var/folders/xp/6yltnt017r34nwvz2j6yzkzsprvtg_/T/tmpsip20vm8/.bootstrap/pex/pex.py", line 533, in execute_interpreter
  File "/var/folders/xp/6yltnt017r34nwvz2j6yzkzsprvtg_/T/tmpsip20vm8/.bootstrap/pex/pex.py", line 499, in demote_bootstrap
  File "/var/folders/xp/6yltnt017r34nwvz2j6yzkzsprvtg_/T/tmpsip20vm8/.bootstrap/pex/__init__.py", line 6, in <module>
ModuleNotFoundError: No module named '__future__'

In another conda environment with python 3.8.5 the same command starts the python interpreter console as expected. Pex itself states to be compatible with Python >=3.5 and < 3.9.

pex version: 2.1.17
Conda version: 4.8.4 (I'm not sure, if this behaviour has anything to do with conda. It's just the way I manage different Python versions locally atm.)
OS: macOS Catalina

Can anyone confirm this behaviour? Or am I doing something wrong?

**Comment by jsirois** [comment]
@christopherfrieler I only have access to Linux, but perhaps you can 1st try the follwing in the the failing conda environment:
```python
$ python3.6
Python 3.6.12 (default, Sep 26 2020, 16:07:18) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import absolute_import
>>> 
```

**Comment by jsirois** [comment]
Actually, no need. Something stranger is going on since pex/pex.py which is higher in the stack trace clearly does load but it also has a `from __future__ import ...` 1st line.  I'll dig a bit in `demote_bootstrap`.

**Comment by jsirois** [comment]
Actually, @christopherfrieler can you run the following in the failing conda environment and report all output?:
```
$> PEX_VERBOSE=9 pex -vvvvvvvvv
```
That will reveal more of what is going on in the `demote_bootstrap` process.

**Comment by christopherfrieler** [comment]
Hi @jsirois, you can find the ouput of the the command here: https://gist.github.com/christopherfrieler/f09a971b935a260f3e370e376c2e4869

**Comment by christopherfrieler** [comment]
Ok, looks like there was something wrong with my conda-environment, although I'm not sure, what. However, recreating it from scratch solved the problem for me. pex is working in the new environment.

Sorry to bother you.
