### ISSUE TITLE
jsonschema fails pex (or cant pex ipython[notebook])

### ISSUE THREAD

**Issue by GregBowyer** [pantsbuild/pex#130]
No idea why, but given this requirements.txt

```
jsonschema
```

Pex does this 
```
greg@gregslaptop ~/work $ pex -r requirements.txt 
Traceback (most recent call last):
  File "/tmp/tmpiHbGHG/.bootstrap/_pex/pex.py", line 313, in execute
    working_set = self._activate()
  File "/tmp/tmpiHbGHG/.bootstrap/_pex/pex.py", line 78, in _activate
    for dist in env.activate():
  File "/tmp/tmpiHbGHG/.bootstrap/_pex/environment.py", line 132, in activate
    self._working_set = self._activate()
  File "/tmp/tmpiHbGHG/.bootstrap/_pex/environment.py", line 181, in _activate
    resolved = self._resolve(working_set, all_reqs)
  File "/tmp/tmpiHbGHG/.bootstrap/_pex/environment.py", line 151, in _resolve
    if e.args[1]:
IndexError: tuple index out of range
```

**Comment by jsirois** [comment]
I do not repro.  I'll show you my steps / configuration and perhaps you can come back with similar:
```console
(pex)jsirois@gill ~ $ python --version
Python 2.7.8
(pex)jsirois@gill ~ $ pex --version
pex 1.0.0
(pex)jsirois@gill ~ $ echo jsonschema > requirements.txt
(pex)jsirois@gill ~ $ pex -vvv -r requirements.txt 
/home/jsirois/.pyenv/versions/pex/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
pex: Building pex :: Resolving interpreter :: Setting up interpreter /home/jsirois/.pyenv/versions/pex/bin/python :: Interpreter cache resolving wheel<0.25.0,>=0.24.0 :: Fetching SourcePackage(u'https://pypi.python.org/packages/source/w/wheel/wheel-0.24.0.tar.gz#md5=3b0d66f0d127ea8befapex: Building pex :: Resolving interpreter :: Setting up interpreter /home/jsirois/.pyenv/versions/pex/bin/python :: Interpreter cache resolving wheel<0.25.0,>=0.24.0 :: Fetching SourcePackage(u'https://pypi.python.org/packages/source/w/wheel/wheel-0.24.0.tar.gz#md5=3b0d66f0d127ea8befapex: Validated wheel-0.24.0.tar.gz (md5=3b0d66f0d127ea8befaa5d11453107fd)                                                                                                                                                                                                                                                                                                                                                         
pex: Validated wheel-0.24.0.tar.gz (md5=3b0d66f0d127ea8befaa5d11453107fd)
pex: Building pex :: Resolving interpreter :: Setting up interpreter /home/jsirois/.pyenv/versions/pex/bin/python :: Interpreter cache resolving wheel<0.25.0,>=0.24.0 :: Installing SourcePackage(u'https://pypi.python.org/packages/source/w/wheel/wheel-0.24.0.tar.gz#md5=3b0d66f0d127ea8bepex: Building pex :: Resolving interpreter :: Setting up interpreter /home/jsirois/.pyenv/versions/pex/bin/python :: Interpreter cache resolving wheel<0.25.0,>=0.24.0 :: Installing SourcePackage(u'https://pypi.python.org/packages/source/w/wheel/wheel-0.24.0.tar.gz#md5=3b0d66f0d127ea8bepex: Building pex :: Resolving distributions                                                                                                                                                                                                                                                  /home/jsirois/.pyenv/versions/pex/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
pex: Validated jsonschema-2.5.1-py2.py3-none-any.whl (md5=20a47c9d9bc9357d8c731cfc19e3f968)                                                                                              
pex: Validated jsonschema-2.5.1-py2.py3-none-any.whl (md5=20a47c9d9bc9357d8c731cfc19e3f968)
pex: Validated functools32-3.2.3-1.tar.gz (md5=6c226dfc1ca56ba3ee200d603b780cbc)                                                                                                                                
pex: Validated functools32-3.2.3-1.tar.gz (md5=6c226dfc1ca56ba3ee200d603b780cbc)
  functools32 3.2.3.post1lving distributions :: Translating /tmp/tmpwz9XCC/functools32-3.2.3-1.tar.gz into distribution :: Packaging functools32 :: Installing /tmp/tmpl5UJW_             
  jsonschema 2.5.1
pex: Building pex: 1364.6ms                                                                                                                                                  
pex:   Resolving interpreter: 595.7ms
pex:     Setting up interpreter /home/jsirois/.pyenv/versions/pex/bin/python: 595.6ms
pex:       Interpreter cache resolving wheel<0.25.0,>=0.24.0: 332.8ms
pex:         Fetching SourcePackage(u'https://pypi.python.org/packages/source/w/wheel/wheel-0.24.0.tar.gz#md5=3b0d66f0d127ea8befaa5d11453107fd'): 202.3ms
pex:           Fetching https://pypi.python.org/packages/source/w/wheel/wheel-0.24.0.tar.gz#md5=3b0d66f0d127ea8befaa5d11453107fd: 201.0ms
pex:         Installing SourcePackage(u'https://pypi.python.org/packages/source/w/wheel/wheel-0.24.0.tar.gz#md5=3b0d66f0d127ea8befaa5d11453107fd'): 130.3ms
pex:           Installing /tmp/tmpvVXedw: 122.4ms
pex:   Resolving distributions: 761.8ms
pex:     Fetching https://pypi.python.org/packages/py2.py3/j/jsonschema/jsonschema-2.5.1-py2.py3-none-any.whl#md5=20a47c9d9bc9357d8c731cfc19e3f968: 186.4ms
pex:     Fetching file:///home/jsirois/.pex/build/jsonschema-2.5.1-py2.py3-none-any.whl: 0.4ms
pex:       Fetching file:///home/jsirois/.pex/build/jsonschema-2.5.1-py2.py3-none-any.whl: 0.2ms
pex:     Translating /tmp/tmpun2i8s/jsonschema-2.5.1-py2.py3-none-any.whl into distribution: 0.9ms
pex:     Fetching https://pypi.python.org/packages/source/f/functools32/functools32-3.2.3-1.tar.gz#md5=6c226dfc1ca56ba3ee200d603b780cbc: 144.9ms
pex:     Fetching file:///home/jsirois/.pex/build/functools32-3.2.3-1.tar.gz: 0.4ms
pex:       Fetching file:///home/jsirois/.pex/build/functools32-3.2.3-1.tar.gz: 0.2ms
pex:     Translating /tmp/tmpwz9XCC/functools32-3.2.3-1.tar.gz into distribution: 105.2ms
pex:       Packaging functools32: 102.1ms
pex:         Installing /tmp/tmpl5UJW_: 101.3ms
Running PEX file at /tmp/tmpniKsZU with args []
pex: PEX.run invoking /home/jsirois/.pyenv/versions/pex/bin/python /tmp/tmpniKsZU
Python 2.7.8 (default, Oct 12 2014, 00:37:26) 
[GCC 4.9.1 20140903 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import jsonschema
>>> dir(jsonschema)
['Draft3Validator', 'Draft4Validator', 'ErrorTree', 'FormatChecker', 'FormatError', 'RefResolutionError', 'RefResolver', 'SchemaError', 'ValidationError', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', '_format', '_utils', '_validators', '_version', 'compat', 'draft3_format_checker', 'draft4_format_checker', 'exceptions', 'validate', 'validators']
>>>
```

**Comment by GregBowyer** [comment]
Oh wow, it now does not reproduce here either !

**Comment by jsirois** [comment]
OK - well, the code in question, for pex version 1 looks faulty: https://github.com/pantsbuild/pex/blob/v1.0.0/pex/environment.py#L151

It tests for args slot 1 of a pkg_resources.DistributionNotFound, and only if present, adds some extra error debugging info.  The test though assumes 1 is present, which looks wrong.

I can send up a quick review to patch this, but in-short - its looks like pex hit a transient requirment resolution error (which is fine and normal), but then errored trying to collect data on the resolution error in a systemic way (which is not okay).

**Comment by jsirois** [comment]
Fix review here: https://rbcommons.com/s/twitter/r/2400/

**Comment by punya** [comment]
I ran into the IPython problem above today, so I'd love to see the fix merged (assuming the fix is correct).

**Comment by jsirois** [comment]
Fix submitted @ https://github.com/pantsbuild/pex/commit/03ef43d86b8498f09a6837e37e1347517d53e622

**Comment by GregBowyer** [comment]
Not sure how I test this, but thanks for figuring out there was something not quite right.
