### ISSUE TITLE
PEX direct requirement metadata for resolves via Pip is incorrect.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1311]
For example:
```
$ python -mpex sanic.routing==0.5.0 -o pip-resolve.pex
^jsirois@gill ~/dev/pantsbuild/pex (main) $ ./pip-resolve.pex -c 'import sanic_routing'
Traceback (most recent call last):
  File "/home/jsirois/dev/pantsbuild/pex/pip-resolve.pex/.bootstrap/pex/pex.py", line 483, in execute
  File "/home/jsirois/dev/pantsbuild/pex/pip-resolve.pex/.bootstrap/pex/pex.py", line 400, in _wrap_coverage
  File "/home/jsirois/dev/pantsbuild/pex/pip-resolve.pex/.bootstrap/pex/pex.py", line 431, in _wrap_profiling
  File "/home/jsirois/dev/pantsbuild/pex/pip-resolve.pex/.bootstrap/pex/pex.py", line 542, in _execute
  File "/home/jsirois/dev/pantsbuild/pex/pip-resolve.pex/.bootstrap/pex/pex.py", line 582, in execute_interpreter
  File "/home/jsirois/dev/pantsbuild/pex/pip-resolve.pex/.bootstrap/pex/pex.py", line 649, in execute_content
  File "/home/jsirois/dev/pantsbuild/pex/pip-resolve.pex/.bootstrap/pex/compatibility.py", line 93, in exec_function
  File "-c <cmd>", line 1, in <module>
ModuleNotFoundError: No module named 'sanic_routing'
$ python -mpex sanic.routing==0.5.0 --pex-repository pip-resolve.pex -o pex-resolve.pex
$ ./pex-resolve.pex -c 'import sanic_routing'
$
```

In other words - PEX files resolved via either Pip or a --pex-repository both have the same distributions but not the same direct requirements:
```diff
$ diff <(pex-tools pip-resolve.pex info -i4) <(pex-tools pex-resolve.pex info -i4)
21c21
<     "pex_hash": "8afa05bc6600a8cac0e42ad2493e371a0659c5c4",
---
>     "pex_hash": "e52d16e483c67467a895e567e027819b78e78fc1",
23c23,25
<     "requirements": [],
---
>     "requirements": [
>         "sanic.routing==0.5.0"
>     ],

```

Where the distributions embedded in both are:
```
$ pex-tools pip-resolve.pex info | jq .distributions
{
  "sanic_routing-0.5.0-py3-none-any.whl": "1acac3815f82bcb444980f7a3a4d24e8d6df2f56"
}
$ pex-tools pex-resolve.pex info | jq .distributions
{
  "sanic_routing-0.5.0-py3-none-any.whl": "1acac3815f82bcb444980f7a3a4d24e8d6df2f56"
}
```

**Comment by jsirois** [comment]
This is the same bug as attacked in #1302. The fix in #1304 just missed a spot.
