### ISSUE TITLE
Pex probes wheel metadata incorrectly.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1375]
I need to find the relevant spec, but the defacto wheel creator appears to lowercase project names when setting up the dist-info metadata directory:
```console
$ python -mvenv PyAthena.venv
$ source PyAthena.venv/bin/activate
(PyAthena.venv) $ pip -q install -U pip
(PyAthena.venv) $ pip wheel --no-deps pyathena==1.11.5
Collecting pyathena==1.11.5
...
Saved ./PyAthena-1.11.5-py2.py3-none-any.whl
(PyAthena.venv) $ zipinfo ./PyAthena-1.11.5-py2.py3-none-any.whl
Archive:  ./PyAthena-1.11.5-py2.py3-none-any.whl
Zip file size: 32074 bytes, number of entries: 19
-rw-r--r--  2.0 unx     1536 b- defN 80-Jan-01 00:00 pyathena/__init__.py
-rw-r--r--  2.0 unx     3343 b- defN 80-Jan-01 00:00 pyathena/async_cursor.py
-rw-r--r--  2.0 unx     2634 b- defN 80-Jan-01 00:00 pyathena/async_pandas_cursor.py
-rw-r--r--  2.0 unx     9619 b- defN 80-Jan-01 00:00 pyathena/common.py
-rw-r--r--  2.0 unx     6391 b- defN 80-Jan-01 00:00 pyathena/connection.py
-rw-r--r--  2.0 unx     4534 b- defN 80-Jan-01 00:00 pyathena/converter.py
-rw-r--r--  2.0 unx     3359 b- defN 80-Jan-01 00:00 pyathena/cursor.py
-rw-r--r--  2.0 unx      718 b- defN 80-Jan-01 00:00 pyathena/error.py
-rw-r--r--  2.0 unx     4493 b- defN 80-Jan-01 00:00 pyathena/formatter.py
-rw-r--r--  2.0 unx     5539 b- defN 80-Jan-01 00:00 pyathena/model.py
-rw-r--r--  2.0 unx     3883 b- defN 80-Jan-01 00:00 pyathena/pandas_cursor.py
-rw-r--r--  2.0 unx    16546 b- defN 80-Jan-01 00:00 pyathena/result_set.py
-rw-r--r--  2.0 unx    14810 b- defN 80-Jan-01 00:00 pyathena/sqlalchemy_athena.py
-rw-r--r--  2.0 unx    10247 b- defN 80-Jan-01 00:00 pyathena/util.py
?rw-r--r--  2.0 unx       79 b- defN 16-Jan-01 00:00 pyathena-1.11.5.dist-info/entry_points.txt
-rw-r--r--  2.0 unx     1055 b- defN 80-Jan-01 00:00 pyathena-1.11.5.dist-info/LICENSE
?rw-r--r--  2.0 unx       87 b- defN 16-Jan-01 00:00 pyathena-1.11.5.dist-info/WHEEL
?rw-r--r--  2.0 unx    32199 b- defN 16-Jan-01 00:00 pyathena-1.11.5.dist-info/METADATA
?rw-r--r--  2.0 unx     1501 b- defN 16-Jan-01 00:00 pyathena-1.11.5.dist-info/RECORD
19 files, 122573 bytes uncompressed, 29662 bytes compressed:  75.8%
```

The upshot is this sort of problem:
```console
$ pex pyathena==1.11.5 -opyathena.pex
Traceback (most recent call last):
  File "/home/jsirois/.venv/pex/bin/pex", line 8, in <module>
    sys.exit(main())
  File "/home/jsirois/.venv/pex/lib/python3.9/site-packages/pex/bin/pex.py", line 1145, in main
    pex_builder = build_pex(options.requirements, options, cache=ENV.PEX_ROOT)
  File "/home/jsirois/.venv/pex/lib/python3.9/site-packages/pex/bin/pex.py", line 1023, in build_pex
    resolveds = resolve_multi(
  File "/home/jsirois/.venv/pex/lib/python3.9/site-packages/pex/resolver.py", line 1054, in resolve_multi
    build_and_install_request.install_distributions(
  File "/home/jsirois/.venv/pex/lib/python3.9/site-packages/pex/resolver.py", line 697, in install_distributions
    for install_result in execute_parallel(
  File "/home/jsirois/.venv/pex/lib/python3.9/site-packages/pex/jobs.py", line 431, in execute_parallel
    yield spawn_result.spawned_job.await_result()
  File "/home/jsirois/.venv/pex/lib/python3.9/site-packages/pex/jobs.py", line 185, in await_result
    job.wait()
  File "/home/jsirois/.venv/pex/lib/python3.9/site-packages/pex/jobs.py", line 76, in wait
    self._finalize_job()
  File "/home/jsirois/.venv/pex/lib/python3.9/site-packages/pex/jobs.py", line 110, in _finalize_job
    self._finalizer()
  File "/home/jsirois/.venv/pex/lib/python3.9/site-packages/pex/pip.py", line 551, in _fixup_install
    project_name_and_version = dist_metadata.project_name_and_version(
  File "/home/jsirois/.venv/pex/lib/python3.9/site-packages/pex/dist_metadata.py", line 207, in project_name_and_version
    pkg_info = _parse_pkg_info(dist)
  File "/home/jsirois/.venv/pex/lib/python3.9/site-packages/pex/dist_metadata.py", line 125, in _parse_pkg_info
    pkg_info = _parse_wheel_package_info(dist)
  File "/home/jsirois/.venv/pex/lib/python3.9/site-packages/pex/dist_metadata.py", line 107, in _parse_wheel_package_info
    with whl.open(os.path.join(dist_info_dir, DistInfoDistribution.PKG_INFO)) as fp:
  File "/usr/lib/python3.9/zipfile.py", line 1502, in open
    zinfo = self.getinfo(name)
  File "/usr/lib/python3.9/zipfile.py", line 1429, in getinfo
    raise KeyError(
KeyError: "There is no item named 'PyAthena-1.11.5.dist-info/METADATA' in the archive"
```

**Comment by jsirois** [comment]
Hrm, yeah - something changed in pip / setuptools / wheel land at some point:
```console
^jsirois@gill ~/Downloads $ zipinfo PyAthena-1.9.0-py2.py3-none-any.whl | grep METADATA
-rw-rw-rw-  2.0 fat      672 b- defN 19-Dec-14 11:25 PyAthena-1.9.0.dist-info/METADATA
^jsirois@gill ~/Downloads $ zipinfo PyAthena-1.11.5-py2.py3-none-any.whl | grep METADATA
?rw-r--r--  2.0 unx    32199 b- defN 16-Jan-01 00:00 pyathena-1.11.5.dist-info/METADATA
^jsirois@gill ~/Downloads $
```

Pex will need to do a case-insensitive / fuzzy search for the `.dist-info/` dir.
