### ISSUE TITLE
Flaky CI due to missing `fcntl` module.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1391]
Failures look like so on Ubuntu 20.04 machines:
```
=================================== FAILURES ===================================
____________________________ test_pex_multi_resolve ____________________________
[gw0] linux -- Python 3.9.6 /home/runner/work/pex/pex/.tox/py39-integration/bin/python

    def test_pex_multi_resolve():
        # type: () -> None
        """Tests multi-interpreter + multi-platform resolution."""
        python27 = ensure_python_interpreter(PY27)
        python37 = ensure_python_interpreter(PY37)
        with temporary_dir() as output_dir:
            pex_path = os.path.join(output_dir, "pex.pex")
            results = run_pex_command(
                [
                    "--disable-cache",
                    "lxml==4.2.4",
                    "--no-build",
                    "--platform=linux-x86_64-cp-36-m",
                    "--platform=macosx-10.6-x86_64-cp-36-m",
                    "--python={}".format(python27),
                    "--python={}".format(python37),
                    "-o",
                    pex_path,
                ]
            )
E           interpreters = [to_python_interpreter(interp) for interp in options.python]
E         File "/home/runner/work/pex/pex/pex/bin/pex.py", line 882, in to_python_interpreter
E           return PythonInterpreter.from_binary(full_path_or_basename)
E         File "/home/runner/work/pex/pex/pex/interpreter.py", line 816, in from_binary
E           raise cls.IdentificationError("Failed to identify {}: {}".format(binary, e))
E       pex.interpreter.IdentificationError: Failed to identify /home/runner/work/pex/pex/.pyenv_test/pyenv/versions/3.7.11/bin/python3.7: Executing /home/runner/work/pex/pex/.pyenv_test/pyenv/versions/3.7.11/bin/python3.7 -s -c import os
E       import sys
E       
E       from pex.common import atomic_directory, safe_open
E       from pex.interpreter import PythonIdentity
E       
E       
E       encoded_identity = PythonIdentity.get(binary='/home/runner/work/pex/pex/.pyenv_test/pyenv/versions/3.7.11/bin/python3.7').encode()
E       sys.stdout.write(encoded_identity)
E       with atomic_directory('/tmp/tmpul4h6mk3/interpreters/ff344dde7b29efd041934e9cdf9ebf323d71360c/e9617385ce8851a1cdd79e5453a4e742d24741ce/c4e95133eacb923d540d7964729a26d52b86b26a', exclusive=False) as cache_dir:
E           if not cache_dir.is_finalized:
E               with safe_open(
E                   os.path.join(cache_dir.work_dir, 'INTERP-INFO'), 'w'
E               ) as fp:
E                   fp.write(encoded_identity)
E        failed with 1
E       STDERR:
E       Could not find platform dependent libraries <exec_prefix>
E       Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
E       Traceback (most recent call last):
E         File "<string>", line 4, in <module>
E         File "/tmp/tmpul4h6mk3/isolated/fefc9fcb79c484c08c57bf84a3fb448f31cf7df2/pex/common.py", line 9, in <module>
E           import fcntl
E       ModuleNotFoundError: No module named 'fcntl'

pex/testing.py:337: AssertionError
========= 1 failed, 112 passed, 3 skipped, 1 xfailed in 744.10 seconds =========
ERROR: InvocationError for command /home/runner/work/pex/pex/.tox/py39-integration/bin/pytest -n auto tests/test_integration.py -vvs (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py39-integration: commands failed
```

**Comment by jsirois** [comment]
This appears to have been an issue with LD_LIBRARY_PATH influencing Pex pyenv test interpreters to load the wrong .so despite pyenv_build attempting to bake this into the Python with rpath. I worked around by side-stepping the issue and ensuring such conflicting LD_LIBRARY_PATH entries were not present on Linux CI shards.

**Comment by jsirois** [comment]
We shall see...
