### ISSUE TITLE
Jinja Templates not found with .pex, works with .whl install

### ISSUE THREAD

**Issue by FilBot3** [pantsbuild/pex#1393]
# The Details

I am trying to build a Python 3.9 project I made into a `.pex` executable. I have made a few other Python projects into `.pex` files, but this is giving me fits. For some reason, Jinja2 cannot find the templates that are in the module when using the `.pex` form, but when I do a `poetry build` and create a `.whl` file, that works just fine.

## Error Output

<details>

```bash
➜  Python cd ansible_project_template 
➜  ansible_project_template git:(main) ✗ make pex
poetry run pex \
	--requirement=requirements.txt \
	--sources-directory=src \
	--entry-point=ansible_project_template \
	--output-file=ansible_project_template.pex
➜  ansible_project_template git:(main) ✗ ./ansible_project_template.pex test01
Traceback (most recent call last):
  File "/home/filbot/Documents/Development/Python/ansible_project_template/ansible_project_template.pex/.bootstrap/pex/pex.py", line 483, in execute
  File "/home/filbot/Documents/Development/Python/ansible_project_template/ansible_project_template.pex/.bootstrap/pex/pex.py", line 401, in _wrap_coverage
  File "/home/filbot/Documents/Development/Python/ansible_project_template/ansible_project_template.pex/.bootstrap/pex/pex.py", line 432, in _wrap_profiling
  File "/home/filbot/Documents/Development/Python/ansible_project_template/ansible_project_template.pex/.bootstrap/pex/pex.py", line 539, in _execute
  File "/home/filbot/Documents/Development/Python/ansible_project_template/ansible_project_template.pex/.bootstrap/pex/pex.py", line 666, in execute_entry
  File "/home/filbot/Documents/Development/Python/ansible_project_template/ansible_project_template.pex/.bootstrap/pex/pex.py", line 678, in execute_module
  File "/usr/lib/python3.9/runpy.py", line 213, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/filbot/Documents/Development/Python/ansible_project_template/ansible_project_template.pex/ansible_project_template/__main__.py", line 24, in <module>
  File "/home/filbot/Documents/Development/Python/ansible_project_template/ansible_project_template.pex/ansible_project_template/create_project.py", line 44, in main
  File "/home/filbot/Documents/Development/Python/ansible_project_template/ansible_project_template.pex/ansible_project_template/create_project.py", line 15, in write_jinja_template
  File "/home/filbot/.pex/installed_wheels/db210cdb4e96524d8fe39f59c3dbe0bfc4378665/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/filbot/.pex/installed_wheels/db210cdb4e96524d8fe39f59c3dbe0bfc4378665/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/filbot/.pex/installed_wheels/db210cdb4e96524d8fe39f59c3dbe0bfc4378665/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/filbot/.pex/installed_wheels/db210cdb4e96524d8fe39f59c3dbe0bfc4378665/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: Makefile.j2
➜  ansible_project_template git:(main) ✗
```

</details>

When I unzip the `.pex` file though, I see the template files directly in the module.

<details>

```bash
➜  ansible_project_template git:(main) ✗ unzip ansible_project_template.pex -d extracted
Archive:  ansible_project_template.pex
   creating: extracted/.bootstrap/
   creating: extracted/.bootstrap/pex/
  inflating: extracted/.bootstrap/pex/__init__.py  
  inflating: extracted/.bootstrap/pex/__main__.py  
  inflating: extracted/.bootstrap/pex/attrs.py  
  inflating: extracted/.bootstrap/pex/bootstrap.py  
  inflating: extracted/.bootstrap/pex/common.py  
  inflating: extracted/.bootstrap/pex/compatibility.py  
  inflating: extracted/.bootstrap/pex/compiler.py  
  inflating: extracted/.bootstrap/pex/dist_metadata.py  
  inflating: extracted/.bootstrap/pex/distribution_target.py  
  inflating: extracted/.bootstrap/pex/environment.py  
  inflating: extracted/.bootstrap/pex/executor.py  
  inflating: extracted/.bootstrap/pex/finders.py  
  inflating: extracted/.bootstrap/pex/inherit_path.py  
  inflating: extracted/.bootstrap/pex/interpreter.py  
  inflating: extracted/.bootstrap/pex/interpreter_constraints.py  
  inflating: extracted/.bootstrap/pex/jobs.py  
  inflating: extracted/.bootstrap/pex/network_configuration.py  
  inflating: extracted/.bootstrap/pex/orderedset.py  
  inflating: extracted/.bootstrap/pex/pep_503.py  
  inflating: extracted/.bootstrap/pex/pex.py  
  inflating: extracted/.bootstrap/pex/pex_bootstrapper.py  
  inflating: extracted/.bootstrap/pex/pex_builder.py  
  inflating: extracted/.bootstrap/pex/pex_info.py  
  inflating: extracted/.bootstrap/pex/pex_warnings.py  
  inflating: extracted/.bootstrap/pex/pip.py  
  inflating: extracted/.bootstrap/pex/platforms.py  
  inflating: extracted/.bootstrap/pex/pyenv.py  
  inflating: extracted/.bootstrap/pex/requirements.py  
  inflating: extracted/.bootstrap/pex/resolver.py  
  inflating: extracted/.bootstrap/pex/testing.py  
   creating: extracted/.bootstrap/pex/third_party/
  inflating: extracted/.bootstrap/pex/third_party/__init__.py  
  inflating: extracted/.bootstrap/pex/tracer.py  
  inflating: extracted/.bootstrap/pex/typing.py  
  inflating: extracted/.bootstrap/pex/util.py  
  inflating: extracted/.bootstrap/pex/variables.py  
   creating: extracted/.bootstrap/pex/vendor/
  inflating: extracted/.bootstrap/pex/vendor/__init__.py  
   creating: extracted/.bootstrap/pex/vendor/_vendored/
  inflating: extracted/.bootstrap/pex/vendor/_vendored/__init__.py  
   creating: extracted/.bootstrap/pex/vendor/_vendored/attrs/
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/__init__.py  
   creating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/__init__.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/__init__.pyi  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/_compat.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/_config.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/_funcs.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/_make.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/_next_gen.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/_version_info.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/_version_info.pyi  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/converters.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/converters.pyi  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/exceptions.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/exceptions.pyi  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/filters.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/filters.pyi  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/py.typed  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/setters.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/setters.pyi  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/validators.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/attrs/attr/validators.pyi  
   creating: extracted/.bootstrap/pex/vendor/_vendored/packaging/
  inflating: extracted/.bootstrap/pex/vendor/_vendored/packaging/__init__.py  
   creating: extracted/.bootstrap/pex/vendor/_vendored/packaging/packaging/
  inflating: extracted/.bootstrap/pex/vendor/_vendored/packaging/packaging/__about__.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/packaging/packaging/__init__.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/packaging/packaging/_compat.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/packaging/packaging/_structures.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/packaging/packaging/_typing.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/packaging/packaging/markers.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/packaging/packaging/py.typed  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/packaging/packaging/requirements.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/packaging/packaging/specifiers.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/packaging/packaging/tags.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/packaging/packaging/utils.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/packaging/packaging/version.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/packaging/pyparsing.py  
   creating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/
  inflating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/__init__.py  
   creating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/
  inflating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/__init__.py  
   creating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/_vendor/
  inflating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/_vendor/__init__.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/_vendor/appdirs.py  
   creating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/_vendor/packaging/
  inflating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/_vendor/packaging/__about__.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/_vendor/packaging/__init__.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/_vendor/packaging/_compat.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/_vendor/packaging/_structures.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/_vendor/packaging/markers.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/_vendor/packaging/requirements.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/_vendor/packaging/specifiers.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/_vendor/packaging/utils.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/_vendor/packaging/version.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/_vendor/pyparsing.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/_vendor/six.py  
   creating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/extern/
  inflating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/extern/__init__.py  
  inflating: extracted/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/py31compat.py  
  inflating: extracted/.bootstrap/pex/venv_bin_path.py  
  inflating: extracted/.bootstrap/pex/version.py  
   creating: extracted/.deps/
   creating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/
   creating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/Jinja2-2.11.3.dist-info/
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/Jinja2-2.11.3.dist-info/INSTALLER  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/Jinja2-2.11.3.dist-info/LICENSE.rst  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/Jinja2-2.11.3.dist-info/METADATA  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/Jinja2-2.11.3.dist-info/RECORD  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/Jinja2-2.11.3.dist-info/REQUESTED  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/Jinja2-2.11.3.dist-info/WHEEL  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/Jinja2-2.11.3.dist-info/entry_points.txt  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/Jinja2-2.11.3.dist-info/top_level.txt  
   creating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__init__.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/_compat.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/_identifier.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/asyncfilters.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/asyncsupport.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/bccache.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/compiler.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/constants.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/debug.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/defaults.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/environment.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/exceptions.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/ext.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/filters.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/idtracking.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/lexer.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/loaders.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/meta.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/nativetypes.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/nodes.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/optimizer.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/parser.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/runtime.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/sandbox.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/tests.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/utils.py  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/visitor.py  
   creating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/__init__.cpython-39.pyc  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/_compat.cpython-39.pyc  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/_identifier.cpython-39.pyc  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/bccache.cpython-39.pyc  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/compiler.cpython-39.pyc  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/defaults.cpython-39.pyc  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/environment.cpython-39.pyc  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/exceptions.cpython-39.pyc  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/filters.cpython-39.pyc  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/idtracking.cpython-39.pyc  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/lexer.cpython-39.pyc  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/loaders.cpython-39.pyc  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/nodes.cpython-39.pyc  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/optimizer.cpython-39.pyc  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/parser.cpython-39.pyc  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/runtime.cpython-39.pyc  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/tests.cpython-39.pyc  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/utils.cpython-39.pyc  
  inflating: extracted/.deps/Jinja2-2.11.3-py2.py3-none-any.whl/jinja2/__pycache__/visitor.cpython-39.pyc  
   creating: extracted/.deps/MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl/
   creating: extracted/.deps/MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl/MarkupSafe-1.1.1.dist-info/
  inflating: extracted/.deps/MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl/MarkupSafe-1.1.1.dist-info/INSTALLER  
  inflating: extracted/.deps/MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl/MarkupSafe-1.1.1.dist-info/LICENSE.rst  
  inflating: extracted/.deps/MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl/MarkupSafe-1.1.1.dist-info/METADATA  
  inflating: extracted/.deps/MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl/MarkupSafe-1.1.1.dist-info/RECORD  
  inflating: extracted/.deps/MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl/MarkupSafe-1.1.1.dist-info/REQUESTED  
  inflating: extracted/.deps/MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl/MarkupSafe-1.1.1.dist-info/WHEEL  
  inflating: extracted/.deps/MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl/MarkupSafe-1.1.1.dist-info/top_level.txt  
   creating: extracted/.deps/MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl/markupsafe/
  inflating: extracted/.deps/MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl/markupsafe/__init__.py  
  inflating: extracted/.deps/MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl/markupsafe/_compat.py  
  inflating: extracted/.deps/MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl/markupsafe/_constants.py  
  inflating: extracted/.deps/MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl/markupsafe/_native.py  
  inflating: extracted/.deps/MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl/markupsafe/_speedups.c  
  inflating: extracted/.deps/MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl/markupsafe/_speedups.cpython-39-x86_64-linux-gnu.so  
   creating: extracted/.deps/MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl/markupsafe/__pycache__/
  inflating: extracted/.deps/MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl/markupsafe/__pycache__/__init__.cpython-39.pyc  
  inflating: extracted/.deps/MarkupSafe-1.1.1-cp39-cp39-manylinux2010_x86_64.whl/markupsafe/__pycache__/_compat.cpython-39.pyc  
  inflating: extracted/PEX-INFO      
  inflating: extracted/__main__.py   
   creating: extracted/ansible_project_template/
  inflating: extracted/ansible_project_template/__init__.py  
  inflating: extracted/ansible_project_template/__main__.py  
   creating: extracted/ansible_project_template/__pycache__/
  inflating: extracted/ansible_project_template/__pycache__/__init__.cpython-38.pyc  
  inflating: extracted/ansible_project_template/__pycache__/__init__.cpython-39.pyc  
  inflating: extracted/ansible_project_template/__pycache__/__main__.cpython-38.pyc  
  inflating: extracted/ansible_project_template/__pycache__/__main__.cpython-39.pyc  
  inflating: extracted/ansible_project_template/__pycache__/create_project.cpython-38.pyc  
  inflating: extracted/ansible_project_template/__pycache__/create_project.cpython-39.pyc  
  inflating: extracted/ansible_project_template/create_project.py  
   creating: extracted/ansible_project_template/templates/
  inflating: extracted/ansible_project_template/templates/CHANGELOG.md.j2  
  inflating: extracted/ansible_project_template/templates/LICENSE.md.j2  
  inflating: extracted/ansible_project_template/templates/Makefile.j2  
  inflating: extracted/ansible_project_template/templates/README.md.j2  
  inflating: extracted/ansible_project_template/templates/collections-requirements.yaml.j2  
  inflating: extracted/ansible_project_template/templates/inventory.yaml.j2  
  inflating: extracted/ansible_project_template/templates/playbook-example.yaml.j2  
  inflating: extracted/ansible_project_template/templates/roles-requirements.yaml.j2  
  inflating: extracted/ansible_project_template/templates/vars.yaml.j2  
  inflating: extracted/ansible_project_template/templates/vault.yaml.j2
```

</details>

Then when I `tree` the files, you can see the files there.

<details>

```bash
➜  ansible_project_template git:(main) ✗ cd extracted 
➜  extracted git:(main) ✗ tree
.
├── ansible_project_template
│   ├── create_project.py
│   ├── __init__.py
│   ├── __main__.py
│   ├── __pycache__
│   │   ├── create_project.cpython-38.pyc
│   │   ├── create_project.cpython-39.pyc
│   │   ├── __init__.cpython-38.pyc
│   │   ├── __init__.cpython-39.pyc
│   │   ├── __main__.cpython-38.pyc
│   │   └── __main__.cpython-39.pyc
│   └── templates
│       ├── CHANGELOG.md.j2
│       ├── collections-requirements.yaml.j2
│       ├── inventory.yaml.j2
│       ├── LICENSE.md.j2
│       ├── Makefile.j2
│       ├── playbook-example.yaml.j2
│       ├── README.md.j2
│       ├── roles-requirements.yaml.j2
│       ├── vars.yaml.j2
│       └── vault.yaml.j2
├── __main__.py
└── PEX-INFO

3 directories, 21 files
```

</details>

The main part of logic that I'm using is this (see below). It's not the most elegant. I'm sure there's omething wrong I'm not doing.

<details>

```python
➜  extracted git:(main) ✗ cat ansible_project_template/create_project.py 
#!/usr/bin/env python
"""Create an Ansible Project
"""

import os
import jinja2


def write_jinja_template(path: str, template_name: str, overrides: dict = None):
    """Write a Jinja2 Tempalte to a file.
    """
    template_loader = jinja2.FileSystemLoader(
        searchpath=os.path.dirname(os.path.realpath(__file__)) + '/templates')
    template_env = jinja2.Environment(loader=template_loader)
    template = template_env.get_template(template_name)

    if overrides is not None:
        with open(path, 'w') as file:
            file.write(template.render(overrides))
    else:
        with open(path, 'w') as file:
            file.write(template.render())


def main(name: str = 'Ansible.Project.Example',
         style: str = 'standard') -> int:
    """Main Function

    Parameters
    ----------
    name : str
        The name of the Ansible Project.
    style : str
        The style of Ansible Project to create. There are three types.
          - standard
          - alternative
          - alternative_modified

    Returns
    -------
    None
    """
    os.mkdir(name, mode=0o755)
    write_jinja_template('/'.join([name, 'Makefile']), 'Makefile.j2')

    write_jinja_template('/'.join([name, 'README.md']), 'README.md.j2')

    write_jinja_template('/'.join([name, 'LICENSE.md']), 'LICENSE.md.j2')

    write_jinja_template('/'.join([name, 'CHANGELOG.md']), 'CHANGELOG.md.j2')

    write_jinja_template(
        '/'.join([name, 'playbook-example.yml']), 'playbook-example.yaml.j2')

    if style == 'alternative':
        os.mkdir('/'.join([name, 'roles']), mode=0o755)
        os.makedirs('/'.join([name, 'collections', 'ansible_collections']),
                    mode=0o755)
        os.makedirs(
            '/'.join([name, 'inventories', 'production', 'group_vars', 'all']),
            mode=0o755)
        os.makedirs(
            '/'.join([name, 'inventories', 'production', 'host_vars']),
            mode=0o755)

        os.makedirs(
            '/'.join([name, 'inventories', 'staging', 'group_vars', 'all']),
            mode=0o755)
        os.makedirs(
            '/'.join([name, 'inventories', 'staging', 'host_vars']),
            mode=0o755)
        write_jinja_template(
            '/'.join([name, 'inventories', 'production', 'hosts']),
            'inventory.yaml.j2')

        write_jinja_template(
            '/'.join([name, 'inventories', 'staging', 'hosts']),
            'inventory.yaml.j2')

        write_jinja_template(
            '/'.join([name, 'roles', 'requirements.yml']), 'roles-requirements.yaml.j2')

        write_jinja_template(
            '/'.join([name, 'collections', 'requirements.yml']),
            'collections-requirements.yaml.j2')

        write_jinja_template(
            '/'.join([name, 'inventories',
                      'production', 'group_vars', 'all', 'vars.yml']),
            'vars.yaml.j2')

        write_jinja_template(
            '/'.join([name, 'inventories',
                      'production', 'group_vars', 'all', 'vault.yml']),
            'vault.yaml.j2')

        write_jinja_template(
            '/'.join([name, 'inventories',
                      'production', 'host_vars', 'localhost.yml']),
            'vars.yaml.j2')
        write_jinja_template(
            '/'.join([name, 'inventories',
                      'staging', 'group_vars', 'all', 'vars.yml']),
            'vars.yaml.j2')

        write_jinja_template(
            '/'.join([name, 'inventories',
                      'staging', 'group_vars', 'all', 'vault.yml']),
            'vault.yaml.j2')

        write_jinja_template(
            '/'.join([name, 'inventories',
                      'staging', 'host_vars', 'localhost.yml']),
            'vars.yaml.j2')
    elif style == 'alternative_modified':
        os.mkdir('/'.join([name, 'roles']), mode=0o755)
        os.makedirs('/'.join([name, 'collections', 'ansible_collections']),
                    mode=0o755)
        os.makedirs(
            '/'.join([name, 'inventory', 'group_vars', 'all']),
            mode=0o755)
        os.makedirs(
            '/'.join([name, 'inventory',  'host_vars']),
            mode=0o755)

        write_jinja_template(
            '/'.join([name, 'inventory', 'hosts.yaml']),
            'inventory.yaml.j2')

        write_jinja_template(
            '/'.join([name, 'roles', 'requirements.yml']), 'roles-requirements.yaml.j2')

        write_jinja_template(
            '/'.join([name, 'collections', 'requirements.yml']),
            'collections-requirements.yaml.j2')

        write_jinja_template(
            '/'.join([name, 'inventory',
                      'group_vars', 'all', 'vars.yml']),
            'vars.yaml.j2')

        write_jinja_template(
            '/'.join([name, 'inventory',
                      'group_vars', 'all', 'vault.yml']),
            'vault.yaml.j2')

        write_jinja_template(
            '/'.join([name, 'inventory',
                      'host_vars', 'localhost.yml']),
            'vars.yaml.j2')
    else:
        os.mkdir('/'.join([name, 'roles']), mode=0o755)
        os.makedirs('/'.join([name, 'collections', 'ansible_collections']),
                    mode=0o755)
        os.makedirs('/'.join([name, 'group_vars', 'all']), mode=0o755)
        os.mkdir('/'.join([name, 'host_vars']), mode=0o755)

        write_jinja_template(
            '/'.join([name, 'production']), 'inventory.yaml.j2')

        write_jinja_template('/'.join([name, 'staging']), 'inventory.yaml.j2')

        write_jinja_template(
            '/'.join([name, 'roles', 'requirements.yml']), 'roles-requirements.yaml.j2')

        write_jinja_template(
            '/'.join([name, 'collections', 'requirements.yml']),
            'collections-requirements.yaml.j2')

        write_jinja_template(
            '/'.join([name, 'group_vars', 'all', 'vars.yml']), 'vars.yaml.j2')

        write_jinja_template(
            '/'.join([name, 'group_vars', 'all', 'vault.yml']), 'vault.yaml.j2')

        write_jinja_template(
            '/'.join([name, 'host_vars', 'localhost.yml']), 'vars.yaml.j2')


if __name__ == '__main__':
    main()
```

</details>

How do I make Python or Pex realize taht the templates are where I said they are?

**Comment by jsirois** [comment]
You've hit an issue that trips alot of folks up. Pex, by default, produces a [zipapp](https://docs.python.org/3/library/zipapp.html) and zipapps run from inside a zip file. As such, normal file system access of the zipped up code doesn't work. You use a `jinja2.FileSystemLoader` and so that's the problem. Your app is not running from the normal filesystem but from a zip. You could either switch to using a [`jinja2.PackageLoader`](https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.PackageLoader), or just tell Pex to create a PEX file that does not run from a zip. There are three options:
```
pex --help
...
PEX output options:
  Tailor the behavior of the emitted .pex file if -o is specified.

...
  --zip-safe, --not-zip-safe
                        Whether or not the sources in the pex file are zip safe. If they are not zip safe, they will be written to disk prior to execution. Also see --unzip which will cause the complete pex file, including dependencies, to be unzipped. (default: True)
  --unzip, --no-unzip   Whether or not the pex file should be unzipped before executing it. If the pex file will be run multiple times under a stable runtime PEX_ROOT the unzipping will only be performed once and subsequent runs will enjoy lower startup latency. (default: False)
  --venv [{prepend,append}]
                        Convert the pex file to a venv before executing it. If 'prepend' or 'append' is specified, then all scripts and console scripts provided by distributions in the pex file will be added to the PATH in the corresponding position. If the the pex file will be run
                        multiple times under a stable runtime PEX_ROOT, the venv creation will only be done once and subsequent runs will enjoy lower startup latency. (default: False)
...

You might experiment with all three, but it's likely `--unzip` has the fastest cold startup time and `--venv` definitely will have the fastest warm startup time (if your PEX file will be run multiple times on a given machine, `--venv` is what you want).

**Comment by jsirois** [comment]
@FilBot3 I'm closing this as an answered question but please report back if my answer is lacking or doesn't actually help you.

**Comment by FilBot3** [comment]
Thank you @jsirois , your information and suggestion helped out. I was able to generate a `.pex` file and have it run.

```bash
➜  ansible_project_template git:(main) ✗ make pex
poetry run pex \
	--unzip \
	--not-zip-safe \
	--requirement=requirements.txt \
	--sources-directory=src \
	--entry-point=ansible_project_template \
	--output-file=ansible_project_template.pex
```

I added the `--not-zip-safe` and `--unzip` options. Those seemed to do the trick.

**Comment by jsirois** [comment]
Great! Note - you should just need one of those options; not both.
