### ISSUE TITLE
"too many values to unpack" when parsing interpreter versions

### ISSUE THREAD

**Issue by kwlzn** [pantsbuild/pex#140]
in pex as used by pants, we've observed about a half dozen users over the months reporting occasional issues with pants/pex throwing "too many values to unpack". usually clearing the interpreter cache fixes this - but it happens frequently enough that I think it should be repaired.

the traceback is:

```
Exception caught:
  File "/Users/easebiomo/.pants.d/bin/pants.pex/pants-1.2.3rc7-testing-py27.pex/.bootstrap/_pex/pex.py", line 271, in execute
    self.execute_entry(entry_point, args)
  File "/Users/easebiomo/.pants.d/bin/pants.pex/pants-1.2.3rc7-testing-py27.pex/.bootstrap/_pex/pex.py", line 320, in execute_entry
    runner(entry_point)
  File "/Users/easebiomo/.pants.d/bin/pants.pex/pants-1.2.3rc7-testing-py27.pex/.bootstrap/_pex/pex.py", line 343, in execute_pkg_resources
    runner()
  File "/Users/easebiomo/workspace/source/.pex/install/pantsbuild.pants-0.0.33-py2-none-any.whl.cd9bdb0408ea39e69875c17237da93bc5427dcdf/pantsbuild.pants-0.0.33-py2-none-any.whl/pants/bin/pants_exe.py", line 81, in main
    _run(exiter)
  File "/Users/easebiomo/workspace/source/.pex/install/pantsbuild.pants-0.0.33-py2-none-any.whl.cd9bdb0408ea39e69875c17237da93bc5427dcdf/pantsbuild.pants-0.0.33-py2-none-any.whl/pants/bin/pants_exe.py", line 74, in _run
    result = goal_runner.run()
  File "/Users/easebiomo/workspace/source/.pex/install/pantsbuild.pants-0.0.33-py2-none-any.whl.cd9bdb0408ea39e69875c17237da93bc5427dcdf/pantsbuild.pants-0.0.33-py2-none-any.whl/pants/bin/goal_runner.py", line 218, in run
    result = self._do_run()
  File "/Users/easebiomo/workspace/source/.pex/install/pantsbuild.pants-0.0.33-py2-none-any.whl.cd9bdb0408ea39e69875c17237da93bc5427dcdf/pantsbuild.pants-0.0.33-py2-none-any.whl/pants/bin/goal_runner.py", line 275, in _do_run
    return engine.execute(context, self.goals)
  File "/Users/easebiomo/workspace/source/.pex/install/pantsbuild.pants-0.0.33-py2-none-any.whl.cd9bdb0408ea39e69875c17237da93bc5427dcdf/pantsbuild.pants-0.0.33-py2-none-any.whl/pants/engine/engine.py", line 26, in execute
    self.attempt(context, goals)
  File "/Users/easebiomo/workspace/source/.pex/install/pantsbuild.pants-0.0.33-py2-none-any.whl.cd9bdb0408ea39e69875c17237da93bc5427dcdf/pantsbuild.pants-0.0.33-py2-none-any.whl/pants/engine/round_engine.py", line 212, in attempt
    goal_executor.attempt(explain)
  File "/Users/easebiomo/workspace/source/.pex/install/pantsbuild.pants-0.0.33-py2-none-any.whl.cd9bdb0408ea39e69875c17237da93bc5427dcdf/pantsbuild.pants-0.0.33-py2-none-any.whl/pants/engine/round_engine.py", line 45, in attempt
    task.execute()
  File "/Users/easebiomo/workspace/source/.pex/install/pantsbuild.pants-0.0.33-py2-none-any.whl.cd9bdb0408ea39e69875c17237da93bc5427dcdf/pantsbuild.pants-0.0.33-py2-none-any.whl/pants/backend/python/tasks/python_run.py", line 36, in execute
    interpreter = self.select_interpreter_for_targets(self.context.targets())
  File "/Users/easebiomo/workspace/source/.pex/install/pantsbuild.pants-0.0.33-py2-none-any.whl.cd9bdb0408ea39e69875c17237da93bc5427dcdf/pantsbuild.pants-0.0.33-py2-none-any.whl/pants/backend/python/tasks/python_task.py", line 65, in select_interpreter_for_targets
    allowed_interpreters = OrderedSet(self.interpreter_cache.interpreters)
  File "/Users/easebiomo/workspace/source/.pex/install/pantsbuild.pants-0.0.33-py2-none-any.whl.cd9bdb0408ea39e69875c17237da93bc5427dcdf/pantsbuild.pants-0.0.33-py2-none-any.whl/pants/backend/python/tasks/python_task.py", line 51, in interpreter_cache
    self._interpreter_cache.setup(filters=self._compatibilities)
  File "/Users/easebiomo/workspace/source/.pex/install/pantsbuild.pants-0.0.33-py2-none-any.whl.cd9bdb0408ea39e69875c17237da93bc5427dcdf/pantsbuild.pants-0.0.33-py2-none-any.whl/pants/backend/python/interpreter_cache.py", line 129, in setup
    self._setup_cached(filters)
  File "/Users/easebiomo/workspace/source/.pex/install/pantsbuild.pants-0.0.33-py2-none-any.whl.cd9bdb0408ea39e69875c17237da93bc5427dcdf/pantsbuild.pants-0.0.33-py2-none-any.whl/pants/backend/python/interpreter_cache.py", line 87, in _setup_cached
    pi = self._interpreter_from_path(path, filters)
  File "/Users/easebiomo/workspace/source/.pex/install/pantsbuild.pants-0.0.33-py2-none-any.whl.cd9bdb0408ea39e69875c17237da93bc5427dcdf/pantsbuild.pants-0.0.33-py2-none-any.whl/pants/backend/python/interpreter_cache.py", line 66, in _interpreter_from_path
    identity = PythonIdentity.from_path(interpreter_dir)
  File "/Users/easebiomo/workspace/source/.pex/install/pex-0.8.6-py2.py3-none-any.whl.3cbdb5d909a2f0a8f8d3e8a8dc123e44a80b45a6/pex-0.8.6-py2.py3-none-any.whl/pex/interpreter.py", line 101, in from_path
    major, minor, patch = version.split('.')

Exception message: too many values to unpack
```

in this users case it wound up that PEX was finding an odd interpreter along the lines of "CPython-2.7.6.tmp.XXXXX".

I believe this is caused by the unguarded tuple unpacking present in https://github.com/pantsbuild/pex/blob/master/pex/interpreter.py#L98

e.g.
```
>>> a, b, c = 'CPython-2.7.6.tmp.XXXXX'.split('.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: too many values to unpack
```

**Comment by kwlzn** [comment]
upon further investigation, it appears pex doesn't actually directly utilize from_path - but rather this is likely a side effect of pants' interpreter_cache.py implementation and its usage of pex as a library.

**Comment by alambert** [comment]
FWIW: I ran into the same crash today. I added a print statement inside interpreter.py's from_path() method; when pants crashed, the dirname was "CPython-2.7.10.tmp.135f73fa58eb4eca8bf6c06c9a3d4f73". The directory ./.pants.d/python-setup/interpreters/CPython-2.7.10.tmp.135f73fa58eb4eca8bf6c06c9a3d4f73 existed, so I removed all of .pants.d and was able to run the command successfully.

**Comment by kwlzn** [comment]
recreated this under the pants project: pantsbuild/pants#2038
