### ISSUE TITLE
Pex third_party isolation fails for packed PEX containing Pex 2.1.48+ as a dep.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1447]
Seen over in Pants:
```console
$ git describe
release_2.8.0.dev1
$ PANTS_PEX_RELEASE=STABLE ./build-support/bin/release.sh build-universal-pex
...
[=== 05:36 Checking prebuilt wheels for 2.8.0.dev1+git11bacb90 ===]
All 2 pantsbuild.pants packages were fetched and are valid.
/tmp/tmpb7qudv1z/pex/.deps/pex-2.1.48-py2.py3-none-any.whl/pex/bin/pex.py:1168: PEXWarning: The pex root has been set via PEX_ROOT but --disable-cache is also set. Ignoring PEX_ROOT and disabling caches.
Failed to spawn a job for DistributionTarget(platform=Platform(platform='linux_x86_64', impl='cp', version='38', abi='cp38')): Expected the `pex` module to be available via an installed distribution or else via an installed or loose PEX. Loaded the `pex` module from /tmp/tmpb7qudv1z/pex/.deps/pex-2.1.48-py2.py3-none-any.whl/pex and argv0 is /tmp/tmpb7qudv1z/pex.
Traceback (most recent call last):
  File "/home/jsirois/.cache/pants/named_caches/pex_root/unzipped_pexes/28f4c740b4fd904afa532678dde9783c8d7487c8/.bootstrap/pex/pex.py", line 476, in execute
    exit_value = self._wrap_coverage(self._wrap_profiling, self._execute)
  File "/home/jsirois/.cache/pants/named_caches/pex_root/unzipped_pexes/28f4c740b4fd904afa532678dde9783c8d7487c8/.bootstrap/pex/pex.py", line 401, in _wrap_coverage
    return runner(*args)
  File "/home/jsirois/.cache/pants/named_caches/pex_root/unzipped_pexes/28f4c740b4fd904afa532678dde9783c8d7487c8/.bootstrap/pex/pex.py", line 432, in _wrap_profiling
    return runner(*args)
  File "/home/jsirois/.cache/pants/named_caches/pex_root/unzipped_pexes/28f4c740b4fd904afa532678dde9783c8d7487c8/.bootstrap/pex/pex.py", line 532, in _execute
    return self.execute_entry(self._pex_info.entry_point)
  File "/home/jsirois/.cache/pants/named_caches/pex_root/unzipped_pexes/28f4c740b4fd904afa532678dde9783c8d7487c8/.bootstrap/pex/pex.py", line 679, in execute_entry
    return self.execute_module(entry_point, alter_sys)
  File "/home/jsirois/.cache/pants/named_caches/pex_root/unzipped_pexes/28f4c740b4fd904afa532678dde9783c8d7487c8/.bootstrap/pex/pex.py", line 691, in execute_module
    runpy.run_module(module_name, run_name="__main__", alter_sys=alter_sys)
  File "/home/jsirois/.pyenv/versions/3.7.11/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/home/jsirois/.pyenv/versions/3.7.11/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/jsirois/.pyenv/versions/3.7.11/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jsirois/dev/pantsbuild/pants/.pants.d/tmp7dbk0pvm/build-support/bin/_release_helper.py", line 977, in <module>
    main()
  File "/home/jsirois/dev/pantsbuild/pants/.pants.d/tmp7dbk0pvm/build-support/bin/_release_helper.py", line 965, in main
    build_pex(fetch=True)
  File "/home/jsirois/dev/pantsbuild/pants/.pants.d/tmp7dbk0pvm/build-support/bin/_release_helper.py", line 604, in build_pex
    check=True,
  File "/home/jsirois/.pyenv/versions/3.7.11/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/jsirois/.pyenv/versions/3.7.11/bin/python3.7', '/tmp/tmpb7qudv1z/pex', '-o', 'dist/pants.2.8.0.dev1+git11bacb90.pex', '--no-build', '--no-pypi', '--disable-cache', '-f', '/home/jsirois/dev/pantsbuild/pants/dist/deploy/wheels/pantsbuild.pants/11bacb90b483018c9169dce47901102ac82bcd91/2.8.0.dev1+git11bacb90', '-f', '/home/jsirois/dev/pantsbuild/pants/dist/deploy/wheels/3rdparty/11bacb90b483018c9169dce47901102ac82bcd91/2.8.0.dev1+git11bacb90', '--no-strip-pex-env', '--console-script=pants', '--platform=linux_x86_64-cp-37-m', '--platform=linux_x86_64-cp-38-cp38', '--platform=linux_x86_64-cp-39-cp39', '--platform=macosx_10.15_x86_64-cp-37-m', '--platform=macosx_10.15_x86_64-cp-38-cp38', '--platform=macosx_10.15_x86_64-cp-39-cp39', 'pantsbuild.pants==2.8.0.dev1+git11bacb90']' returned non-zero exit status 1.
```

**Comment by jsirois** [comment]
The issue is in PEX layout identification here:
https://github.com/pantsbuild/pex/blob/e0ad91f7542e174fe878113cbad39823eff4f2a9/pex/layout.py#L277-L282
The `is_python_script` checks the executable bit is set:
https://github.com/pantsbuild/pex/blob/e0ad91f7542e174fe878113cbad39823eff4f2a9/pex/common.py#L514-L516
https://github.com/pantsbuild/pex/blob/e0ad91f7542e174fe878113cbad39823eff4f2a9/pex/common.py#L491-L505

The Pants code in the OP downloads an official Pex PEX and runs it via `python pex`; so it never needs to (re)establish the execute mode bit on the Pex PEX file.
