### ISSUE TITLE
Pex `--platform` does not populate the `platform_machine` env marker.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1488]
The failure looks like so:
```console
$ python -mpex --platform linux_x86_64-cp-39-cp39 sqlalchemy -o sqlalchemy.pex 
ERROR: Exception:
Traceback (most recent call last):
  File "/home/jsirois/.pex/venvs/short/9d336279/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3021, in _dep_map
    return self.__dep_map
  File "/home/jsirois/.pex/venvs/short/9d336279/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jsirois/.pex/venvs/short/9d336279/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/home/jsirois/.pex/venvs/short/9d336279/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/home/jsirois/.pex/venvs/short/9d336279/lib/python3.9/site-packages/pip/_internal/commands/download.py", line 130, in run
    requirement_set = resolver.resolve(
  File "/home/jsirois/.pex/venvs/short/9d336279/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 180, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/jsirois/.pex/venvs/short/9d336279/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 431, in _resolve_one
    set(req_to_install.extras) - set(dist.extras)
  File "/home/jsirois/.pex/venvs/short/9d336279/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2978, in extras
    return [dep for dep in self._dep_map if dep]
  File "/home/jsirois/.pex/venvs/short/9d336279/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3023, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/jsirois/.pex/venvs/short/9d336279/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3040, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/home/jsirois/.pex/venvs/short/9d336279/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3037, in reqs_for_extra
    if not req.marker or req.marker.evaluate({'extra': extra}):
  File "/home/jsirois/.pex/venvs/short/9d336279/lib/python3.9/site-packages/pip/_vendor/packaging/markers.py", line 328, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/home/jsirois/.pex/venvs/short/9d336279/lib/python3.9/site-packages/pip/_vendor/packaging/markers.py", line 239, in _evaluate_markers
    groups[-1].append(_evaluate_markers(marker, environment))
  File "/home/jsirois/.pex/venvs/short/9d336279/lib/python3.9/site-packages/pip/_vendor/packaging/markers.py", line 244, in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
  File "/home/jsirois/.pex/venvs/short/9d336279/lib/python3.9/site-packages/pip/_vendor/packaging/markers.py", line 224, in _get_env
    raise UndefinedEnvironmentName(
pip._vendor.packaging.markers.UndefinedEnvironmentName: 'platform_machine' does not exist in evaluation environment.
pid 14893 -> /home/jsirois/.pex/venvs/1bfd51a9d830d9b6d4e3075cebe5d9107b1b9d2a/108a3ddc84230ab282ea6312e06cb68f51008ce5/pex --disable-pip-version-check --no-python-version-warning --exists-action a --use-deprecated legacy-resolver --isolated -q --cache-dir /home/jsirois/.pex --log /tmp/tmpscrxmds4/pip.log download --dest /tmp/tmp2i5ufoqi/linux_x86_64-cp-39-cp39 --platform manylinux2014_x86_64 --platform linux_x86_64 --implementation cp --python-version 39 --abi cp39 --only-binary :all: sqlalchemy --index-url https://pypi.org/simple --retries 5 --timeout 15 exited with 2 and STDERR:
Failed to resolve for platform linux_x86_64-cp-39-cp39. Resolve requires evaluation of unknown environment marker: 'platform_machine' does not exist in evaluation environment.
```

This is because SQLAlchemy has a `platform_machine` specific dependency on greenlet:
```console
$ unzip -qc wheelhouse/SQLAlchemy-1.4.25-cp39-cp39-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl SQLAlchemy-1.4.25.dist-info/METADATA | grep Requires-Dist
Requires-Dist: importlib-metadata ; python_version < "3.8"
Requires-Dist: greenlet (!=0.4.17) ; python_version >= "3" and (platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32"))))))
Requires-Dist: greenlet (!=0.4.17) ; (python_version >= "3") and extra == 'aiomysql'
Requires-Dist: aiomysql ; (python_version >= "3") and extra == 'aiomysql'
Requires-Dist: typing-extensions (!=3.10.0.1) ; extra == 'aiosqlite'
Requires-Dist: greenlet (!=0.4.17) ; (python_version >= "3") and extra == 'aiosqlite'
Requires-Dist: aiosqlite ; (python_version >= "3") and extra == 'aiosqlite'
Requires-Dist: greenlet (!=0.4.17) ; (python_version >= "3") and extra == 'asyncio'
Requires-Dist: greenlet (!=0.4.17) ; (python_version >= "3") and extra == 'asyncmy'
Requires-Dist: asyncmy (>=0.2.0) ; (python_version >= "3") and extra == 'asyncmy'
Requires-Dist: mariadb (>=1.0.1) ; (python_version >= "3") and extra == 'mariadb_connector'
Requires-Dist: pyodbc ; extra == 'mssql'
Requires-Dist: pymssql ; extra == 'mssql_pymssql'
Requires-Dist: pyodbc ; extra == 'mssql_pyodbc'
Requires-Dist: sqlalchemy2-stubs ; extra == 'mypy'
Requires-Dist: mypy (>=0.910) ; (python_version >= "3") and extra == 'mypy'
Requires-Dist: mysqlclient (<2,>=1.4.0) ; (python_version < "3") and extra == 'mysql'
Requires-Dist: mysqlclient (>=1.4.0) ; (python_version >= "3") and extra == 'mysql'
Requires-Dist: mysql-connector-python ; extra == 'mysql_connector'
Requires-Dist: cx-oracle (<8,>=7) ; (python_version < "3") and extra == 'oracle'
Requires-Dist: cx-oracle (>=7) ; (python_version >= "3") and extra == 'oracle'
Requires-Dist: psycopg2 (>=2.7) ; extra == 'postgresql'
Requires-Dist: greenlet (!=0.4.17) ; (python_version >= "3") and extra == 'postgresql_asyncpg'
Requires-Dist: asyncpg ; (python_version >= "3") and extra == 'postgresql_asyncpg'
Requires-Dist: pg8000 (>=1.16.6) ; extra == 'postgresql_pg8000'
Requires-Dist: psycopg2-binary ; extra == 'postgresql_psycopg2binary'
Requires-Dist: psycopg2cffi ; extra == 'postgresql_psycopg2cffi'
Requires-Dist: pymysql (<1) ; (python_version < "3") and extra == 'pymysql'
Requires-Dist: pymysql ; (python_version >= "3") and extra == 'pymysql'
Requires-Dist: sqlcipher3-binary ; (python_version >= "3") and extra == 'sqlcipher'
```

**Comment by jsirois** [comment]
It seems like we have all the information needed to populate this environment marker from the `--platform`; so this was just an oversight in #1367.
