### ISSUE TITLE
Errors when using PEX_TOOLS=1

### ISSUE THREAD

**Issue by apollo13** [pantsbuild/pex#1510]
Hi, this is solely a UX issue, there doesn't appear to be anything fundamentally broken but it might be confusing to the user.

Running the following commands works:
```
PEX_TOOLS=1 pex --help
PEX_TOOLS=1 pex repository --help
```
Dropping `--help` results in:
```
Traceback (most recent call last):
  File "/home/florian/.pex/unzipped_pexes/01a8d22400b26b1d132a9849fb6e28962f1ecf9e/.bootstrap/pex/pex.py", line 473, in execute
    exit_value = tools.main(pex=PEX(sys.argv[0]))
  File "/home/florian/.pex/unzipped_pexes/01a8d22400b26b1d132a9849fb6e28962f1ecf9e/.bootstrap/pex/tools/main.py", line 78, in main
    with pex_tools.parsed_command() as pex_command, TRACER.timed(
  File "/usr/lib64/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/florian/.pex/unzipped_pexes/01a8d22400b26b1d132a9849fb6e28962f1ecf9e/.bootstrap/pex/commands/command.py", line 488, in parsed_command
    with global_environment(options):
  File "/usr/lib64/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/florian/.pex/unzipped_pexes/01a8d22400b26b1d132a9849fb6e28962f1ecf9e/.bootstrap/pex/commands/command.py", line 372, in global_environment
    with _configured_env(options):
  File "/usr/lib64/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/florian/.pex/unzipped_pexes/01a8d22400b26b1d132a9849fb6e28962f1ecf9e/.bootstrap/pex/commands/command.py", line 353, in _configured_env
    if options.rc_file or not ENV.PEX_IGNORE_RCFILES:
AttributeError: 'Namespace' object has no attribute 'rc_file'
```
in both cases. It would be great if instead if could maybe also show the help (so one can discover subcommands easily)

**Comment by jsirois** [comment]
Thanks for the report @apollo13.
