### ISSUE TITLE
Nondeterministic "invalid command 'bdist_wheel'" resulting in "Untranslateable" exception

### ISSUE THREAD

**Issue by chris-martin** [pantsbuild/pex#158]
I just started using pex. About half of the time I run it, it works great. The other half of the time, it fails like this.

```
> pex --python python2.7 abc.zip -v
**** Failed to install enum34-1.0.4. stdout: :: Packaging enum34

**** Failed to install enum34-1.0.4. stderr:
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'

pex: Failed to install package at /tmp/tmppcotrf/enum34-1.0.4: Failed to install /tmp/tmppcotrf/enum34-1.0.4
Traceback (most recent call last):
  File "/bin/pex", line 9, in <module>
    load_entry_point('pex==1.0.3', 'console_scripts', 'pex')()
  File "/usr/lib/python3.3/site-packages/pex/bin/pex.py", line 509, in main
    pex_builder = build_pex(reqs, options, resolver_options_builder)
  File "/usr/lib/python3.3/site-packages/pex/bin/pex.py", line 471, in build_pex
    resolveds = resolver.resolve(resolvables)
  File "/usr/lib/python3.3/site-packages/pex/resolver.py", line 191, in resolve
    dist = self.build(package, resolvable.options)
  File "/usr/lib/python3.3/site-packages/pex/resolver.py", line 248, in build
    dist = super(CachingResolver, self).build(package, options)
  File "/usr/lib/python3.3/site-packages/pex/resolver.py", line 160, in build
    raise Untranslateable('Package %s is not translateable by %s' % (package, translator))
pex.resolver.Untranslateable: Package SourcePackage('file:///home/chris/.pex/build/enum34-1.0.4.zip') is not translateable by ChainedTranslator(WheelTranslator, EggTranslator, SourceTranslator)
```

In the above example it failed on `enum34`, but which dependency it fails on appears random as well.

**Comment by chris-martin** [comment]
Passing `--no-wheel` seems to serve as a workaround.

I don't know understand the ramifications are, though. Am I missing out on something by doing that?

**Comment by wickman** [comment]
This is because some projects do not use setuptools in their setup.py.  ``bdist_egg`` won't work on them either.  The only reliable way to get around this is to use the ``pex`` tool directly or edit the setup.py and add the preamble: ``import setuptools as distutils``.

**Comment by chris-martin** [comment]
I'm using the latest pypi release, 1.0.3.

**Comment by srobertson** [comment]
I'm seeing this issue with 1.0.3 as well

**Comment by Hunter-Github** [comment]
--no-wheel works for me.

**Comment by mgrandi** [comment]
it seems to happen 100% of the time for me 


```
[2017-01-31 11:23:43] markgrandi@Gypaetus:~/Code/sigfig/rabbitmq_monitor$ pex -r requirements.txt -o ~/rabbitmq_monitor.pex
**** Failed to install arrow-0.8.0 (caused by: NonZeroExit("received exit code 1 during execution of `['/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6', '-', 'bdist_wheel', '--dist-dir=/var/folders/7p/65pblygs2lq0mk242wl3cg240000gn/T/tmpmjul6i29']` while trying to execute `['/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6', '-', 'bdist_wheel', '--dist-dir=/var/folders/7p/65pblygs2lq0mk242wl3cg240000gn/T/tmpmjul6i29']`",)
):
stdout:

stderr:
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'


Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/pex", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pex/bin/pex.py", line 578, in main
    pex_builder = build_pex(reqs, options, resolver_options_builder)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pex/bin/pex.py", line 527, in build_pex
    resolveds = resolver.resolve(resolvables)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pex/resolver.py", line 207, in resolve
    dist = self.build(package, resolvable.options)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pex/resolver.py", line 264, in build
    dist = super(CachingResolver, self).build(package, options)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pex/resolver.py", line 173, in build
    raise Untranslateable('Package %s is not translateable by %s' % (package, translator))
pex.resolver.Untranslateable: Package SourcePackage('file:///Users/markgrandi/.pex/build/arrow-0.8.0.tar.gz') is not translateable by ChainedTranslator(WheelTranslator, EggTranslator, SourceTranslator)
```

**Comment by danmur** [comment]
I've got this happening too. My particular problem appeared to be that the Python interpreter I was using didn't have setuptools available to it.

I'm suspicious of that command it's running though, why is there a hyphen there instead of setup.py?

**Comment by xsteadfastx** [comment]
any news on this? im pretty sure that the interpreter im using has setuptools installed.

**Comment by mgrandi** [comment]
does using '--no-wheel' not help? seems to be a bug specific to handling wheel files

**Comment by kwlzn** [comment]
this isn't pex specific - but in order to have the `bdist_wheel` command, you'd need both `setuptools` and `wheel` installed in the interpreter's environment.

**Comment by kwlzn** [comment]
also noting that `pip install pex` should transitively install both `setuptools` and `wheel` for you, but it's possible that `pip` is not how most folks reporting here are getting `pex` (or perhaps their `pex` versions are really old)? would be interested to understand how this is happening from someone who has it repro'd.

**Comment by jsirois** [comment]
Wow this was old!

I hit this writing a pex unit test last night. The offending code is in [`InstallerBase`](https://github.com/pantsbuild/pex/blob/d1f946c8b46f8c5123b01bcd376c87bb67c8a884/pex/installer.py#L36). Right now , for the `WheelInstaller` we write out:
```
import sys
sys.path.insert(0, u'/home/jsirois/dev/pantsbuild/jsirois-pex/.pyenv_test/versions/3.6.3/lib/python3.6/site-packages'); import setuptools
sys.path.insert(0, '/tmp/tmpdzU0rv/interpreters/CPython-3.6.3/wheel-0.27.0-py3.6.egg'); import wheel

__file__ = 'setup.py'
sys.argv[0] = 'setup.py'
exec(compile(open(__file__, 'rb').read(), __file__, 'exec'))
```

Here - the sys.path.insert lines are randomly order by dict item iteration order, and the order show above is problematic, since `setuptools` is imported before `wheel` is on `sys.path`, foiling discovery of the `wheel` `distutils.commands` `bdist_wheel` entry point.

The fix is to just do all imports after we fully modify `sys.path`.
