### ISSUE TITLE
Venv creation fails when PEX_PATH includes another PEX with overlapping distributions

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1637]
As seen in Pants CI here: https://github.com/pantsbuild/pants/runs/5366819312?check_suite_focus=true#step:14:244
```
Traceback (most recent call last):
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/f24bc43887fbe833662f695d52015ae6960a03e0/.bootstrap/pex/pex.py", line 496, in execute
    exit_value = self._wrap_coverage(self._wrap_profiling, self._execute)
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/f24bc43887fbe833662f695d52015ae6960a03e0/.bootstrap/pex/pex.py", line 401, in _wrap_coverage
    return runner(*args)
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/f24bc43887fbe833662f695d52015ae6960a03e0/.bootstrap/pex/pex.py", line 432, in _wrap_profiling
    return runner(*args)
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/f24bc43887fbe833662f695d52015ae6960a03e0/.bootstrap/pex/pex.py", line 552, in _execute
    return self.execute_entry(self._pex_info.entry_point)
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/f24bc43887fbe833662f695d52015ae6960a03e0/.bootstrap/pex/pex.py", line 688, in execute_entry
    return self.execute_pkg_resources(entry_point)
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/f24bc43887fbe833662f695d52015ae6960a03e0/.bootstrap/pex/pex.py", line 720, in execute_pkg_resources
    return runner()
  File "/home/runner/.cache/pants/named_caches/pex_root/installed_wheels/9c753f809ca916c7792319971e4b0a1289669f9f/pex-2.1.68-py2.py3-none-any.whl/pex/bin/pex.py", line 693, in main
    env=env,
  File "/home/runner/.cache/pants/named_caches/pex_root/installed_wheels/9c753f809ca916c7792319971e4b0a1289669f9f/pex-2.1.68-py2.py3-none-any.whl/pex/bin/pex.py", line 733, in do_main
    seed_info = seed_cache(options, pex, verbose=options.seed == Seed.VERBOSE)
  File "/home/runner/.cache/pants/named_caches/pex_root/installed_wheels/9c753f809ca916c7792319971e4b0a1289669f9f/pex-2.1.68-py2.py3-none-any.whl/pex/bin/pex.py", line 771, in seed_cache
    venv_pex = ensure_venv(pex)
  File "/home/runner/.cache/pants/named_caches/pex_root/installed_wheels/9c753f809ca916c7792319971e4b0a1289669f9f/pex-2.1.68-py2.py3-none-any.whl/pex/pex_bootstrapper.py", line 469, in ensure_venv
    symlink=not pex_info.venv_site_packages_copies,
  File "/home/runner/.cache/pants/named_caches/pex_root/installed_wheels/9c753f809ca916c7792319971e4b0a1289669f9f/pex-2.1.68-py2.py3-none-any.whl/pex/venv/pex.py", line 120, in populate_venv
    record_provenance(_populate_deps(venv, pex, venv_python, symlink))
  File "/home/runner/.cache/pants/named_caches/pex_root/installed_wheels/9c753f809ca916c7792319971e4b0a1289669f9f/pex-2.1.68-py2.py3-none-any.whl/pex/venv/pex.py", line 116, in record_provenance
    for src, dst in src_to_dst:
  File "/home/runner/.cache/pants/named_caches/pex_root/installed_wheels/9c753f809ca916c7792319971e4b0a1289669f9f/pex-2.1.68-py2.py3-none-any.whl/pex/venv/pex.py", line 216, in _populate_deps
    for src, dst in record.reinstall(venv, symlink=symlink, rel_extra_path=rel_extra_path):
  File "/home/runner/.cache/pants/named_caches/pex_root/installed_wheels/9c753f809ca916c7792319971e4b0a1289669f9f/pex-2.1.68-py2.py3-none-any.whl/pex/pep_376.py", line 430, in reinstall
    os.symlink(rel_src, dst)
FileExistsError: [Errno 17] File exists: '../../../../../../installed_wheels/344f2d140a5da7db8bc9a1815c4ef21a7acf78df/typing_extensions-4.0.1-py3-none-any.whl/typing_extensions-4.0.1.dist-info' -> '/home/runner/.cache/pants/named_caches/pex_root/venvs/803bfa7a4272661bf61d0f74b7f68fec85cce03e/869423fe37ea5ac6ac5d56346aa5c96907919ef8.d22ba668af3c4c6f847d6d591b493a71/lib/python3.7/site-packages/typing_extensions-4.0.1.dist-info'
```

The issue here is a PEX_PATH is in play (`pytest.pex:requirements.pex:local_dists.pex`) and more than one PEX provides typing_extensions-4.0.1. Since PEX.resolve does no de-dup:
https://github.com/pantsbuild/pex/blob/6cc144e2d45d1320fda0e1ff9961989dff20580f/pex/pex.py#L115-L119

And since #1630 removed the failure guard from symlink (but only symlink) creation:
https://github.com/pantsbuild/pex/blob/70a2caded62e12ff8ecd97b67d0ea2f89c16b60d/pex/pep_376.py#L423-L430
https://github.com/pantsbuild/pex/blob/70a2caded62e12ff8ecd97b67d0ea2f89c16b60d/pex/pep_376.py#L405-L421

... this long-standing lack of de-duping came to the fore.

**Comment by jsirois** [comment]
Aha. This is pretty narrow. The issue only occurs for distributuons that ship a top-level _module_. Top-level packages work fine since they trigger namespace-package .pth treatment and each gets its own unique site-packages subdir.
