### ISSUE TITLE
`--lock` with no input requirements should resolve the whole lock

### ISSUE THREAD

**Issue by Eric-Arellano** [pantsbuild/pex#1657]
With this lockfile created via `pex3 lock create ansicolors -o colors.lock --indent=2`:

```json
{
  "allow_builds": true,
  "allow_prereleases": false,
  "allow_wheels": true,
  "build_isolation": true,
  "constraints": [],
  "locked_resolves": [
    {
      "locked_requirements": [
        {
          "artifacts": [
            {
              "algorithm": "sha256",
              "hash": "00d2dde5a675579325902536738dd27e4fac1fd68f773fe36c21044eb559e187",
              "url": "https://files.pythonhosted.org/packages/53/18/a56e2fe47b259bb52201093a3a9d4a32014f9d85071ad07e9d60600890ca/ansicolors-1.1.8-py2.py3-none-any.whl"
            }
          ],
          "project_name": "ansicolors",
          "requires_dists": [],
          "requires_python": null,
          "version": "1.1.8"
        }
      ],
      "platform_tag": [
        "cp39",
        "cp39",
        "macosx_11_0_arm64"
      ]
    }
  ],
  "pex_version": "2.1.70",
  "prefer_older_binary": false,
  "requirements": [
    "ansicolors"
  ],
  "requires_python": [],
  "resolver_version": "pip-legacy-resolver",
  "style": "strict",
  "transitive": true,
  "use_pep517": null
}
```

I get this error:

```
❯ ../pex/dist/pex --lock colors.lock
Traceback (most recent call last):
  File "/Users/ericarellano/.pex/unzipped_pexes/4bbee6e719f7c34181394d0293cbdafc19203558/.bootstrap/pex/pex.py", line 503, in execute
    exit_value = self._wrap_coverage(self._wrap_profiling, self._execute)
  File "/Users/ericarellano/.pex/unzipped_pexes/4bbee6e719f7c34181394d0293cbdafc19203558/.bootstrap/pex/pex.py", line 408, in _wrap_coverage
    return runner(*args)
  File "/Users/ericarellano/.pex/unzipped_pexes/4bbee6e719f7c34181394d0293cbdafc19203558/.bootstrap/pex/pex.py", line 439, in _wrap_profiling
    return runner(*args)
  File "/Users/ericarellano/.pex/unzipped_pexes/4bbee6e719f7c34181394d0293cbdafc19203558/.bootstrap/pex/pex.py", line 559, in _execute
    return self.execute_entry(self._pex_info.entry_point)
  File "/Users/ericarellano/.pex/unzipped_pexes/4bbee6e719f7c34181394d0293cbdafc19203558/.bootstrap/pex/pex.py", line 695, in execute_entry
    return self.execute_pkg_resources(entry_point)
  File "/Users/ericarellano/.pex/unzipped_pexes/4bbee6e719f7c34181394d0293cbdafc19203558/.bootstrap/pex/pex.py", line 727, in execute_pkg_resources
    return runner()
  File "/Users/ericarellano/.pex/installed_wheels/b343f539fabf56dc5011ddc42b3cbcfc20790515/pex-2.1.70-py2.py3-none-any.whl/pex/bin/pex.py", line 724, in main
    do_main(
  File "/Users/ericarellano/.pex/installed_wheels/b343f539fabf56dc5011ddc42b3cbcfc20790515/pex-2.1.70-py2.py3-none-any.whl/pex/bin/pex.py", line 745, in do_main
    pex_builder = build_pex(
  File "/Users/ericarellano/.pex/installed_wheels/b343f539fabf56dc5011ddc42b3cbcfc20790515/pex-2.1.70-py2.py3-none-any.whl/pex/bin/pex.py", line 594, in build_pex
    resolve_from_lock(
  File "/Users/ericarellano/.pex/installed_wheels/b343f539fabf56dc5011ddc42b3cbcfc20790515/pex-2.1.70-py2.py3-none-any.whl/pex/resolve/lock_resolver.py", line 137, in resolve_from_lock
    resolve_result = locked_resolve.resolve(
  File "/Users/ericarellano/.pex/installed_wheels/b343f539fabf56dc5011ddc42b3cbcfc20790515/pex-2.1.70-py2.py3-none-any.whl/pex/resolve/locked_resolve.py", line 661, in resolve
    return Resolved.create(
  File "/Users/ericarellano/.pex/installed_wheels/b343f539fabf56dc5011ddc42b3cbcfc20790515/pex-2.1.70-py2.py3-none-any.whl/pex/resolve/locked_resolve.py", line 339, in create
    target_specificity=sum(target_specificities) / len(target_specificities),
ZeroDivisionError: division by zero
```

I believe this implies that `downloadable_requirements` is empty, so this for loop isn't executing, because the `append` is unconditional in the loop body:

https://github.com/pantsbuild/pex/blob/2f2c77227bbda4401054b6ca1b7677ef6a419ed2/pex/resolve/locked_resolve.py#L317-L342

**Comment by Eric-Arellano** [comment]
This was due to me not understanding the right invocation. `pex --lock colors.lock` fails, but `pex --lock colors.lock ansicolors` works spendidly.

@jsirois would you consider a mode where you attempt to install the entire lock contents? That would help Pants out, we have the `[python].run_against_entire_lockfile` option, where Pants is not aware of what all the possible `python_requirement`s are that were used to generate and it would be a slow calculation to do so.

**Comment by jsirois** [comment]
Yes. That was actually intended / worked on. I think --pex-repository works this way now?.

**Comment by Eric-Arellano** [comment]
>  I think --pex-repository works this way now?.

It looks like it. 

> $ pex --pex-repository=colors.pex -o colors.2.pex

--

> That was actually intended / worked on

Would it help for me to pick that up? 

(It might be a good exercise for me to better understand this code.)

**Comment by jsirois** [comment]
I think "picking that up" == solving this issue!
