### ISSUE TITLE
Lockfile: missing `pip.log`

### ISSUE THREAD

**Issue by Eric-Arellano** [pantsbuild/pex#1668]
Using Pex 2.71 and the Docker image `quay.io/pypa/manylinux2014_x86_64:latest`, I get this failure:

```
PEX_SCRIPT=pex3 /opt/python/cp37-cp37m/bin/python ./pex lock create --resolver-version=pip-2020-resolver ansicolors
Traceback (most recent call last):
  File "/root/.pex/venvs/685195326480c4d9d521e9cc3994b066950eeb1e/f084cae1efd893aa7ecfef66d45dea1a5e619caa/pex", line 126, in <module>
    os.execv(script_path, [script_path] + sys.argv[1:])
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/root/.pex/unzipped_pexes/3c037481d92e64c70b4c4d598b63e24e6c2bb819/.bootstrap/pex/pex.py", line 503, in execute
    exit_value = self._wrap_coverage(self._wrap_profiling, self._execute)
  File "/root/.pex/unzipped_pexes/3c037481d92e64c70b4c4d598b63e24e6c2bb819/.bootstrap/pex/pex.py", line 408, in _wrap_coverage
    return runner(*args)
  File "/root/.pex/unzipped_pexes/3c037481d92e64c70b4c4d598b63e24e6c2bb819/.bootstrap/pex/pex.py", line 439, in _wrap_profiling
    return runner(*args)
  File "/root/.pex/unzipped_pexes/3c037481d92e64c70b4c4d598b63e24e6c2bb819/.bootstrap/pex/pex.py", line 553, in _execute
    return self.execute_script(self._pex_info_overrides.script)
  File "/root/.pex/unzipped_pexes/3c037481d92e64c70b4c4d598b63e24e6c2bb819/.bootstrap/pex/pex.py", line 635, in execute_script
    return self.execute_entry(entry_point)
  File "/root/.pex/unzipped_pexes/3c037481d92e64c70b4c4d598b63e24e6c2bb819/.bootstrap/pex/pex.py", line 695, in execute_entry
    return self.execute_pkg_resources(entry_point)
  File "/root/.pex/unzipped_pexes/3c037481d92e64c70b4c4d598b63e24e6c2bb819/.bootstrap/pex/pex.py", line 727, in execute_pkg_resources
    return runner()
  File "/root/.pex/installed_wheels/9fb4bc59f7085c6133bed415fd8806a166d6f472798f2350158f7f0a710ec0f6/pex-2.1.71-py2.py3-none-any.whl/pex/cli/pex.py", line 30, in main
    result = catch(command.run)
  File "/root/.pex/installed_wheels/9fb4bc59f7085c6133bed415fd8806a166d6f472798f2350158f7f0a710ec0f6/pex-2.1.71-py2.py3-none-any.whl/pex/result.py", line 101, in catch
    return func(*args, **kwargs)
  File "/root/.pex/installed_wheels/9fb4bc59f7085c6133bed415fd8806a166d6f472798f2350158f7f0a710ec0f6/pex-2.1.71-py2.py3-none-any.whl/pex/cli/command.py", line 84, in run
    return subcommand_func(self)
  File "/root/.pex/installed_wheels/9fb4bc59f7085c6133bed415fd8806a166d6f472798f2350158f7f0a710ec0f6/pex-2.1.71-py2.py3-none-any.whl/pex/cli/commands/lock.py", line 248, in _create
    pip_configuration=pip_configuration,
  File "/root/.pex/installed_wheels/9fb4bc59f7085c6133bed415fd8806a166d6f472798f2350158f7f0a710ec0f6/pex-2.1.71-py2.py3-none-any.whl/pex/resolve/lockfile/__init__.py", line 253, in create
    dest=dest,
  File "/root/.pex/installed_wheels/9fb4bc59f7085c6133bed415fd8806a166d6f472798f2350158f7f0a710ec0f6/pex-2.1.71-py2.py3-none-any.whl/pex/resolver.py", line 1200, in download
    lock_configuration=lock_configuration,
  File "/root/.pex/installed_wheels/9fb4bc59f7085c6133bed415fd8806a166d6f472798f2350158f7f0a710ec0f6/pex-2.1.71-py2.py3-none-any.whl/pex/resolver.py", line 1086, in _download_internal
    dest=dest, max_parallel_jobs=max_parallel_jobs
  File "/root/.pex/installed_wheels/9fb4bc59f7085c6133bed415fd8806a166d6f472798f2350158f7f0a710ec0f6/pex-2.1.71-py2.py3-none-any.whl/pex/resolver.py", line 141, in download_distributions
    max_jobs=max_parallel_jobs,
  File "/root/.pex/installed_wheels/9fb4bc59f7085c6133bed415fd8806a166d6f472798f2350158f7f0a710ec0f6/pex-2.1.71-py2.py3-none-any.whl/pex/jobs.py", line 512, in execute_parallel
    yield spawn_result.spawned_job.await_result()
  File "/root/.pex/installed_wheels/9fb4bc59f7085c6133bed415fd8806a166d6f472798f2350158f7f0a710ec0f6/pex-2.1.71-py2.py3-none-any.whl/pex/jobs.py", line 216, in await_result
    job.wait()
  File "/root/.pex/installed_wheels/9fb4bc59f7085c6133bed415fd8806a166d6f472798f2350158f7f0a710ec0f6/pex-2.1.71-py2.py3-none-any.whl/pex/jobs.py", line 75, in wait
    self._check_returncode(stderr)
  File "/root/.pex/installed_wheels/9fb4bc59f7085c6133bed415fd8806a166d6f472798f2350158f7f0a710ec0f6/pex-2.1.71-py2.py3-none-any.whl/pex/pip.py", line 450, in _check_returncode
    with open(self._log, "r") as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp8czrmzg8/pip.log'
```

It's deterministic, but I can't get it to happen on my mac. Using the old resolver returns this error. 

```
Traceback (most recent call last):
  File "/root/.pex/venvs/685195326480c4d9d521e9cc3994b066950eeb1e/f084cae1efd893aa7ecfef66d45dea1a5e619caa/pex", line 126, in <module>
    os.execv(script_path, [script_path] + sys.argv[1:])
FileNotFoundError: [Errno 2] No such file or directory
pid 751 -> /root/.pex/venvs/685195326480c4d9d521e9cc3994b066950eeb1e/f084cae1efd893aa7ecfef66d45dea1a5e619caa/pex --disable-pip-version-check --no-python-version-warning --exists-action a --use-deprecated legacy-resolver --isolated -q --cache-dir /root/.pex --log /tmp/tmpu7jsac5m/pip.log download --dest /tmp/tmpdpb9zdq_/opt._internal.cpython-3.7.12.bin.python3.7 ansicolors --index-url https://pypi.org/simple --retries 5 --timeout 15 exited with 1 and STDERR:
None
```

**Comment by jsirois** [comment]
Noting this is specifically a Pex PEX issue. Eric's odd looking choice of means to execute Pex here are intended and the issue. Pants execute Pex this way.

**Comment by jsirois** [comment]
Specifically, this is the Pex dogfood Pip venv PEX being used internally looking for and not finding `pex3`. That Pip venv definitely doesn't and shouldn't have `pex3`; so that much is good. The only question is how `PEX_SCRIPT` is making it down there now when it apparently wasn't before.

**Comment by jsirois** [comment]
I'm not sure how this ever worked:
```
^jsirois@gill ~/dev/pantsbuild/pex ((v2.1.60)|BISECTING) $ rm -rf .tox dist /tmp/pex_root && tox -epackage -- --local && PEX_ROOT=/tmp/pex_root PEX_SCRIPT=pex3 /usr/bin/python3.7 dist/pex lock create --resolver-version=pip-2020-resolver ansicolors --indent 2
package create: /home/jsirois/dev/pantsbuild/pex/.tox/package
package installdeps: flit, pygments, toml
package installed: certifi==2021.10.8,charset-normalizer==2.0.12,docutils==0.18.1,flit==3.7.1,flit_core==3.7.1,idna==3.3,Pygments==2.11.2,requests==2.27.1,toml==0.10.2,tomli==2.0.1,tomli_w==1.0.0,urllib3==1.26.8
package run-test-pre: PYTHONHASHSEED='2745318215'
package run-test: commands[0] | python scripts/package.py --local
Building Pex PEX to `dist/pex` ...
Built Pex PEX @ v2.1.60:
sha256: 7df92784aa8a8b0ed2ce4bbc99388fb2cb5b6e7966ab6a1295ff25d399d25fb2
  size: 3693748
____________________________________________________________________________________________________________________________________ summary ____________________________________________________________________________________________________________________________________
  package: commands succeeded
  congratulations :)
Traceback (most recent call last):
  File "/tmp/pex_root/venvs/d2793a662f3a73ad3be3ab7149bad4426b7468b5/8526d9ba87349150aa1391090e89d679ed25a846/pex", line 111, in <module>
    os.execv(script_path, [script_path] + sys.argv[1:])
FileNotFoundError: [Errno 2] No such file or directory
```

Here Pex 2.1.60 was the version the `PEX_SCRIPT=pex3` means of invoking the `pex.cli` module was 1st introduced in Pants.
