### ISSUE TITLE
Pex's fetcher falls back to `certifi` if `--cert` not specified

### ISSUE THREAD

**Issue by Eric-Arellano** [pantsbuild/pex#1674]
This might not actually be a bug - this is only a brain dump.

When resolving a lock via `--lock`, the build fails if `SSL_CERT_FILE` is unset when it normally would be set:

```
❯ docker run -it quay.io/pypa/manylinux2014_x86_64:latest /bin/bash
[root@a4c1c141b60e /]# curl -L -O https://github.com/pantsbuild/pex/releases/download/v2.1.72/pex
[root@a4c1c141b60e /]# PEX_SCRIPT=pex3 SSL_CERT_FILE='' /opt/_internal/cpython-3.7.12/bin/python3.7 ./pex lock create ansicolors --disable-cache -o color.lock
[root@a4c1c141b60e /]# SSL_CERT_FILE='' /opt/_internal/cpython-3.7.12/bin/python3.7 ./pex --disable-cache --lock colors.lock
Traceback (most recent call last):
  File "/root/.pex/unzipped_pexes/38cdfc09438399cde0c3c3c4ee091074f928b118/.bootstrap/pex/pex.py", line 504, in execute
    exit_value = self._wrap_coverage(self._wrap_profiling, self._execute)
  File "/root/.pex/unzipped_pexes/38cdfc09438399cde0c3c3c4ee091074f928b118/.bootstrap/pex/pex.py", line 409, in _wrap_coverage
    return runner(*args)
  File "/root/.pex/unzipped_pexes/38cdfc09438399cde0c3c3c4ee091074f928b118/.bootstrap/pex/pex.py", line 440, in _wrap_profiling
    return runner(*args)
  File "/root/.pex/unzipped_pexes/38cdfc09438399cde0c3c3c4ee091074f928b118/.bootstrap/pex/pex.py", line 560, in _execute
    return self.execute_entry(self._pex_info.entry_point)
  File "/root/.pex/unzipped_pexes/38cdfc09438399cde0c3c3c4ee091074f928b118/.bootstrap/pex/pex.py", line 696, in execute_entry
    return self.execute_pkg_resources(entry_point)
  File "/root/.pex/unzipped_pexes/38cdfc09438399cde0c3c3c4ee091074f928b118/.bootstrap/pex/pex.py", line 728, in execute_pkg_resources
    return runner()
  File "/root/.pex/installed_wheels/011143db8b77ec9508f2599e80f422621fdb0de7d868cb08cd2f859026236c83/pex-2.1.72-py2.py3-none-any.whl/pex/bin/pex.py", line 730, in main
    env=env,
  File "/root/.pex/installed_wheels/011143db8b77ec9508f2599e80f422621fdb0de7d868cb08cd2f859026236c83/pex-2.1.72-py2.py3-none-any.whl/pex/bin/pex.py", line 750, in do_main
    cache=ENV.PEX_ROOT,
  File "/root/.pex/installed_wheels/011143db8b77ec9508f2599e80f422621fdb0de7d868cb08cd2f859026236c83/pex-2.1.72-py2.py3-none-any.whl/pex/bin/pex.py", line 612, in build_pex
    max_parallel_jobs=pip_configuration.max_jobs,
  File "/root/.pex/installed_wheels/011143db8b77ec9508f2599e80f422621fdb0de7d868cb08cd2f859026236c83/pex-2.1.72-py2.py3-none-any.whl/pex/result.py", line 82, in try_
    raise ResultError(error=result)
pex.result.ResultError: There was 1 error downloading required artifacts:
1. ansicolors 1.1.8 from https://files.pythonhosted.org/packages/53/18/a56e2fe47b259bb52201093a3a9d4a32014f9d85071ad07e9d60600890ca/ansicolors-1.1.8-py2.py3-none-any.whl
    <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>
```

This is not an issue in environments that don't use `SSL_CERT_FILE`.

Setting Pex's `--cert="$SSL_CERT_FILE"` fixes things.

Note that it has not been an issue with other Pex codepaths to unset `SSL_CERT_FILE`, e.g. `pex ansicolors`. John pointed out in DM that with locks, Pex is now doing the download rather than pip:

https://github.com/pantsbuild/pex/blob/a8c681a8e5beeb703f8516c5a46695c3d2705f4d/pex/resolve/lock_resolver.py#L180-L182

This looks particularly relevant:

https://github.com/pantsbuild/pex/blob/a8c681a8e5beeb703f8516c5a46695c3d2705f4d/pex/fetcher.py#L42-L44

**Comment by Eric-Arellano** [comment]
This code all lines up, indeed.

https://github.com/pantsbuild/pex/blob/a8c681a8e5beeb703f8516c5a46695c3d2705f4d/pex/fetcher.py#L42-L44

If you pass `--cert`, then the `SSLContext` will be set to use that. Else, Python's `ssl` will try to load system certificates. PEP 476 states that `SSL_CERT_FILE` will be consulted: https://peps.python.org/pep-0476/#trust-database.

I suspect that pip has more robust SSL fallback logic if `SSL_CERT_FILE`. I got lost trying to read the vendored pip code, but note that pip vendors several libraries like `urllib3` and `requests` which have more robust SSL support than the Python std-lib. So, that likely explains why unsetting `SSL_CERT_FILE` breaks using Python's `ssl` directly, but it does not break pip.

I'm not sure where to go from here: should we change `fetcher.py` to use the vendored pip/urrllib3/requests such that it has the same SSL fallbacks we had previously? Or expect users to either set `--cert` or to not unset `SSL_CERT_FILE`?

**Comment by jsirois** [comment]
Look at https://pypi.org/project/certifi/#description and see how this is used in the vendored code. I just looked at all this for the 1st time and that appears to be the answer for the fallback and a fine sane way for Pex to fallback. So far, Pex has avoided using doubly-vendored code (It patches doubly vendored code in Pip to affect universal locks, but that's a bit different - it's steering Pip, not doing its own thing). I'd love to keep that delineation and just straight up vendor certifi at the top level independent of Pip's vendored copy.

**Comment by Eric-Arellano** [comment]
https://github.com/pantsbuild/pants/pull/14808 means that pantsbuild/pants no longer has a stake in this feature request. 

Shall I close this ticket? Imo it's reasonable to expect that you don't unset `SSL_CERT_FILE` if your environment normally sets it—it's not worth the complexity of vendoring `certiffi` to handle this edge case.

**Comment by jsirois** [comment]
Yeah. If it needs to be resurrected, there is background here. I'll close.
