### ISSUE TITLE
Pex fails to parse wheel tags correctly when resolving from a lock.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1676]
This looks like:
```
$ pex --lock default.lock
Traceback (most recent call last):
  File "/home/jsirois/.venv/pex/bin/pex", line 8, in <module>
    sys.exit(main())
  File "/home/jsirois/.venv/pex/lib/python3.10/site-packages/pex/bin/pex.py", line 724, in main
    do_main(
  File "/home/jsirois/.venv/pex/lib/python3.10/site-packages/pex/bin/pex.py", line 745, in do_main
    pex_builder = build_pex(
  File "/home/jsirois/.venv/pex/lib/python3.10/site-packages/pex/bin/pex.py", line 594, in build_pex
    resolve_from_lock(
  File "/home/jsirois/.venv/pex/lib/python3.10/site-packages/pex/resolve/lock_resolver.py", line 139, in resolve_from_lock
    resolve_result = locked_resolve.resolve(
  File "/home/jsirois/.venv/pex/lib/python3.10/site-packages/pex/resolve/locked_resolve.py", line 586, in resolve
    ranked_artifact = locked_requirement.select_artifact(
  File "/home/jsirois/.venv/pex/lib/python3.10/site-packages/pex/resolve/locked_resolve.py", line 196, in select_artifact
    for tag in artifact.parse_tags():
  File "/home/jsirois/.venv/pex/lib/python3.10/site-packages/pex/resolve/locked_resolve.py", line 111, in parse_tags
    for tag in tags.parse_tag(artifact_stem.split("-", 2)[-1]):
  File "/home/jsirois/.venv/pex/lib/python3.10/site-packages/pex/vendor/_vendored/packaging/packaging/tags.py", line 149, in parse_tag
    interpreters, abis, platforms = tag.split("-")
ValueError: too many values to unpack (expected 3)
```

Where the input is an artifact URL of `https://developer.download.nvidia.com/compute/redist/nvidia-dali-cuda110/nvidia_dali_cuda110-1.11.1-4069477-py3-none-manylinux2014_x86_64.whl`.

The bad code is here:
https://github.com/pantsbuild/pex/blob/a8c681a8e5beeb703f8516c5a46695c3d2705f4d/pex/resolve/locked_resolve.py#L107-L111

That splitting is incorrect when a build tag is present. This is done right in CompatibilityTags here though:
https://github.com/pantsbuild/pex/blob/d5eaaac4d8f5a0c30b91daaba61c1d3dac1928fb/pex/pep_425.py#L67-L78

**Comment by jsirois** [comment]
This is also done right, but with copy-pasta, here:
https://github.com/pantsbuild/pex/blob/39d24eceff202abc26542d1c0eb3b6666b7b3a52/pex/environment.py#L289-L296

The fix should centralize all these spots on `CompatibilityTags` since its factored out and unit tested.
