### ISSUE TITLE
"Resource deadlock avoided" when creating multiple `--venv` PEXs in parallel

### ISSUE THREAD

**Issue by thejcannon** [pantsbuild/pex#1693]
Testing out some change in Pants, I create some (>10 < 60) number of processes responsible for creating a PEX venv (`--venv`) using a PEX lockfile (`--lock`) specifying some requirement strings which among the processes are likely highly overlapping yet unique subset of my lockfile.

The stacktrace is at the end of this issue. The issue is regularly reproducible in our work repo, but not reproducible in Pants' own repo with the relevant Pants code running (Pants is only relevant because that's how I'm opening the N processes).

Let me know what else you need to help debug and solve.

Stacktrace:
```
Traceback (most recent call last):                                                                                                                                            File "/home/joshuacannon/.cache/pants/named_caches/pex_root/unzipped_pexes/15004f7f47d92f2a9c0b754a1c6d2997f332ea44/.bootstrap/pex/pex.py", line 504, in execute          
    exit_value = self._wrap_coverage(self._wrap_profiling, self._execute)                                                                                                     File "/home/joshuacannon/.cache/pants/named_caches/pex_root/unzipped_pexes/15004f7f47d92f2a9c0b754a1c6d2997f332ea44/.bootstrap/pex/pex.py", line 409, in _wrap_coverage   
    return runner(*args)                                                                                                                                                      File "/home/joshuacannon/.cache/pants/named_caches/pex_root/unzipped_pexes/15004f7f47d92f2a9c0b754a1c6d2997f332ea44/.bootstrap/pex/pex.py", line 440, in _wrap_profiling  
    return runner(*args)                                                                                                                                                      File "/home/joshuacannon/.cache/pants/named_caches/pex_root/unzipped_pexes/15004f7f47d92f2a9c0b754a1c6d2997f332ea44/.bootstrap/pex/pex.py", line 560, in _execute         
    return self.execute_entry(self._pex_info.entry_point)                                                                                                                   
  File "/home/joshuacannon/.cache/pants/named_caches/pex_root/unzipped_pexes/15004f7f47d92f2a9c0b754a1c6d2997f332ea44/.bootstrap/pex/pex.py", line 696, in execute_entry
    return self.execute_pkg_resources(entry_point)
  File "/home/joshuacannon/.cache/pants/named_caches/pex_root/unzipped_pexes/15004f7f47d92f2a9c0b754a1c6d2997f332ea44/.bootstrap/pex/pex.py", line 728, in execute_pkg_resources
    return runner()
  File "/home/joshuacannon/.cache/pants/named_caches/pex_root/installed_wheels/0457d0c3fb526f3f246a04ebe5fa67dfa4f0877fe617e106f23f3b083f7b1ab1/pex-2.1.73-py2.py3-none-any.whl/pex/bin/pex.py", line 724, in main
    do_main(
  File "/home/joshuacannon/.cache/pants/named_caches/pex_root/installed_wheels/0457d0c3fb526f3f246a04ebe5fa67dfa4f0877fe617e106f23f3b083f7b1ab1/pex-2.1.73-py2.py3-none-any.whl/pex/bin/pex.py", line 745, in do_main
    pex_builder = build_pex(
  File "/home/joshuacannon/.cache/pants/named_caches/pex_root/installed_wheels/0457d0c3fb526f3f246a04ebe5fa67dfa4f0877fe617e106f23f3b083f7b1ab1/pex-2.1.73-py2.py3-none-any.whl/pex/bin/pex.py", line 594, in build_pex
    resolve_from_lock(
  File "/home/joshuacannon/.cache/pants/named_caches/pex_root/installed_wheels/0457d0c3fb526f3f246a04ebe5fa67dfa4f0877fe617e106f23f3b083f7b1ab1/pex-2.1.73-py2.py3-none-any.whl/pex/resolve/lock_resolver.py", line 198, in resolve_from_lock
    pool.map(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/joshuacannon/.cache/pants/named_caches/pex_root/installed_wheels/0457d0c3fb526f3f246a04ebe5fa67dfa4f0877fe617e106f23f3b083f7b1ab1/pex-2.1.73-py2.py3-none-any.whl/pex/result.py", line 101, in catch
    return func(*args, **kwargs)
  File "/home/joshuacannon/.cache/pants/named_caches/pex_root/installed_wheels/0457d0c3fb526f3f246a04ebe5fa67dfa4f0877fe617e106f23f3b083f7b1ab1/pex-2.1.73-py2.py3-none-any.whl/pex/resolve/lock_resolver.py", line 46, in store_downloadable_artifact
    return self.store(artifact=downloadable_artifact.artifact)
  File "/home/joshuacannon/.cache/pants/named_caches/pex_root/installed_wheels/0457d0c3fb526f3f246a04ebe5fa67dfa4f0877fe617e106f23f3b083f7b1ab1/pex-2.1.73-py2.py3-none-any.whl/pex/resolve/lockfile/download_manager.py", line 40, in store
    with atomic_directory(download_dir, exclusive=True) as atomic_dir:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/joshuacannon/.cache/pants/named_caches/pex_root/installed_wheels/0457d0c3fb526f3f246a04ebe5fa67dfa4f0877fe617e106f23f3b083f7b1ab1/pex-2.1.73-py2.py3-none-any.whl/pex/common.py", line 470, in atomic_directory
    fcntl.lockf(lock_fd, fcntl.LOCK_EX)  # A blocking write lock.
OSError: [Errno 35] Resource deadlock avoided
```

**Comment by jsirois** [comment]
The atomic directory code has been in its current form since #1126 - ~16 months of use in that form. Never a report of OSError 35 EDEADLCK since inception; that suggests looking at what's new. That is using threading in Pex. The `--lock` resolver uses a thread pool as a poor-man's way to get parallel downloads that works in Python 2.7 too and doesn't require vendoring more libraries. So; I'm surely POSIX dumb here and if I weren't there would be a well known gotcha combining threads and file locks of this style. I'm guessing the quick fix is to switch to a multipprocess pool instead of a thread pool. The overhead of that switch is likely in the noise. That though punts the why. It would be good to understand why and exactly the mechanism here.

**Comment by jsirois** [comment]
Yeah - you'll need to dig.

**Comment by thejcannon** [comment]
Some light internet reading shows this might happen if you `fork()` and spawn threads together. 

Here's a rough sketch

1. spawn one or more threads in your program
2. have at least one of those threads make try and acquire a file lock
3. have your main thread or another thread use os.fork() to run some 
python code in a child process.
4. If the fork happened while one of your threads was within the 
behind-the-lock critical section (or anywhere else where 
the lock is acquired), your child process will deadlock as soon as 
it tries to log anything.  It inherited a held lock.

so @jsirois if I try really hard to think about this (not easy for me) I'm wondering if something is spawning a process inside the download threads. What do you think? Might be this? Something else perhaps?

**Comment by thejcannon** [comment]
Ahh I suspect the `fork` here is happening via Pants, not PEX. So it's extremely plausible this is what is happening.

**Comment by jsirois** [comment]
@thejcannon does the relevant lock file have more than one artifact with the same fingerprint? That and only that would lead two two threads in the same Pex process trying to lock the same file lock. So, for example, if you had an artifact, say foo-bar-1.0 available via 2 different URLs but with the same fingerprint (hash + algorithm).

**Comment by jsirois** [comment]
Whether or not this is your case, it seems it is a valid case when there is >1 --index or --find-links. As such, that does represent a gedanken-bug at the least. I'll file.

**Comment by thejcannon** [comment]
I don't think our case involves any of those symptoms. In this case, the PEX thread doesn't need to fork, it's parent process can and it would exhibit the same behavior.
[deadlock.zip](https://github.com/pantsbuild/pex/files/8357965/deadlock.zip)

**Comment by jsirois** [comment]
I don't buy the bit about forking in a parent process. The only relevant thing about forking and locks in general (mutexes or file locks / open fds) is when the parent is involved in the lock. Pants has 0 involvement with these locks. Further, repeating myself, but the Pex process doesn't fork either (except for VCS requirements). I'm almost positive forks are red herrings here.

An experiment is good though. A problem with yours is the lock file having potentially colliding names in the same process, that can't happen in the Pex case mod the issue I noted above. So you'd want to not use a small random number that could repeat.

I don't have time to run my own experiment this morning, but after re-reading the fcntl man page and the relevant Linux fs lock code, I'm pretty sure this is Linux being pedantically incorrect. One process locks a and tries to lock b, another process does the opposite and the kernel thinks this is a deadlock when it's not, all these file locks are independent.

**Comment by thejcannon** [comment]
> One process locks a and tries to lock b, another process does the opposite

I tried this and I get a hang. So likely not what we're seeing: [johnidea.zip](https://github.com/pantsbuild/pex/files/8365122/johnidea.zip)

At least not directly, this is a deterministic(ish) reproducible demo: [strictrepo.zip](https://github.com/pantsbuild/pex/files/8365554/strictrepo.zip)

**Comment by Eric-Arellano** [comment]
@thejcannon should this be closed?

**Comment by thejcannon** [comment]
I'll leave that to @jsirois, to make sure we understood the problem and the fix well enough

**Comment by jsirois** [comment]
@thejcannon it doesn't hang if you 1. `s/Pool/ThreadPool/` and 2. `os.makedirs("/tmp/locks")`. I'll investigate this more this weekend. It seems like we're still clueless what's going on t=and the current fix just papers this over. I appreciate you moving forward with the hack, but I want to understand this.

**Comment by jsirois** [comment]
And, adding an unlock to your strict causes the issue to go away. That, at least, is a clue:
```
$ diff -u strictrepo.py strictrepo_edited.py 
--- strictrepo.py	2022-03-28 12:08:10.000000000 -0700
+++ strictrepo_edited.py	2022-03-31 19:19:44.705426890 -0700
@@ -31,6 +31,7 @@
             )
             fcntl.lockf(lock_fd, fcntl.LOCK_EX)  # A blocking write lock.
             time.sleep(20)
+            fcntl.lockf(lock_fd, fcntl.LOCK_UN)
 
     else:
         if not os.path.exists("/tmp/locks"):
$ python strictrepo.py 
Traceback (most recent call last):
  File "/home/jsirois/Downloads/strictrepo.py", line 32, in <module>
    fcntl.lockf(lock_fd, fcntl.LOCK_EX)  # A blocking write lock.
OSError: [Errno 35] Resource deadlock avoided
Traceback (most recent call last):
  File "/home/jsirois/Downloads/strictrepo.py", line 40, in <module>
    worker_pool.map(high_worker_threads, [("A", "B"), ("B", "A")])
  File "/home/jsirois/.pyenv/versions/3.10.2/lib/python3.10/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/jsirois/.pyenv/versions/3.10.2/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/jsirois/.pyenv/versions/3.10.2/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/jsirois/.pyenv/versions/3.10.2/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/jsirois/Downloads/strictrepo.py", line 18, in high_worker_threads
    subprocess.run(
  File "/home/jsirois/.pyenv/versions/3.10.2/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/jsirois/.pyenv/versions/3.10.2/bin/python', '/home/jsirois/Downloads/strictrepo.py', 'B', 'A']' returned non-zero exit status 1.
$ python strictrepo_edited.py
$
```

**Comment by jsirois** [comment]
Yeah, so here is a rig that's faithful (needs to be run in a pex clone with Joshua's fix reverted):
```python
import functools
import os.path
import subprocess
import sys
import threading
from argparse import ArgumentParser

from pex.common import atomic_directory, temporary_dir
from multiprocessing.pool import ThreadPool


def identity():
    return "pid={pid}, tid={tid}".format(pid=os.getpid(), tid=threading.current_thread().ident)


def log(message):
    print("[{identity}] {msg}".format(identity=identity(), msg=message), file=sys.stderr)


def atomically(directory, item):
    with atomic_directory(
        os.path.join(directory, "item{}".format(item)), exclusive=True
    ) as atomic_dir:
        if atomic_dir.is_finalized():
            with open(os.path.join(atomic_dir.target_dir, "data")) as fp:
                ident = fp.readline()
                log(
                    "Target directory {target_dir} was finalized by: {finalizer}".format(
                        target_dir=atomic_dir.target_dir, finalizer=identity()
                    )
                )
        else:
            log("Finalizing {target_dir}".format(target_dir=atomic_dir.target_dir))
            with open(os.path.join(atomic_dir.work_dir, "data"), "w") as fp:
                ident = identity()
                fp.write(ident)
                fp.write(os.linesep)

    return item, ident


def process(directory, threads=10, items=0):
    with ThreadPool(processes=threads) as pool:
        items = list(range(items or threads))
        for item, ident in pool.map(functools.partial(atomically, directory), items):
            log("Item {item} processed by {ident}".format(item=item, ident=ident))


if __name__ == "__main__":
    parser = ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--processes", type=int, default=2)
    mode.add_argument("--dir", type=str, default=None)
    parser.add_argument("--threads", type=int, default=10)
    parser.add_argument("--items", type=int, default=0)
    parser.add_argument("--no-cleanup", dest="cleanup", default=True, action="store_false")

    options = parser.parse_args()
    if options.dir:
        log("Processing...")
        process(
            directory=options.dir, threads=options.threads, items=options.items or options.threads
        )
    else:
        with temporary_dir(cleanup=options.cleanup) as directory:
            log("Spawning contending processes against {} ...".format(directory))
            processes = []
            for _ in range(options.processes):
                processes.append(
                    subprocess.Popen(
                        args=[
                            sys.executable,
                            __file__,
                            "--dir",
                            directory,
                            "--threads",
                            str(options.threads),
                            "--items",
                            str(options.items or options.threads),
                        ],
                    )
                )
            status = 0
            for process in processes:
                status += process.wait()
                log(
                    "pid {pid} returned {returncode}".format(
                        pid=process.pid, returncode=process.returncode
                    )
                )
            sys.exit(status)

```

This never fails (1300+ iterations before stopping):
```
clear && COUNT=0 && while python rig.py --processes 2 --threads 1 --items 3; do echo -e "\nAttempt $((COUNT+=1))\n\n"; done
```

This eventually fails:
```
...
Attempt 9


[pid=116170, tid=140367201425216] Spawning contending processes against /tmp/tmp1j33kpy0 ...
[pid=116186, tid=140438900021056] Processing...
[pid=116187, tid=140626719569728] Processing...
[pid=116186, tid=140438890067520] >>> Locking /tmp/tmp1j33kpy0/item0...
[pid=116186, tid=140438890067520]     LOCKED /tmp/tmp1j33kpy0/item0...
[pid=116186, tid=140438890067520] Finalizing /tmp/tmp1j33kpy0/item0
[pid=116187, tid=140626701223488] >>> Locking /tmp/tmp1j33kpy0/item1...
[pid=116187, tid=140626709616192] >>> Locking /tmp/tmp1j33kpy0/item0...
[pid=116186, tid=140438890067520] >>> Unlocking /tmp/tmp1j33kpy0/item0...
[pid=116187, tid=140626701223488]     LOCKED /tmp/tmp1j33kpy0/item1...
[pid=116186, tid=140438881674816] >>> Locking /tmp/tmp1j33kpy0/item1...
[pid=116187, tid=140626701223488] Finalizing /tmp/tmp1j33kpy0/item1
[pid=116187, tid=140626709616192]     LOCKED /tmp/tmp1j33kpy0/item0...
[pid=116186, tid=140438890067520] >>> Locking /tmp/tmp1j33kpy0/item2...
[pid=116186, tid=140438890067520]     LOCKED /tmp/tmp1j33kpy0/item2...
[pid=116186, tid=140438890067520] Finalizing /tmp/tmp1j33kpy0/item2
[pid=116187, tid=140626709616192] Target directory /tmp/tmp1j33kpy0/item0 was finalized by: pid=116187, tid=140626709616192
[pid=116186, tid=140438890067520] >>> Unlocking /tmp/tmp1j33kpy0/item2...
[pid=116187, tid=140626709616192] >>> Unlocking /tmp/tmp1j33kpy0/item0...
[pid=116187, tid=140626701223488] >>> Unlocking /tmp/tmp1j33kpy0/item1...
[pid=116187, tid=140626709616192] Target directory /tmp/tmp1j33kpy0/item2 was finalized by: pid=116187, tid=140626709616192
[pid=116186, tid=140438881674816]     LOCKED /tmp/tmp1j33kpy0/item1...
[pid=116186, tid=140438881674816] Target directory /tmp/tmp1j33kpy0/item1 was finalized by: pid=116186, tid=140438881674816
[pid=116186, tid=140438881674816] >>> Unlocking /tmp/tmp1j33kpy0/item1...
[pid=116187, tid=140626719569728] Item 0 processed by pid=116186, tid=140438890067520

[pid=116187, tid=140626719569728] Item 1 processed by pid=116187, tid=140626701223488
[pid=116187, tid=140626719569728] Item 2 processed by pid=116186, tid=140438890067520

[pid=116186, tid=140438900021056] Item 0 processed by pid=116186, tid=140438890067520
[pid=116186, tid=140438900021056] Item 1 processed by pid=116187, tid=140626701223488

[pid=116186, tid=140438900021056] Item 2 processed by pid=116186, tid=140438890067520
[pid=116170, tid=140367201425216] pid 116186 returned 0
[pid=116170, tid=140367201425216] pid 116187 returned 0

Attempt 10


[pid=116198, tid=140280974968640] Spawning contending processes against /tmp/tmptcoljfye ...
[pid=116215, tid=139880099129152] Processing...
[pid=116214, tid=139933276030784] Processing...
[pid=116214, tid=139933266077248] >>> Locking /tmp/tmptcoljfye/item0...
[pid=116214, tid=139933266077248]     LOCKED /tmp/tmptcoljfye/item0...
[pid=116215, tid=139880080782912] >>> Locking /tmp/tmptcoljfye/item1...
[pid=116215, tid=139880089175616] >>> Locking /tmp/tmptcoljfye/item0...
[pid=116214, tid=139933266077248] Finalizing /tmp/tmptcoljfye/item0
[pid=116215, tid=139880080782912]     LOCKED /tmp/tmptcoljfye/item1...
[pid=116215, tid=139880080782912] Finalizing /tmp/tmptcoljfye/item1
[pid=116214, tid=139933188617792] >>> Locking /tmp/tmptcoljfye/item1...
[pid=116214, tid=139933188617792]     FAILED to lock /tmp/tmptcoljfye/item1: [Errno 35] Resource deadlock avoided
[pid=116215, tid=139880080782912] >>> Unlocking /tmp/tmptcoljfye/item1...
[pid=116215, tid=139880080782912] >>> Locking /tmp/tmptcoljfye/item2...
[pid=116215, tid=139880080782912]     LOCKED /tmp/tmptcoljfye/item2...
[pid=116214, tid=139933188617792] >>> Locking /tmp/tmptcoljfye/item2...
[pid=116215, tid=139880080782912] Finalizing /tmp/tmptcoljfye/item2
[pid=116214, tid=139933188617792]     FAILED to lock /tmp/tmptcoljfye/item2: [Errno 35] Resource deadlock avoided
[pid=116215, tid=139880080782912] >>> Unlocking /tmp/tmptcoljfye/item2...
[pid=116214, tid=139933266077248] >>> Unlocking /tmp/tmptcoljfye/item0...
[pid=116215, tid=139880089175616]     LOCKED /tmp/tmptcoljfye/item0...
[pid=116215, tid=139880089175616] Target directory /tmp/tmptcoljfye/item0 was finalized by: pid=116215, tid=139880089175616
[pid=116215, tid=139880089175616] >>> Unlocking /tmp/tmptcoljfye/item0...
[pid=116215, tid=139880099129152] Item 0 processed by pid=116214, tid=139933266077248

[pid=116215, tid=139880099129152] Item 1 processed by pid=116215, tid=139880080782912
[pid=116215, tid=139880099129152] Item 2 processed by pid=116215, tid=139880080782912
Traceback (most recent call last):
  File "/home/jsirois/dev/pantsbuild/jsirois-pex/rig.py", line 61, in <module>
    process(
  File "/home/jsirois/dev/pantsbuild/jsirois-pex/rig.py", line 45, in process
    for item, ident in pool.map(functools.partial(atomically, directory), items):
  File "/home/jsirois/.pyenv/versions/3.10.2/lib/python3.10/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/jsirois/.pyenv/versions/3.10.2/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/jsirois/.pyenv/versions/3.10.2/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/jsirois/.pyenv/versions/3.10.2/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/jsirois/dev/pantsbuild/jsirois-pex/rig.py", line 21, in atomically
    with atomic_directory(
  File "/home/jsirois/.pyenv/versions/3.10.2/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/jsirois/dev/pantsbuild/jsirois-pex/pex/common.py", line 485, in atomic_directory
    raise e
  File "/home/jsirois/dev/pantsbuild/jsirois-pex/pex/common.py", line 481, in atomic_directory
    fcntl.lockf(lock_fd, fcntl.LOCK_EX)  # A blocking write lock.
OSError: [Errno 35] Resource deadlock avoided
[pid=116198, tid=140280974968640] pid 116214 returned 1
[pid=116198, tid=140280974968640] pid 116215 returned 0
```

Still ruminating on this. But at least the repro is now faithful to the actual code used in production and the repro is provably #thread based - must be >1.

**Comment by jsirois** [comment]
Ok, and further bolstering weirdness with threads, `s/lockf/flock/` gets things working. Linux doesn't even attempt deadlock detection for BSD-style locks. As far as fcntl locks (which lockf is under the covers) the issue with threads are discussed here: https://lore.kernel.org/lkml/482A3FA0050D21419C269D13989C61130435E200@lavender-fe.eng.netapp.com/T/

The main sticky wicket is NFS afaict, which fcntl can sometimes work on (NFSv4 + some kernels) and flock never works on.

**Comment by jsirois** [comment]
As an aside, interesting reading along the way from some big hitters:
+ http://0pointer.de/blog/projects/locking.html
+ https://apenwarr.ca/log/20101213
+ https://www.samba.org/samba/news/articles/low_point/tale_two_stds_os2.html

**Comment by jsirois** [comment]
Ok, wrapping up. It turns out the guess [here](https://github.com/pantsbuild/pex/issues/1693#issuecomment-1079982936) was right:
> I don't have time to run my own experiment this morning, but after re-reading the fcntl man page and the relevant Linux fs lock code, I'm pretty sure this is Linux being pedantically incorrect. One process locks a and tries to lock b, another process does the opposite and the kernel thinks this is a deadlock when it's not, all these file locks are independent.

Looking at the repro logs above, we see:
```
[pid=116215, tid=139880099129152] Processing...
[pid=116214, tid=139933276030784] Processing...
[pid=116214, tid=139933266077248] >>> Locking /tmp/tmptcoljfye/item0...
[pid=116214, tid=139933266077248]     LOCKED /tmp/tmptcoljfye/item0...
[pid=116215, tid=139880080782912] >>> Locking /tmp/tmptcoljfye/item1...
[pid=116215, tid=139880089175616] >>> Locking /tmp/tmptcoljfye/item0...
[pid=116214, tid=139933266077248] Finalizing /tmp/tmptcoljfye/item0
[pid=116215, tid=139880080782912]     LOCKED /tmp/tmptcoljfye/item1...
[pid=116215, tid=139880080782912] Finalizing /tmp/tmptcoljfye/item1
[pid=116214, tid=139933188617792] >>> Locking /tmp/tmptcoljfye/item1...
[pid=116214, tid=139933188617792]     FAILED to lock /tmp/tmptcoljfye/item1: [Errno 35] Resource deadlock avoided
```

Find-replace long numbers to simpler symbols:
```
[pid=A, tid=X] >>> Locking item0...
[pid=A, tid=X]     LOCKED item0...
[pid=B, tid=Y] >>> Locking item1...
[pid=B, tid=Z] >>> Locking item0...
[pid=A, tid=X] Finalizing item0
[pid=B, tid=Y]     LOCKED item1...
[pid=B, tid=Y] Finalizing item1
[pid=A, tid=W] >>> Locking item1...
[pid=A, tid=W]     FAILED to lock item1: [Errno 35] Resource deadlock avoided
```

Go thread-blind and:
```
[pid=A] >>> Locking item0...
[pid=A]     LOCKED item0...
[pid=B] >>> Locking item1...
[pid=B] >>> Locking item0...
[pid=A] Finalizing item0
[pid=B]     LOCKED item1...
[pid=B] Finalizing item1
[pid=A] >>> Locking item1...
[pid=A]     FAILED to lock item1: [Errno 35] Resource deadlock avoided
```

That sequence is:
1. A locks 0
2. B locks 1
3. B tries to lock 0 (which A holds in step 1)
4. A tries to lock 1 (which B holds in step 2)

So, ignoring threads, the kernel sees a deadlock.

Not ignoring threads we see the sequence really is:
1. (A, X) locks 0
2. (B, Y) locks 1
3. (B, Z) tries to lock 0 (which A, X holds in step 1)
4. (A, W) tries to lock 1 (which B, Y holds in step 2)

I.E.: There is no deadlock, there are four separate players - not two.

Right now the workaround is to retry when the kernel signals a deadlock. Without reading kernel code its not clear if both deadlocked processes get EDEADLCK or just one. If both get it we could infinite loop. I'm pretty sure just the "last" contender gets EDEADLCK and so we don't happen to infinite loop, but that could be wrong and we're just lucky so far. Either way, depending on undocumented behavior seems like a bad idea.

There are two broad classes of alternatives fwict:
1. Switch to a lock style not subject to deadlock / deadlock detection (`s/fcntl.lockf/fcntl.flock/`)
2. Use process parallelism instead of thread parallelism (`execute_parallel` infra).

The only disadvantage of 1 seems to be missing out on Pex working when PEX_ROOT is on an NFSv4 protocol network share under kernels that handle NFS locking correctly. It's not clear Pex has clients in the wild exercising this, but there certainly may be. We know indirect Pex users via Pants can't be in this boat since Pants uses LMDB/MMAP which is ~known to not work on NFS generally, but that class of users is a subset of Pex users.

The disadvantage of 2 is more complex code to write up an URL fetching main to shell out to as well as dealing with the non-uniformity of VCS vs URL processes. To date, `execute_parallel` only deals with homogenous processes.

Since the issue here is limited to the lock resolver which is a feature introduced for Pants and very likely only used by Pants so far, it seems like the most robust path is to use `fcntl.flock` locking in that code path only. Since `fcntl.lockf` and `fcntl.flock` have the same API (use the same constants even), parametrization of the locking API used can be clean and uncomplicated.
