### ISSUE TITLE
The interpreter we run Pex with affects the resolve

### ISSUE THREAD

**Issue by benjyw** [pantsbuild/pex#1734]
```
python3.6 -m pex.cli lock create --style=universal --interpreter-constraint 'CPython<3.9,>=3.8' 'aioconsole' 
```

Fails with `ERROR: Package 'aioconsole' requires a different Python: 3.6.6 not in '>=3.7'` . 

Running with python3.7 succeeds.

Removing `--style=universal` succeeds.

Note: `aioconsole` only publishes an sdist.

**Comment by benjyw** [comment]
Putting debugging/learning notes here, even though they are likely obvious to @jsirois, or plain wrong.

**Comment by benjyw** [comment]
So this `aioconsole` is sdist-only, and we run its `setup.py` in the python 3.6 we use to run pex itself, rather than in an interpreter compatible with the explicit `--interpreter-constraint`.

**Comment by jsirois** [comment]
Presumably, with verbosity turned up, it will be revealed this happens in the resolve post-processing phase where sdists are built into wheels to get `Requires-*` metadata for the lock. If so, this was just an oversight and, when an IC is present in a universal lock Pex should pick (demand) a local interpreter that fits the IC to do the post-processing with.

**Comment by benjyw** [comment]
This is the full output:

```
$ python3.6 -m pex.cli lock create -vvvvvvvvv   --style=universal --interpreter-constraint 'CPython<3.9,>=3.8' 'aiomonitor<0.5.0,>=0.4.5' 
pex: Resolving for:
pex: Spawning a maximum of 8 parallel jobs to process:
  /Users/benjyw/src/pex/venv/bin/python3.6
pex: Hashing pex: 70.6ms
pex: Isolating pex: 0.1ms
pex: Calculating compatible python versions for ('<3.9,>=3.8',): 11.9ms
    Running command python setup.py egg_info
    running egg_info
    creating /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-pip-egg-info-4jkpcfae/aioconsole.egg-info
    writing /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-pip-egg-info-4jkpcfae/aioconsole.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-pip-egg-info-4jkpcfae/aioconsole.egg-info/dependency_links.txt
    writing entry points to /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-pip-egg-info-4jkpcfae/aioconsole.egg-info/entry_points.txt
    writing top-level names to /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-pip-egg-info-4jkpcfae/aioconsole.egg-info/top_level.txt
    writing manifest file '/private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-pip-egg-info-4jkpcfae/aioconsole.egg-info/SOURCES.txt'
    reading manifest file '/private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-pip-egg-info-4jkpcfae/aioconsole.egg-info/SOURCES.txt'
    writing manifest file '/private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-pip-egg-info-4jkpcfae/aioconsole.egg-info/SOURCES.txt'
pex: Resolving for:
pex: Resolving for:/pex/venv/bin/python3.6 :: Building 1 source distribution to gather metadata for lock.
  /Users/benjyw/src/pex/venv/bin/python3.6 :: Building 1 source distribution to gather metadata for lock. :: Building distributions for:
  BuildRequest(target=LocalInterpreter(id='Users.benjyw.src.pex.venv.bin.python3.6', platform=Platform(platform='macosx_10_16_x86_64', impl='cp', version='3.6.6', version_info=(3, 6, 6), abi='cp36m'), marker_environment=MarkerEnvironment(implementation_name='cpython', implementation_version='3.6.6', os_name='posix', platform_machine='x86_64', platform_python_implementation='CPython', platform_release='21.4.0', platform_system='Darwin', platform_version='Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64', python_full_version='3.6.6', python_version='3.6', sys_platform='darwin'), interpreter=PythonInterpreter('/Users/benjyw/src/pex/venv/bin/python3.6', PythonIdentity('/Users/benjyw/src/pex/venv/bin/python3.6', 'cp36', 'cp36m', 'macosx_10_16_x86_64', (3, 6, 6)))), source_path='/private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/tmpwrrepd09/Users.benjyw.src.pex.venv.bin.python3.6/aioconsole-0.4.1.tar.gz', fingerprint='0c0acb66b4e72d6606cpex: Building /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/tmpwrrepd09/Users.benjyw.src.pex.venv.bin.python3.6/aioconsole-0.4.1.tar.gz to /Users/benjyw/.pex/built_wheels/sdists/aioconsole-0.4.1.tar.gz/0c0acb66b4e72d6606c9fa14ac9eb001a222c37c885b8fbdf65f41824cfa855f/cp36-cp36m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
pex: Spawning a maximum of 8 parallel jobs to process:
  BuildRequest(target=LocalInterpreter(id='Users.benjyw.src.pex.venv.bin.python3.6', platform=Platform(platform='macosx_10_16_x86_64', impl='cp', version='3.6.6', version_info=(3, 6, 6), abi='cp36m'), marker_environment=MarkerEnvironment(implementation_name='cpython', implementation_version='3.6.6', os_name='posix', platform_machine='x86_64', platform_python_implementation='CPython', platform_release='21.4.0', platform_system='Darwin', platform_version='Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64', python_full_version='3.6.6', python_version='3.6', sys_platform='darwin'), interpreter=PythonInterpreter('/Users/benjyw/src/pex/venv/bin/python3.6', PythonIdentity('/Users/benjyw/src/pex/venv/bin/python3.6', 'cp36', 'cp36m', 'macosx_10_16_x86_64', (3, 6, 6)))), source_path='/private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/tmpwrrepd09/Users.benjyw.src.pex.venv.bin.python3.6/aioconsole-0.4.1.tar.gz', fingerprint='0c0acb66b4e72d6606c9fa14ac9eb001a222c37c885b8fbdf65f41824cfa855f')
Created temporary directory: /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-ephem-wheel-cache-e8uljkdl
Created temporary directory: /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-req-tracker-nd10d19v
Initialized build tracking at /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-req-tracker-nd10d19v
Created build tracker: /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-req-tracker-nd10d19v
Entered build tracker: /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-req-tracker-nd10d19v
Created temporary directory: /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-wheel-33xx7m3h
Processing /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/tmpwrrepd09/Users.benjyw.src.pex.venv.bin.python3.6/aioconsole-0.4.1.tar.gz
  Created temporary directory: /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-req-build-n_2udc6a
  Added file:///private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/tmpwrrepd09/Users.benjyw.src.pex.venv.bin.python3.6/aioconsole-0.4.1.tar.gz to build tracker '/private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-req-tracker-nd10d19v'
    Running setup.py (path:/private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-req-build-n_2udc6a/setup.py) egg_info for package from file:///private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/tmpwrrepd09/Users.benjyw.src.pex.venv.bin.python3.6/aioconsole-0.4.1.tar.gz
    Created temporary directory: /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-pip-egg-info-niz5a_2k
    Running command python setup.py egg_info
    running egg_info
    creating /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-pip-egg-info-niz5a_2k/aioconsole.egg-info
    writing /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-pip-egg-info-niz5a_2k/aioconsole.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-pip-egg-info-niz5a_2k/aioconsole.egg-info/dependency_links.txt
    writing entry points to /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-pip-egg-info-niz5a_2k/aioconsole.egg-info/entry_points.txt
    writing top-level names to /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-pip-egg-info-niz5a_2k/aioconsole.egg-info/top_level.txt
    writing manifest file '/private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-pip-egg-info-niz5a_2k/aioconsole.egg-info/SOURCES.txt'
    reading manifest file '/private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-pip-egg-info-niz5a_2k/aioconsole.egg-info/SOURCES.txt'
    writing manifest file '/private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-pip-egg-info-niz5a_2k/aioconsole.egg-info/SOURCES.txt'
  Source in /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-req-build-n_2udc6a has version 0.4.1, which satisfies requirement aioconsole==0.4.1 from file:///private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/tmpwrrepd09/Users.benjyw.src.pex.venv.bin.python3.6/aioconsole-0.4.1.tar.gz
  Removed aioconsole==0.4.1 from file:///private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/tmpwrrepd09/Users.benjyw.src.pex.venv.bin.python3.6/aioconsole-0.4.1.tar.gz from build tracker '/private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-req-tracker-nd10d19v'
ERROR: Package 'aioconsole' requires a different Python: 3.6.6 not in '>=3.7'
Exception information:
Traceback (most recent call last):
  File "/Users/benjyw/.pex/venvs/s/a1a3f642/venv/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/Users/benjyw/.pex/venvs/s/a1a3f642/venv/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/Users/benjyw/.pex/venvs/s/a1a3f642/venv/lib/python3.6/site-packages/pip/_internal/commands/wheel.py", line 163, in run
    reqs, check_supported_wheels=True
  File "/Users/benjyw/.pex/venvs/s/a1a3f642/venv/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 180, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/Users/benjyw/.pex/venvs/s/a1a3f642/venv/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 390, in _resolve_one
    ignore_requires_python=self.ignore_requires_python,
  File "/Users/benjyw/.pex/venvs/s/a1a3f642/venv/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 101, in _check_dist_requires_python
    dist.project_name, version, requires_python,
pip._internal.exceptions.UnsupportedPythonVersion: Package 'aioconsole' requires a different Python: 3.6.6 not in '>=3.7'
Removed build tracker: '/private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/pip-req-tracker-nd10d19v'
pid 91261 -> /Users/benjyw/.pex/venvs/a79216b84ff96b998dbc88a7f69324653f7b73b2/ca86241134ff9c9261cc49ffd61bf96e7844a4a8/pex --disable-pip-version-check --no-python-version-warning --exists-action a --use-deprecated legacy-resolver --isolated -vvv --cache-dir /Users/benjyw/.pex wheel --no-deps --wheel-dir /Users/benjyw/.pex/built_wheels/sdists/aioconsole-0.4.1.tar.gz/0c0acb66b4e72d6606c9fa14ac9eb001a222c37c885b8fbdf65f41824cfa855f/cp36-cp36m.09e668179bdd49b29524ebaf4a0cbe8c /private/var/folders/q4/pv4jnnm944b_ywr3tnp_b1300000gn/T/tmpwrrepd09/Users.benjyw.src.pex.venv.bin.python3.6/aioconsole-0.4.1.tar.gz --index-url https://pypi.org/simple --retries 5 --timeout 15 exited with 1 and STDERR:
None
```

**Comment by benjyw** [comment]
So yeah, this is happening when processing the BuildRequest.

**Comment by benjyw** [comment]
Thanks for fixing @jsirois ! It would have taken me a while to get that done.
