### ISSUE TITLE
Exception with sudo su -, but not with sudo -s

### ISSUE THREAD

**Issue by amiorin** [pantsbuild/pex#176]
I use pex to deploy python code starting services like elasticsearch.
The script packaged with ``pex`` is using ``python-consul`` to fetch ``elasticsearch`` configuration from ``consul``. ``python-consul`` is using ``requests`` that uses ``chardet`` module.
https://github.com/kennethreitz/requests/blob/master/requests/packages/chardet/__init__.py#L27

This exception happens with ``sudo su -``, but not with ``sudo -s``.
Ubuntu trusty inside docker.
Any idea why?

```
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 317, in execute
  File ".bootstrap/_pex/pex.py", line 250, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 282, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 360, in _execute
  File ".bootstrap/_pex/pex.py", line 418, in execute_entry
  File ".bootstrap/_pex/pex.py", line 436, in execute_pkg_resources
  File "/root/.pex/install/run_elasticsearch-0.0.4-py2-none-any.whl.f28929d3fe9d0c810bee456cf6dc278d6f079680/run_elasticsearch-0.0.4-py2-none-any.whl/main.py", line 32, in cli
  File "/root/.pex/install/run_elasticsearch-0.0.4-py2-none-any.whl.f28929d3fe9d0c810bee456cf6dc278d6f079680/run_elasticsearch-0.0.4-py2-none-any.whl/main.py", line 39, in create_script
  File "/root/.pex/install/run_elasticsearch-0.0.4-py2-none-any.whl.f28929d3fe9d0c810bee456cf6dc278d6f079680/run_elasticsearch-0.0.4-py2-none-any.whl/main.py", line 53, in render_script
  File "/root/.pex/install/run_elasticsearch-0.0.4-py2-none-any.whl.f28929d3fe9d0c810bee456cf6dc278d6f079680/run_elasticsearch-0.0.4-py2-none-any.whl/main.py", line 44, in heap
  File "/root/.pex/install/run_elasticsearch-0.0.4-py2-none-any.whl.f28929d3fe9d0c810bee456cf6dc278d6f079680/run_elasticsearch-0.0.4-py2-none-any.whl/run_utils/__init__.py", line 41, in get_key
  File "/root/.pex/install/python_consul-0.4.7-py2-none-any.whl.951c15d94bb2078b5cfee34b0a53996fb0255b9d/python_consul-0.4.7-py2-none-any.whl/consul/base.py", line 391, in get
  File "/root/.pex/install/python_consul-0.4.7-py2-none-any.whl.951c15d94bb2078b5cfee34b0a53996fb0255b9d/python_consul-0.4.7-py2-none-any.whl/consul/std.py", line 34, in get
  File "/root/.pex/install/python_consul-0.4.7-py2-none-any.whl.951c15d94bb2078b5cfee34b0a53996fb0255b9d/python_consul-0.4.7-py2-none-any.whl/consul/std.py", line 23, in response
  File "/root/.pex/install/requests-2.8.1-py2.py3-none-any.whl.1c5a361b4c60f18ed7c52565ebd718df59f2d5d4/requests-2.8.1-py2.py3-none-any.whl/requests/models.py", line 766, in text
  File "/root/.pex/install/requests-2.8.1-py2.py3-none-any.whl.1c5a361b4c60f18ed7c52565ebd718df59f2d5d4/requests-2.8.1-py2.py3-none-any.whl/requests/models.py", line 640, in apparent_encoding
  File "/root/.pex/install/requests-2.8.1-py2.py3-none-any.whl.1c5a361b4c60f18ed7c52565ebd718df59f2d5d4/requests-2.8.1-py2.py3-none-any.whl/requests/packages/chardet/__init__.py", line 27, in detect
ImportError: cannot import name universaldetector
```

**Comment by amiorin** [comment]
It looks, it's something inside the ``home`` that breaks things.
I've another pex file to start ``consul`` ``run-consul``, that is started before ``run-elasticsearch``

**Comment by amiorin** [comment]
I don't know if it is bug. The workaround was to move at the end of script the change of user from ``root`` (the configuration management user) to ``elasticsearch`` (the java process user)

```python
    pw = getpwnam(user)
    setgid(pw.pw_gid)
    setuid(pw.pw_uid)
    stdout.flush()
    stderr.flush()
    execvpe(cmd, argv, {})
```

**Comment by kwlzn** [comment]
@amiorin this is likely the result of tilde expansion behavior on your system. pex caches to '~/.pex' (aka the "pex root") by default. in your case, it looks like '~/.pex' is getting expanded as the root users path (/root/.pex) which is likely unreadable after the privilege drop. something between the two forms of sudo is affecting this expansion.

if you can't use a sudo method that affords sane tilde expansion behavior, you can always explicitly control this using the PEX_ROOT env var, e.g.

  `$ PEX_ROOT=/some/readable/path/.pex pex ...`

HTH

**Comment by amiorin** [comment]
Thx, I'll use the PEX_ROOT=/tmp/.pex
You are right, /root/.pex is not readable.
