### ISSUE TITLE
pex --lock ... --no-pypi --index https://aws:$CODEARTIFACT_AUTH_TOKEN@ ... fails to handle `Bearer` auth scheme

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1803]
Given an AWS CodeArtifact repo, lock creation and use goes like so:

Create OK:
```
$ pex3 lock create --no-pypi --index https://aws:$CODEARTIFACT_AUTH_TOKEN@pantsbuild-282318314562.d.codeartifact.us-west-2.amazonaws.com/pypi/pants.issues.15766/simple/ ansicolors --indent 2 -o lock.json
$ cat lock.json 
{
  "allow_builds": true,
  "allow_prereleases": false,
  "allow_wheels": true,
  "build_isolation": true,
  "constraints": [],
  "locked_resolves": [
    {
      "locked_requirements": [
        {
          "artifacts": [
            {
              "algorithm": "sha256",
              "hash": "00d2dde5a675579325902536738dd27e4fac1fd68f773fe36c21044eb559e187",
              "url": "https://pantsbuild-282318314562.d.codeartifact.us-west-2.amazonaws.com/pypi/pants.issues.15766/simple/ansicolors/1.1.8/ansicolors-1.1.8-py2.py3-none-any.whl"
            }
          ],
          "project_name": "ansicolors",
          "requires_dists": [],
          "requires_python": null,
          "version": "1.1.8"
        }
      ],
      "platform_tag": [
        "cp311",
        "cp311",
        "manylinux_2_35_x86_64"
      ]
    }
  ],
  "path_mappings": {},
  "pex_version": "2.1.92",
  "prefer_older_binary": false,
  "requirements": [
    "ansicolors"
  ],
  "requires_python": [],
  "resolver_version": "pip-legacy-resolver",
  "style": "strict",
  "transitive": true,
  "use_pep517": null
}
```

Use Fails:
```
$ rm -rf ~/.pex
$ pex --lock lock.json --no-pypi --index https://aws:$CODEARTIFACT_AUTH_TOKEN@pantsbuild-282318314562.d.codeartifact.us-west-2.amazonaws.com/pypi/pants.issues.15766/simple/ -o colors.pex
Traceback (most recent call last):
  File "/home/jsirois/.venv/pex/bin/pex", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/bin/pex.py", line 761, in main
    do_main(
    ^^^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/bin/pex.py", line 782, in do_main
    pex_builder = build_pex(
                  ^^^^^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/bin/pex.py", line 630, in build_pex
    resolve_from_lock(
    ^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/resolve/lock_resolver.py", line 369, in resolve_from_lock
    pool.map(
    ^^^^^^^^^
  File "/home/jsirois/.pyenv/versions/3.11.0b3/lib/python3.11/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/.pyenv/versions/3.11.0b3/lib/python3.11/multiprocessing/pool.py", line 771, in get
    raise self._value
    ^^^^^^^^^^^^^^^^^
  File "/home/jsirois/.pyenv/versions/3.11.0b3/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/.pyenv/versions/3.11.0b3/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/resolve/lock_resolver.py", line 207, in download_artifact
    return catch(
           ^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/result.py", line 103, in catch
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/resolve/lockfile/download_manager.py", line 152, in store
    self.save(
    ^^^^^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/resolve/lock_resolver.py", line 74, in save
    with open(path, "wb") as fp, self._url_fetcher.get_body_stream(url) as stream:
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/.pyenv/versions/3.11.0b3/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/fetcher.py", line 103, in get_body_stream
    fp = cast(BinaryIO, opener.open(request, timeout=self._timeout))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/.pyenv/versions/3.11.0b3/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/.pyenv/versions/3.11.0b3/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/.pyenv/versions/3.11.0b3/lib/python3.11/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/.pyenv/versions/3.11.0b3/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/jsirois/.pyenv/versions/3.11.0b3/lib/python3.11/urllib/request.py", line 1238, in http_error_401
    retry = self.http_error_auth_reqed('www-authenticate',
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/.pyenv/versions/3.11.0b3/lib/python3.11/urllib/request.py", line 1120, in http_error_auth_reqed
    raise ValueError("AbstractDigestAuthHandler does not support"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: AbstractDigestAuthHandler does not support the following scheme: 'Bearer'
```

**Comment by jsirois** [comment]
FWICT this is pretty hopeless to support using the stdlib.

Our vendored Pip vendors requests which handles this on the `pex3 lock create` side. The current Pex vendoring scheme does not re-write Pip imports; so we can't `from pex.third_party import pip...` code. Flipping out Pip vendoring to do import rewrites fails:
```
...
Examining /home/jsirois/dev/pantsbuild/jsirois-pex/pex/vendor/_vendored/pip/pip/_vendor/distlib/util.py...
Traceback (most recent call last):
  File "/home/jsirois/dev/pantsbuild/jsirois-pex/.tox/vendor/lib/python3.8/site-packages/baron/baron.py", line 20, in _parse
    return parser(tokens)
  File "/home/jsirois/dev/pantsbuild/jsirois-pex/.tox/vendor/lib/python3.8/site-packages/baron/grammator.py", line 836, in parse
    return parser.parse(iter(tokens))
  File "/home/jsirois/dev/pantsbuild/jsirois-pex/.tox/vendor/lib/python3.8/site-packages/baron/parser.py", line 165, in parse
    raise ParsingError(debug_output)
baron.parser.ParsingError: Error, got an unexpected token $end here:

1755         return p
1756 
1757 
1758 def normalize_name(name):
1759     """Normalize a python package name a la PEP 503"""
1760     # https://www.python.org/dev/peps/pep-0503/#normalized-names
1761     return re.sub('[-_.]+', '-', name).lower()
1762 <---- here

The token $end should be one of those: ASSERT, AT, BACKQUOTE, BINARY, BINARY_RAW_STRING, BINARY_STRING, BREAK, CLASS, COMMENT, COMPLEX, CONTINUE, DEDENT, DEF, DEL, ELLIPSIS, ENDL, ENDMARKER, EXEC, FLOAT, FLOAT_EXPONANT, FLOAT_EXPONANT_COMPLEX, FOR, FROM, GLOBAL, HEXA, IF, IMPORT, INT, INTERPOLATED_RAW_STRING, INTERPOLATED_STRING, LAMBDA, LEFT_BRACKET, LEFT_PARENTHESIS, LEFT_SQUARE_BRACKET, LONG, MINUS, NAME, NONLOCAL, NOT, OCTA, PASS, PLUS, PRINT, RAISE, RAW_STRING, RETURN, STAR, STRING, TILDE, TRY, UNICODE_RAW_STRING, UNICODE_STRING, WHILE, WITH, YIELD

Baron has failed to parse this input. If this is valid python code (and by that I mean that the python binary successfully parse this code without any syntax error) (also consider that baron does not yet parse python 3 code integrally) it would be kind if you can extract a snippet of your code that make Baron fails and open a bug here: https://github.com/PyCQA/baron/issues

Sorry for the inconvenience.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jsirois/.pyenv/versions/3.8.13/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jsirois/.pyenv/versions/3.8.13/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jsirois/dev/pantsbuild/jsirois-pex/pex/vendor/__main__.py", line 373, in <module>
    vendorize(
  File "/home/jsirois/dev/pantsbuild/jsirois-pex/pex/vendor/__main__.py", line 299, in vendorize
    modifications = import_rewriter.rewrite(python_file)
  File "/home/jsirois/dev/pantsbuild/jsirois-pex/pex/vendor/__main__.py", line 97, in rewrite
    red_baron = self._parse(python_file)
  File "/home/jsirois/dev/pantsbuild/jsirois-pex/pex/vendor/__main__.py", line 41, in _parse
    return RedBaron(fp.read())
  File "/home/jsirois/dev/pantsbuild/jsirois-pex/.tox/vendor/lib/python3.8/site-packages/redbaron/redbaron.py", line 36, in __init__
    self.node_list = base_nodes.NodeList.from_fst(baron.parse(source_code), parent=self, on_attribute="root")
  File "/home/jsirois/dev/pantsbuild/jsirois-pex/.tox/vendor/lib/python3.8/site-packages/baron/baron.py", line 66, in parse
    return _parse(tokens, print_function)
  File "/home/jsirois/dev/pantsbuild/jsirois-pex/.tox/vendor/lib/python3.8/site-packages/baron/baron.py", line 24, in _parse
    return parser(tokens)
  File "/home/jsirois/dev/pantsbuild/jsirois-pex/.tox/vendor/lib/python3.8/site-packages/baron/grammator.py", line 836, in parse
    return parser.parse(iter(tokens))
  File "/home/jsirois/dev/pantsbuild/jsirois-pex/.tox/vendor/lib/python3.8/site-packages/baron/parser.py", line 165, in parse
    raise ParsingError(debug_output)
baron.parser.ParsingError: Error, got an unexpected token $end here:

1755         return p
1756 
1757 
1758 def normalize_name(name):
1759     """Normalize a python package name a la PEP 503"""
1760     # https://www.python.org/dev/peps/pep-0503/#normalized-names
1761     return re.sub('[-_.]+', '-', name).lower()
1762 <---- here

The token $end should be one of those: ASSERT, AT, BACKQUOTE, BINARY, BINARY_RAW_STRING, BINARY_STRING, BREAK, CLASS, COMMENT, COMPLEX, CONTINUE, DEDENT, DEF, DEL, ELLIPSIS, ENDL, ENDMARKER, FLOAT, FLOAT_EXPONANT, FLOAT_EXPONANT_COMPLEX, FOR, FROM, GLOBAL, HEXA, IF, IMPORT, INT, INTERPOLATED_RAW_STRING, INTERPOLATED_STRING, LAMBDA, LEFT_BRACKET, LEFT_PARENTHESIS, LEFT_SQUARE_BRACKET, LONG, MINUS, NAME, NONLOCAL, NOT, OCTA, PASS, PLUS, RAISE, RAW_STRING, RETURN, STAR, STRING, TILDE, TRY, UNICODE_RAW_STRING, UNICODE_STRING, WHILE, WITH, YIELD

Baron has failed to parse this input. If this is valid python code (and by that I mean that the python binary successfully parse this code without any syntax error) (also consider that baron does not yet parse python 3 code integrally) it would be kind if you can extract a snippet of your code that make Baron fails and open a bug here: https://github.com/PyCQA/baron/issues

Sorry for the inconvenience.
...
```

This leaves:
1. Vendor our own copy of requests (requests is ~large; so this also means vendoring chardet, idna, urllib3 and certifi).
2. Resolve our own copy of requests (create and use an internal requests PEX just in time).

**Comment by jsirois** [comment]
Vendoring requests is a rocky road. Post-vendor, a patch is needed in certif to fix Python 3.x and a different patch is needed in requests.packages to fix Python 2.7.

**Comment by jsirois** [comment]
Another option here is to just use `pip download --no-deps --no-index --ignore-requires-python --dest <dest> https://aws:$CODEARTIFACT_AUTH_TOKEN@pantsbuild-282318314562.d.codeartifact.us-west-2.amazonaws.com/pypi/pants.issues.15766/simple/ansicolors/1.1.8/ansicolors-1.1.8-py2.py3-none-any.whl`. This works and the only adjustments in Pex code would be:
+ Use process parallelism for downloads instead of a thread pool (also allows killing file lock specialization for threading scenario).
+ Substitute auth info back into lock URLs at fetch time.

**Comment by jsirois** [comment]
OK. A quick experiment shows re-using pip-download is viable.
