### ISSUE TITLE
PEX 1.1.1, Django 1.8.6, and Python 2.7.10's email -- Error

### ISSUE THREAD

**Issue by c17r** [pantsbuild/pex#186]
I put this as a thread on the Pants Developers list but figure it might be more focused here.  We've converted 12 sites to using PEX and this is the first major hiccup we've run into.

Using the items above with this small test script:

````python
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project.settings")

from django.conf import settings
from django.core.mail import send_mail

send_mail('subject', 'body', 'noone@example.com', ['noone@example.com'])
````

We get an exception from inside Python's email/header code

````python
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 317, in execute
  File ".bootstrap/_pex/pex.py", line 250, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 282, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 363, in _execute
  File ".bootstrap/_pex/pex.py", line 373, in execute_interpreter
  File ".bootstrap/_pex/pex.py", line 403, in execute_content
  File "<exec_function>", line 4, in exec_function
  File "test.py", line 7, in <module>
    send_mail('subject', 'body', 'noone@example.com', ['noone@example.com'])
  File "/Users/christian/tmp/.pex/install/Django-1.8.6-py2.py3-none-any.whl.f9d35ff7278f3bd886094cf8f073aaf21c75ebc9/Django-1.8.6-py2.py3-none-any.whl/django/core/mail/__init__.py", line 62, in send_mail
    return mail.send()
  File "/Users/christian/tmp/.pex/install/Django-1.8.6-py2.py3-none-any.whl.f9d35ff7278f3bd886094cf8f073aaf21c75ebc9/Django-1.8.6-py2.py3-none-any.whl/django/core/mail/message.py", line 303, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/Users/christian/tmp/.pex/install/Django-1.8.6-py2.py3-none-any.whl.f9d35ff7278f3bd886094cf8f073aaf21c75ebc9/Django-1.8.6-py2.py3-none-any.whl/django/core/mail/backends/smtp.py", line 107, in send_messages
    sent = self._send(message)
  File "/Users/christian/tmp/.pex/install/Django-1.8.6-py2.py3-none-any.whl.f9d35ff7278f3bd886094cf8f073aaf21c75ebc9/Django-1.8.6-py2.py3-none-any.whl/django/core/mail/backends/smtp.py", line 123, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/Users/christian/tmp/.pex/install/Django-1.8.6-py2.py3-none-any.whl.f9d35ff7278f3bd886094cf8f073aaf21c75ebc9/Django-1.8.6-py2.py3-none-any.whl/django/core/mail/message.py", line 138, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/generator.py", line 115, in _write
    self._write_headers(msg)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/generator.py", line 164, in _write_headers
    v, maxlinelen=self._maxheaderlen, header_name=h).encode()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/header.py", line 179, in __init__
    if not isinstance(charset, Charset):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
````

We do not get this error from either straight python setup or using virtual environments, only PEX.

If I edit email/header.py so it gives a stack trace at the point it sets `Charset` I get the following with a venv:

````python
  File "test.py", line 5, in <module>
    from django.core.mail import send_mail
  File "/Users/christian/.virtualenvs/ffe/lib/python2.7/site-packages/django/core/mail/__init__.py", line 14, in <module>
    from django.core.mail.message import (
  File "/Users/christian/.virtualenvs/ffe/lib/python2.7/site-packages/django/core/mail/message.py", line 8, in <module>
    from email import (
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/generator.py", line 15, in <module>
    from email.header import Header
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/header.py", line 23, in <module>
    traceback.print_stack()
````

While this via PEX:

````python
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "__main__.py", line 25, in <module>
    bootstrap_pex(__entry_point__)
  File ".bootstrap/_pex/pex_bootstrapper.py", line 98, in bootstrap_pex
    pex.PEX(entry_point).execute()
  File ".bootstrap/_pex/pex.py", line 310, in execute
    with self.patch_sys():
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File ".bootstrap/_pex/pex.py", line 243, in patch_sys
    new_sys_path, new_sys_path_importer_cache, new_sys_modules = cls.minimum_sys()
  File ".bootstrap/_pex/pex.py", line 202, in minimum_sys
    sys_modules = cls.minimum_sys_modules(site_libs)
  File ".bootstrap/_pex/pex.py", line 133, in minimum_sys_modules
    if not hasattr(module, '__path__'):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/__init__.py", line 79, in __getattr__
    __import__(self.__name__)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/generator.py", line 15, in <module>
    from email.header import Header
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/header.py", line 23, in <module>
    traceback.print_stack()

  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "__main__.py", line 25, in <module>
    bootstrap_pex(__entry_point__)
  File ".bootstrap/_pex/pex_bootstrapper.py", line 98, in bootstrap_pex
    pex.PEX(entry_point).execute()
  File ".bootstrap/_pex/pex.py", line 317, in execute
    self._wrap_coverage(self._wrap_profiling, self._execute)
  File ".bootstrap/_pex/pex.py", line 250, in _wrap_coverage
    runner(*args)
  File ".bootstrap/_pex/pex.py", line 282, in _wrap_profiling
    runner(*args)
  File ".bootstrap/_pex/pex.py", line 363, in _execute
    return self.execute_interpreter()
  File ".bootstrap/_pex/pex.py", line 373, in execute_interpreter
    self.execute_content(name, content)
  File ".bootstrap/_pex/pex.py", line 403, in execute_content
    exec_function(ast, globals())
  File "<exec_function>", line 4, in exec_function
  File "test.py", line 5, in <module>
    from django.core.mail import send_mail
  File "/Users/christian/tmp/.pex/install/Django-1.8.6-py2.py3-none-any.whl.f9d35ff7278f3bd886094cf8f073aaf21c75ebc9/Django-1.8.6-py2.py3-none-any.whl/django/core/mail/__init__.py", line 14, in <module>
    from django.core.mail.message import (
  File "/Users/christian/tmp/.pex/install/Django-1.8.6-py2.py3-none-any.whl.f9d35ff7278f3bd886094cf8f073aaf21c75ebc9/Django-1.8.6-py2.py3-none-any.whl/django/core/mail/message.py", line 11, in <module>
    from email.header import Header
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/header.py", line 23, in <module>
    traceback.print_stack()
````

Perhaps something gets missed during the minimum_sys/minimum_sys_modules clean up?

**Comment by c17r** [comment]
Any thoughts on this issue?  Turns out it also breaks when django tries to email about a 500 to the admins.

**Comment by c17r** [comment]
Thanks to the pants-devel list, we got something that works: building the PEX file with "--not-zip-safe --always-write-cache" as flags.

**Comment by butlern** [comment]
Came across this exact same issue and thought I'd share our solution. Setting zip_safe=False in your BUILD file or passing PEX_FORCE_LOCAL=true at runtime does fix this. However, that solution didn't solve the problem (for us) with pants run (since we want our dev to match our pex deployed prod environment).

So I dug into this and it turns out that django overrides the default `email.message.Message:as_string` method. Now here's where it gets weird, looking at the default method vs the django one (in `django.core.mail.message.MIMEMixin:as_string`), aside from the django one doing some six.PY2/PY3 stuff and adding an as_bytes method (for py2/py3 cross functionality) the ONLY other difference* is how the Generator class is imported/used.

In the broken django version:
```
from email import generator
generator.Generator(...)
```

In the working default version:
```
from email.generator import Generator
Generator(...)
```

I tested monkeypatching the django as_string with the same logic except for different import and call and it works both for pants run and with a unexploded pex file.

Here's the monkeypatch
```
$ cat monkeypatches.py
def patched_as_string(self, unixfrom=False, linesep='\n'):
    """Return the entire formatted message as a string.
    Optional `unixfrom' when True, means include the Unix From_ envelope
    header.

    This overrides the default as_string() implementation to not mangle
    lines that begin with 'From '. See bug #13433 for details.
    """
    from email.generator import Generator # This is the patch!
    fp = six.StringIO()
    #g = generator.Generator(fp, mangle_from_=False) <- THIS FAILS
    g = Generator(fp, mangle_from_=False) # This is the patch!
    if six.PY2:
        g.flatten(self, unixfrom=unixfrom)
    else:
        g.flatten(self, unixfrom=unixfrom, linesep=linesep)
    return fp.getvalue()

def patch_django_core_mail_message_MIMEMixin():
    import django.core.mail.message
    django.core.mail.message.MIMEMixin.as_string = patched_as_string
    if six.PY2:
        django.core.mail.message.MIMEMixin.as_bytes = patched_as_string
```

And then in your settings.py

```
import monkeypatches
monkeypatches.patch_django_core_mail_message_MIMEMixin()
```

Clearly this is not a good long term solution, ymmv.

*I lied there's one other difference which is `Generator()` is called with `mangle_from_=False` but that doesn't seem to cause the problem.
