### ISSUE TITLE
Pex fails to find RECORD for python-certifi-win32 1.6.1

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1861]
Looks like:
```
$ pex python-certifi-win32==1.6.1
Traceback (most recent call last):
  File "/home/jsirois/.venv/pex/bin/pex", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/bin/pex.py", line 775, in main
    catch(
    ^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/result.py", line 103, in catch
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/bin/pex.py", line 798, in do_main
    pex_builder = build_pex(
                  ^^^^^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/bin/pex.py", line 681, in build_pex
    result = resolve(
             ^^^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/resolver.py", line 948, in resolve
    build_and_install_request.install_distributions(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/resolver.py", line 714, in install_distributions
    for install_result in execute_parallel(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/jobs.py", line 541, in execute_parallel
    yield spawn_result.spawned_job.await_result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/jobs.py", line 220, in await_result
    job.wait()
    ^^^^^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/jobs.py", line 81, in wait
    self._finalize_job()
    ^^^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/jobs.py", line 139, in _finalize_job
    self._finalizer(self._process.returncode)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/pip/tool.py", line 711, in fixup_install
    record = Record.from_prefix_install(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/.venv/pex/lib/python3.11/site-packages/pex/pep_376.py", line 445, in from_prefix_install
    raise RecordNotFoundError(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
pex.pep_376.RecordNotFoundError: Could not find the installation RECORD for python-certifi-win32 1.6.1 under /home/jsirois/.pex/installed_wheels/508fd4fb1730cad2d9dada061df737650c8cfaa205d64657faa4cc6a55384402/python_certifi_win32-1.6.1-py2.py3-none-any.whl.353db331daf74436a74d93cf324aa9a9
```

**Comment by jsirois** [comment]
The `--prefix` install is:
$ pip install --prefix chroot --no-deps python_certifi_win32-1.6.1-py2.py3-none-any.whl
$ tree -L 4 chroot/
chroot/
└── lib
    ├── python3.10
    │   └── site-packages
    │       ├── certifi_win32
    │       └── python_certifi_win32-1.6.1.dist-info
    └── site-packages
        └── python-certifi-win32-init.pth

6 directories, 1 file
It's trying to install a .pth file and misses. Those must belong to the site-packages directory of a venv which is chroot/lib/python3.10/site-packages in this case and not chroot/lib/site-packages.  The issue is in how they package the .pth file:
$ zipinfo -1 python_certifi_win32-1.6.1-py2.py3-none-any.whl 
certifi_win32/__init__.py
certifi_win32/bootstrap.py
certifi_win32/wincerts.py
certifi_win32/wrapt_certifi.py
certifi_win32/wrapt_pip.py
python_certifi_win32-1.6.1.data/data/lib/site-packages/python-certifi-win32-init.pth
python_certifi_win32-1.6.1.dist-info/LICENSE
python_certifi_win32-1.6.1.dist-info/METADATA
python_certifi_win32-1.6.1.dist-info/WHEEL
python_certifi_win32-1.6.1.dist-info/top_level.txt
python_certifi_win32-1.6.1.dist-info/RECORD
Instead of storing it as python-certifi-win32-init.pth at the top-level, they attempt to use the data files mechanism.

All that said, this should not trip Pex up. I'll get up a fix and Pex release today. Once done I can give you some pants.toml edits here to get you using the fixed Pex.
