### ISSUE TITLE
`--inherit-path {prefer,fallback}` does not work but `PEX_INHERIT_PATH={prefer,fallback}` does.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1870]
As demonstrated below.

1. Create a venv with `ansicolors` installed.
```
$ python -mvenv ansicolors.venv
$ ansicolors.venv/bin/pip -q install -U pip
$ ansicolors.venv/bin/pip -q install ansicolors
```

2. Create an empty PEX with no user code or 3rdparty dependencies, but with inherit_path configured as "prefer".
```
$ pex --inherit-path=prefer -o empty.pex
$ pex-tools empty.pex info | jq .inherit_path
"prefer"
```

3. Try to run it as configured and pick up the venv ansicolors:
```
$ PEX_VERBOSE=1 ansicolors.venv/bin/python empty.pex -c 'import colors; print(colors.__file__)'
pex: Laying out PEX zipfile /home/jsirois/dev/pantsbuild/jsirois-pex/empty.pex: 0.1ms
pex: Executing installed PEX for /home/jsirois/dev/pantsbuild/jsirois-pex/empty.pex at /home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5
pex:   Testing /home/jsirois/dev/pantsbuild/jsirois-pex/ansicolors.venv/bin/python can resolve PEX at /home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5: 0.1ms
pex: Re-executing: cmdline='/usr/bin/python3.10 /home/jsirois/dev/pantsbuild/jsirois-pex/empty.pex -c import colors; print(colors.__file__)', sys.executable='/home/jsirois/dev/pantsbuild/jsirois-pex/ansicolors.venv/bin/python', PEX_PYTHON=None, PEX_PYTHON_PATH=None, interpreter_constraints=[]
pex: Laying out PEX zipfile /home/jsirois/dev/pantsbuild/jsirois-pex/empty.pex: 0.1ms
pex: Executing installed PEX for /home/jsirois/dev/pantsbuild/jsirois-pex/empty.pex at /home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5
pex: Found site-library: /usr/lib/python3.10/site-packages
pex: Tainted path element: /usr/lib/python3.10/site-packages
pex: New sys.path: ['/home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5/.bootstrap', '/home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/usr/lib/python3.10/site-packages']
pex: Activating PEX virtual environment from /home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5: 0.1ms
pex: No entry point specified, dropping into interpreter
pex: Bootstrap complete, performing final sys.path modifications...
pex: PYTHONPATH contains:
pex:   * 
pex:     /home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5
pex:   * /usr/lib/python310.zip
pex:     /usr/lib/python3.10
pex:     /usr/lib/python3.10/lib-dynload
pex:     /usr/lib/python3.10/site-packages
pex:     /home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5/.bootstrap
pex:   * - paths that do not exist or will be imported via zipimport
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5/__main__.py", line 103, in <module>
    bootstrap_pex(__entry_point__, execute=__execute__, venv_dir=__venv_dir__)
  File "/home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5/.bootstrap/pex/pex_bootstrapper.py", line 601, in bootstrap_pex
    pex.PEX(entry_point).execute()
  File "/home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5/.bootstrap/pex/pex.py", line 528, in execute
    sys.exit(self._wrap_coverage(self._wrap_profiling, self._execute))
  File "/home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5/.bootstrap/pex/pex.py", line 435, in _wrap_coverage
    return runner(*args)
  File "/home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5/.bootstrap/pex/pex.py", line 466, in _wrap_profiling
    return runner(*args)
  File "/home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5/.bootstrap/pex/pex.py", line 560, in _execute
    return self.execute_interpreter()
  File "/home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5/.bootstrap/pex/pex.py", line 617, in execute_interpreter
    return self.execute_content("-c <cmd>", content, argv0="-c")
  File "/home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5/.bootstrap/pex/pex.py", line 713, in execute_content
    return cls.execute_ast(name, program, argv0=argv0)
  File "/home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5/.bootstrap/pex/pex.py", line 731, in execute_ast
    exec_function(program, globals_map)
  File "/home/jsirois/dev/pantsbuild/jsirois-pex/pex/compatibility.py", line 94, in exec_function
    exec (ast, globals_map, locals_map)
  File "-c <cmd>", line 1, in <module>
ModuleNotFoundError: No module named 'colors'
```

4. Instead run it with `PEX_INHERIT_PATH=prefer`:
```
$ PEX_VERBOSE=1 PEX_INHERIT_PATH=prefer ansicolors.venv/bin/python empty.pex -c 'import colors; print(colors.__file__)'
pex: Laying out PEX zipfile /home/jsirois/dev/pantsbuild/jsirois-pex/empty.pex: 0.1ms
pex: Executing installed PEX for /home/jsirois/dev/pantsbuild/jsirois-pex/empty.pex at /home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5
pex:   Testing /home/jsirois/dev/pantsbuild/jsirois-pex/ansicolors.venv/bin/python can resolve PEX at /home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5: 0.1ms
pex: Using the current interpreter /home/jsirois/dev/pantsbuild/jsirois-pex/ansicolors.venv/bin/python since it matches constraints and PYTHONPATH is not set.
pex: Found site-library: /home/jsirois/dev/pantsbuild/jsirois-pex/ansicolors.venv/lib/python3.10/site-packages
pex: Tainted path element: /home/jsirois/dev/pantsbuild/jsirois-pex/ansicolors.venv/lib/python3.10/site-packages
pex: New sys.path: ['/home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5/.bootstrap', '/home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/jsirois/dev/pantsbuild/jsirois-pex/ansicolors.venv/lib/python3.10/site-packages']
pex: Activating PEX virtual environment from /home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5: 0.0ms
pex: No entry point specified, dropping into interpreter
pex: Bootstrap complete, performing final sys.path modifications...
pex: PYTHONPATH contains:
pex:   * 
pex:     /home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5
pex:   * /usr/lib/python310.zip
pex:     /usr/lib/python3.10
pex:     /usr/lib/python3.10/lib-dynload
pex:     /home/jsirois/dev/pantsbuild/jsirois-pex/ansicolors.venv/lib/python3.10/site-packages
pex:     /home/jsirois/.pex/unzipped_pexes/8a70498a7d95a6ecedde810dd5f69e9ad7407dd5/.bootstrap
pex:   * - paths that do not exist or will be imported via zipimport
/home/jsirois/dev/pantsbuild/jsirois-pex/ansicolors.venv/lib/python3.10/site-packages/colors/__init__.py
```

**Comment by jsirois** [comment]
Ok, the reading of the setting is just plain broken afaict and has been for a long time:
https://github.com/pantsbuild/pex/blob/4aecc86263ccf8d27630ef761335591ab5100759/pex/pex.py#L387-L394

**Comment by jsirois** [comment]
Ah, no. That code is actually fine. The problem is here and fully explains the env-var / PEX-INFO venv-busting behavior discrepancy:
https://github.com/pantsbuild/pex/blob/bb68814b476c96ae25576620b685122695429bad/pex/pex_bootstrapper.py#L386-L398
