### ISSUE TITLE
`PEX_ROOT/unzippped_pexes/<hash>/__main__.py` fails to find ~itself in its own stack frame.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1955]
See in a Pants CI job here: https://github.com/pantsbuild/pants/actions/runs/3283455197/jobs/5408557053#step:11:11743
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/__main__.py", line 103, in <module>
    bootstrap_pex(__entry_point__, execute=__execute__, venv_dir=__venv_dir__)
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/pex_bootstrapper.py", line 595, in bootstrap_pex
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/pex_bootstrapper.py", line 662, in _bootstrap_venv
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/pex_bootstrapper.py", line 496, in ensure_venv
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/venv/virtualenv.py", line 217, in create_atomic
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/venv/virtualenv.py", line 200, in create
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/venv/virtualenv.py", line 235, in __init__
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/interpreter.py", line 886, in from_binary
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/interpreter.py", line 865, in _spawn_from_binary
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/interpreter.py", line 806, in _spawn_from_binary_external
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/interpreter.py", line 662, in _create_isolated_cmd
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/third_party/__init__.py", line 591, in expose
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/third_party/__init__.py", line 460, in isolated
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/util.py", line 109, in dir_hash
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/hashing.py", line 213, in dir_hash
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/hashing.py", line 185, in file_hash
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/__main__.py'
```

This job ran using Pex 2.1.108

**Comment by jsirois** [comment]
Much like in #1956, this backtrace has the same origination creating a venv mode PEX from a PEX that has laid itself out (`<packed PEX> -> unzipped_pexes/<X> -> <create venv of X>`). Maybe even more directly than in #1956, it shows a clear file-exists, a few more lines of code execute, file does not exist:
https://github.com/pantsbuild/pex/blob/bb68814b476c96ae25576620b685122695429bad/pex/hashing.py#L189-L213

The path `/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/__main__.py` that is found not to exist on line 213 was just gathered via a filesystem walk on line 206 above. That is a clear case of that portion of the filesystem changing out from underneath a single function call's execution scope. This case does not involve the sys.path at all; so I'll close #1956 as a dup if this issue.

**Comment by jsirois** [comment]
Ok, this is a broken Pants cherry pick here: https://github.com/pantsbuild/pants/pull/17200#discussion_r1002093435

Pex is fine.
