### ISSUE TITLE
Pex third_party isolation fails.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1956]
See in Pants CI here: https://github.com/pantsbuild/pants/actions/runs/3283455197/jobs/5408557053#step:11:11631
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/__main__.py", line 103, in <module>
    bootstrap_pex(__entry_point__, execute=__execute__, venv_dir=__venv_dir__)
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/pex_bootstrapper.py", line 595, in bootstrap_pex
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/pex_bootstrapper.py", line 662, in _bootstrap_venv
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/pex_bootstrapper.py", line 496, in ensure_venv
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/venv/virtualenv.py", line 217, in create_atomic
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/venv/virtualenv.py", line 200, in create
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/venv/virtualenv.py", line 235, in __init__
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/interpreter.py", line 886, in from_binary
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/interpreter.py", line 865, in _spawn_from_binary
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/interpreter.py", line 806, in _spawn_from_binary_external
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/interpreter.py", line 662, in _create_isolated_cmd
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/third_party/__init__.py", line 591, in expose
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/third_party/__init__.py", line 474, in isolated
AssertionError: Expected the `pex` module to be available via an installed distribution or else via a PEX. Loaded the `pex` module from /home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex and but the enclosing PEX has an unexpected layout /home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384
```

The Pex version here is 2.1.108.

**Comment by jsirois** [comment]
This one makes no sense at all. The relevant code:
https://github.com/pantsbuild/pex/blob/ff8ca0b2a75ddc2852b1194e60de459186895079/pex/third_party/__init__.py#L457-L475

From the backtrace phrase:
```
Loaded the `pex` module from /home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex
```
We see that `pex_path` assigned at line 457 is `/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex` in this case.

Looking at lines above in the backtrace like `File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/pex_bootstrapper.py", line 595, in bootstrap_pex` we can see that the `pex_path` of `/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex` is a directory; yet getting to the point of omitting this error requires failing the `os.path.isdir(pex_path)` check on line 459.

As far as I can tell, the only way for that to happen would be for the PEX process to start running and get to the point of importing `pex.third_party` fully from `"/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/third_party/__init__.py"` and only then, have something remove the `/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/` directory.

**Comment by jsirois** [comment]
And #1955 is even cleaner here in pointing to a filesystem mutation (delete) going on inside the pex root during a PEX invocation. As such I'll close this as dup of that.
