### ISSUE TITLE
Interpreter identification fails with import error of Pex helper code.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1957]
See here in Pants CI: https://github.com/pantsbuild/pants/actions/runs/3283455197/jobs/5408557053#step:11:11606
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/__main__.py", line 103, in <module>
    bootstrap_pex(__entry_point__, execute=__execute__, venv_dir=__venv_dir__)
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/pex_bootstrapper.py", line 595, in bootstrap_pex
    venv_pex = _bootstrap_venv(entry_point, interpreter=target)
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/pex_bootstrapper.py", line 662, in _bootstrap_venv
    return ensure_venv(pex.PEX(entry_point, interpreter=interpreter))
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/pex_bootstrapper.py", line 496, in ensure_venv
    prompt=os.path.basename(ENV.PEX) if ENV.PEX else None,
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/venv/virtualenv.py", line 217, in create_atomic
    prompt=prompt,
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/venv/virtualenv.py", line 200, in create
    return cls(venv_dir, custom_prompt=custom_prompt)
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/venv/virtualenv.py", line 235, in __init__
    self._interpreter = PythonInterpreter.from_binary(python_exe_path)
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/interpreter.py", line 888, in from_binary
    raise cls.IdentificationError("Failed to identify {}: {}".format(binary, e))
pex.interpreter.IdentificationError: Failed to identify /home/runner/.cache/pants/named_caches/pex_root/venvs/58058b45d45f7fd03762b653bb93f82431caf384/2fb94972d8452f704d42872312e5dabc63179e5c.ac8b8cee73234477b8a6510fb836ebe0/bin/python: Executing /home/runner/.cache/pants/named_caches/pex_root/venvs/58058b45d45f7fd03762b653bb93f82431caf384/2fb94972d8452f704d42872312e5dabc63179e5c.ac8b8cee73234477b8a6510fb836ebe0/bin/python3.7 -s -c import os
import sys

from pex.common import atomic_directory, safe_open
from pex.interpreter import PythonIdentity


encoded_identity = PythonIdentity.get(binary='/home/runner/.cache/pants/named_caches/pex_root/venvs/58058b45d45f7fd03762b653bb93f82431caf384/2fb94972d8452f704d42872312e5dabc63179e5c.ac8b8cee73234477b8a6510fb836ebe0/bin/python3.7').encode()
with atomic_directory('/home/runner/.cache/pants/named_caches/pex_root/interpreters/cb5a5cc48daa308903b2e02d5912edda32f6b31e/5da39830088ecda1d6b4be609bf7da6e5ce40464/b464e7fb79e9a6ab1c7a292ab515408ddcac985c', exclusive=False) as cache_dir:
    if not cache_dir.is_finalized():
        with safe_open(
            os.path.join(cache_dir.work_dir, 'INTERP-INFO'), 'w'
        ) as fp:
            fp.write(encoded_identity)
 failed with 1
STDERR:
Traceback (most recent call last):
  File "<string>", line 4, in <module>
ModuleNotFoundError: No module named 'pex.common'
```

This is using Pex 2.1.108.

N.B. that `pex.common` is not special here. Another failure in the same run is here: [XXX](https://github.com/pantsbuild/pants/actions/runs/3283455197/jobs/5408557053#step:11:11527)
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/__main__.py", line 103, in <module>
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/pex_bootstrapper.py", line 595, in bootstrap_pex
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/pex_bootstrapper.py", line 662, in _bootstrap_venv
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/pex_bootstrapper.py", line 496, in ensure_venv
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/venv/virtualenv.py", line 217, in create_atomic
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/venv/virtualenv.py", line 200, in create
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/venv/virtualenv.py", line 235, in __init__
  File "/home/runner/.cache/pants/named_caches/pex_root/unzipped_pexes/58058b45d45f7fd03762b653bb93f82431caf384/.bootstrap/pex/interpreter.py", line 888, in from_binary
pex.interpreter.IdentificationError: Failed to identify /home/runner/.cache/pants/named_caches/pex_root/venvs/58058b45d45f7fd03762b653bb93f82431caf384/2fb94972d8452f704d42872312e5dabc63179e5c.c5ab6068739b46d4a09756b102ded79d/bin/python: Executing /home/runner/.cache/pants/named_caches/pex_root/venvs/58058b45d45f7fd03762b653bb93f82431caf384/2fb94972d8452f704d42872312e5dabc63179e5c.c5ab6068739b46d4a09756b102ded79d/bin/python3.7 -s -c import os
import sys

from pex.common import atomic_directory, safe_open
from pex.interpreter import PythonIdentity


encoded_identity = PythonIdentity.get(binary='/home/runner/.cache/pants/named_caches/pex_root/venvs/58058b45d45f7fd03762b653bb93f82431caf384/2fb94972d8452f704d42872312e5dabc63179e5c.c5ab6068739b46d4a09756b102ded79d/bin/python3.7').encode()
with atomic_directory('/home/runner/.cache/pants/named_caches/pex_root/interpreters/cb5a5cc48daa308903b2e02d5912edda32f6b31e/5da39830088ecda1d6b4be609bf7da6e5ce40464/fdaa70951b4cf638c9414b00dea73405c79fe51b', exclusive=False) as cache_dir:
    if not cache_dir.is_finalized():
        with safe_open(
            os.path.join(cache_dir.work_dir, 'INTERP-INFO'), 'w'
        ) as fp:
            fp.write(encoded_identity)
 failed with 1
STDERR:
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/home/runner/.cache/pants/named_caches/pex_root/isolated/fcac194ac43af04ce78beb45d6ba56cadf657df5/pex/interpreter.py", line 23, in <module>
ModuleNotFoundError: No module named 'pex.executor'
```

**Comment by jsirois** [comment]
I'll note that both of these backtraces have the same origination as in #1956 whose only apparent explanation can be removal of a portion of unzipped_pexes at just the right moment _after_ some code there is already imported. The #1956 case though has the advantage of not entwining sys.path considerations since it has an `isdir` check in Pex code failing for `.../.bootstrap/pex` by code under that directory.

As such I'll close this issue as a dup of that one.
