### ISSUE TITLE
pex init won't work: unable to connect to github.com

### ISSUE THREAD

**Issue by OlgaPaw** [pantsbuild/pex#2016]
```
> pex init
fatal: unable to connect to github.com:
github.com[0: 140.82.121.4]: errno=Operation timed out
```

**Comment by jsirois** [comment]
@OlgaPaw I have no clues what init is here, so my exploration:
```
$ pex -V
2.1.119
$ pex init
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import init
>>> init.__file__
'/home/jsirois/.pex/installed_wheels/db4122f6069d12eaf47e56bae7f59df9e9205fb62780af0d11d0988dbe902a6b/init-0.1.0-py3-none-any.whl/init/__init__.py'
>>>
now exiting InteractiveConsole...
```

So that says `init` is a requirement and Pex resolves it just fine. I see: https://pypi.org/project/init/ and that indicates there is an `init` console script from its examples; so:
```
$ pex init --script init -- --help
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/tmpoescwa1o/__main__.py", line 103, in <module>
    bootstrap_pex(__entry_point__, execute=__execute__, venv_dir=__venv_dir__)
  File "/tmp/tmpoescwa1o/.bootstrap/pex/pex_bootstrapper.py", line 600, in bootstrap_pex
    pex.PEX(entry_point).execute()
  File "/tmp/tmpoescwa1o/.bootstrap/pex/pex.py", line 551, in execute
    sys.exit(self._wrap_coverage(self._wrap_profiling, self._execute))
  File "/tmp/tmpoescwa1o/.bootstrap/pex/pex.py", line 458, in _wrap_coverage
    return runner(*args)
  File "/tmp/tmpoescwa1o/.bootstrap/pex/pex.py", line 489, in _wrap_profiling
    return runner(*args)
  File "/tmp/tmpoescwa1o/.bootstrap/pex/pex.py", line 592, in _execute
    return self.execute_script(self._pex_info.script)
  File "/tmp/tmpoescwa1o/.bootstrap/pex/pex.py", line 725, in execute_script
    return self.execute_ast(dist_script.path, ast, argv0=script_name)
  File "/tmp/tmpoescwa1o/.bootstrap/pex/pex.py", line 768, in execute_ast
    exec_function(program, globals_map)
  File "/tmp/tmpoescwa1o/.bootstrap/pex/compatibility.py", line 109, in exec_function
    exec (ast, globals_map, locals_map)
  File "/home/jsirois/.pex/installed_wheels/db4122f6069d12eaf47e56bae7f59df9e9205fb62780af0d11d0988dbe902a6b/init-0.1.0-py3-none-any.whl/.prefix/bin/init", line 9, in <module>
    from init import cli, info
  File "/home/jsirois/.pex/installed_wheels/db4122f6069d12eaf47e56bae7f59df9e9205fb62780af0d11d0988dbe902a6b/init-0.1.0-py3-none-any.whl/init/cli.py", line 285
    except TypeError, exc:
           ^^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized
```

Ok, that looks like a Python 2 syntax attempted under Python 3 error; so:
```
$ pex --python python2.7 init --script init -- --help

  init 0.1.0

  Usage: init <command> [option]

  Options:

    -h, --help      output the help menu
    -V, --version   output the version number
    -l, --list      show available templates
    -v, --verbose   show more logs
    -q, --quiet     show less logs

  Commands:

    license         show available licenses.
    install         install a template to ~/.init-template/
    update          update templates in ~/.init-template/

  Examples:

    $ init python
    $ init init-template/python

  Find templates on https://github.com/init-template

```

Ok, that seems more like what you're after? You'll need to provide much more detailed information here. What version of Pex are you using? What version of Python are you trying to use? Is `pex init` really your command line? That does not seem right, that should causes `pex` to resolve `init` from PyPI and drop you into a REPL session with `init` on the `sys.path` like in my 1st example.

**Comment by benjyw** [comment]
What is it you're expecting `pex init` to do? What it is actually doing is installing a requirement named `init` (https://pypi.org/project/init/) into a pex file and then dropping into an interpreter in that pex, which is probably not what you intend?

As to why even that is not working, I'm not sure why it cares about github access. Do other requirements have the same issue? E.g., `pex ansicolors`?
