### ISSUE TITLE
PEX can't format an exception

### ISSUE THREAD

**Issue by direvius** [pantsbuild/pex#220]
If there are non-string values ```self._distributions``` [this](https://github.com/pantsbuild/pex/blob/master/pex/pex_builder.py#L214) line does not work:
```
direvius@debuild-trusty:~/robe/yandex-tank$ pex -f wheelhouse/ yandextank -c yandex.tank -o yandex-tank.pex
Traceback (most recent call last):
  File "/usr/local/bin/pex", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pex/bin/pex.py", line 509, in main
    pex_builder = build_pex(reqs, options, resolver_options_builder)
  File "/usr/local/lib/python2.7/dist-packages/pex/bin/pex.py", line 486, in build_pex
    pex_builder.set_script(options.script)
  File "/usr/local/lib/python2.7/dist-packages/pex/pex_builder.py", line 214, in set_script
    script, ', '.join(self._distributions)))
TypeError: sequence item 0: expected string, DistInfoDistribution found
```
The solution is to convert them into strings before joining:
```
', '.join(str(d) for d in self._distributions)
```

**Comment by kwlzn** [comment]
thanks for the bug report! this should be fixed in master and will go out with the 1.1.5 pex release.
