### ISSUE TITLE
Can't install wheels with 'none' abi

### ISSUE THREAD

**Issue by burrows-labs** [pantsbuild/pex#228]
Try to install PyNaCl 1.0.1 from pypi.

```
Box:abc burr0ws$ pex --version
pex 1.1.4
Box:abc burr0ws$ pex -o asdf.pex https://pypi.python.org/packages/cp27/P/PyNaCl/PyNaCl-1.0.1-cp27-none-macosx_10_6_intel.whl#md5=3d24d6e9786fb079c6b31634aa587fc2
Traceback (most recent call last):
  File "/usr/local/bin/pex", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/pex/bin/pex.py", line 509, in main
    pex_builder = build_pex(reqs, options, resolver_options_builder)
  File "/usr/local/lib/python2.7/site-packages/pex/bin/pex.py", line 471, in build_pex
    resolveds = resolver.resolve(resolvables)
  File "/usr/local/lib/python2.7/site-packages/pex/resolver.py", line 200, in resolve
    dist = self.build(package, resolvable.options)
  File "/usr/local/lib/python2.7/site-packages/pex/resolver.py", line 257, in build
    dist = super(CachingResolver, self).build(package, options)
  File "/usr/local/lib/python2.7/site-packages/pex/resolver.py", line 168, in build
    raise Untranslateable('Package %s is not translateable by %s' % (package, translator))
pex.resolver.Untranslateable: Package WheelPackage('file:///Users/burr0ws/.pex/build/PyNaCl-1.0.1-cp27-none-macosx_10_6_intel.whl') is not translateable by ChainedTranslator(WheelTranslator, EggTranslator, SourceTranslator)
```

If I set the abi.

```
Box:abc burr0ws$ wget https://pypi.python.org/packages/cp27/P/PyNaCl/PyNaCl-1.0.1-cp27-none-macosx_10_6_intel.whl#md5=3d24d6e9786fb079c6b31634aa587fc2
--2016-04-07 17:26:13--  https://pypi.python.org/packages/cp27/P/PyNaCl/PyNaCl-1.0.1-cp27-none-macosx_10_6_intel.whl
Resolving pypi.python.org... 199.27.76.223
Connecting to pypi.python.org|199.27.76.223|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 137990 (135K) [application/octet-stream]
Saving to: 'PyNaCl-1.0.1-cp27-none-macosx_10_6_intel.whl'

PyNaCl-1.0.1-cp27-n 100%[===================>] 134.76K  --.-KB/s    in 0.05s   

2016-04-07 17:26:13 (2.51 MB/s) - 'PyNaCl-1.0.1-cp27-none-macosx_10_6_intel.whl' saved [137990/137990]

Box:abc burr0ws$ mv PyNaCl-1.0.1-cp27-none-macosx_10_6_intel.whl PyNaCl-1.0.1-cp27-cp27m-macosx_10_6_intel.whl 
Box:abc burr0ws$ pex -o asdf.pex PyNaCl-1.0.1-cp27-cp27m-macosx_10_6_intel.whl 
```

Possibly related to #213

**Comment by burrows-labs** [comment]
This isn't an issue on HEAD.

**Comment by burrows-labs** [comment]
@ewang Your ABI patch seems related?

**Comment by ewang** [comment]
@burrows-labs I can't seem to reproduce. Are you on OSX 10.11.4 and CPython 2.7.10? What does pex say if you run it with -vvvvv?

#229 is likely related.

```
(dev)Erics-MacBook-Air:workspace ericwang$ pex --version
pex 1.1.4
(dev)Erics-MacBook-Air:workspace ericwang$ pex -vvvvv https://pypi.python.org/packages/cp27/P/PyNaCl/PyNaCl-1.0.1-cp27-none-macosx_10_6_intel.whl#md5=3d24d6e9786fb079c6b31634aa587fc2
pex: Constructed RequestsContext context <pex.http.RequestsContext object at 0x103696250>                            
pex: Building pex :: Resolving distributions :: Fetching file:///Users/ericwang/.pex/build/PyNaCl-1.0.1-cp27-none-macosx_10_6_intel.whl :: Fetching fpex: Building pex :: Resolving distributions :: Translating /private/var/folders/lm/mknz0lm54jxc8sf76q_j27nc0000gn/T/tmpJaoEai/PyNaCl-1.0.1-cp27-nonepex: Constructed RequestsContext context <pex.http.RequestsContext object at 0x1036c1110>                                                                                                    
pex: crawling link i=0 link=Link('file:///Users/ericwang/.pex/build') follow_links=False
pex: crawling link i=0 link=Link('https://pypi.python.org/simple/six/') follow_links=False
pex: Constructed RequestsContext context <pex.http.RequestsContext object at 0x1036c1250>
pex: crawling link i=0 link=Link('https://pypi.python.org/simple/cffi/') follow_links=False
pex: Building pex :: Resolving distributions :: Fetching file:///Users/ericwang/.pex/build/six-1.10.0-py2.py3-none-any.whl :: Fetching file:///Users/pex: Building pex :: Resolving distributions :: Translating /private/var/folders/lm/mknz0lm54jxc8sf76q_j27nc0000gn/T/tmp8SzPQJ/six-1.10.0-py2.py3-nonpex: Building pex :: Resolving distributions :: Fetching file:///Users/ericwang/.pex/build/cffi-1.5.2-cp27-cp27m-macosx_10_6_intel.whl               pex: Building pex :: Resolving distributions :: Fetching file:///Users/ericwang/.pex/build/cffi-1.5.2-cp27-cp27m-macosx_10_6_intel.whl :: Fetching fipex: Building pex :: Resolving distributions :: Translating /private/var/folders/lm/mknz0lm54jxc8sf76q_j27nc0000gn/T/tmp_XG2ZA/cffi-1.5.2-cp27-cp27m-pex: Constructed RequestsContext context <pex.http.RequestsContext object at 0x103ce1810>                                                                                                   
pex: crawling link i=0 link=Link('https://pypi.python.org/simple/pycparser/') follow_links=False
pex: Building pex :: Resolving distributions :: Fetching file:///Users/ericwang/.pex/build/pycparser-2.14.tar.gz :: Fetching file:///Users/ericwang/.pex: Building pex :: Resolving distributions :: Translating /private/var/folders/lm/mknz0lm54jxc8sf76q_j27nc0000gn/T/tmpk3USWt/pycparser-2.14.tar.gz pex: Building pex :: Resolving distributions :: Translating /private/var/folders/lm/mknz0lm54jxc8sf76q_j27nc0000gn/T/tmpk3USWt/pycparser-2.14.tar.gz pex: Building pex :: Resolving distributions :: Translating /private/var/folders/lm/mknz0lm54jxc8sf76q_j27nc0000gn/T/tmpk3USWt/pycparser-2.14.tar.gz   cffi 1.5.2ution :: Packaging pycparser :: Installing /var/folders/lm/mknz0lm54jxc8sf76q_j27nc0000gn/T/tmpSC0TWz
  six 1.10.0
  pycparser 2.14
  PyNaCl 1.0.1
pex: Building pex: 1920.2ms                                                                                                                                                                                                                                           
pex:   Resolving interpreter: 1.0ms
pex:     Setting up interpreter /Users/ericwang/workspace/py_envs/dev/bin/python: 0.9ms
pex:   Resolving distributions: 1811.2ms
pex:     Fetching file:///Users/ericwang/.pex/build/PyNaCl-1.0.1-cp27-none-macosx_10_6_intel.whl: 1.8ms
pex:       Fetching file:///Users/ericwang/.pex/build/PyNaCl-1.0.1-cp27-none-macosx_10_6_intel.whl: 1.0ms
pex:     Translating /private/var/folders/lm/mknz0lm54jxc8sf76q_j27nc0000gn/T/tmpJaoEai/PyNaCl-1.0.1-cp27-none-macosx_10_6_intel.whl into distribution: 3.5ms
pex:     Fetching file:///Users/ericwang/.pex/build/six-1.10.0-py2.py3-none-any.whl: 1.8ms
pex:       Fetching file:///Users/ericwang/.pex/build/six-1.10.0-py2.py3-none-any.whl: 0.9ms
pex:     Translating /private/var/folders/lm/mknz0lm54jxc8sf76q_j27nc0000gn/T/tmp8SzPQJ/six-1.10.0-py2.py3-none-any.whl into distribution: 2.6ms
pex:     Fetching file:///Users/ericwang/.pex/build/cffi-1.5.2-cp27-cp27m-macosx_10_6_intel.whl: 2.1ms
pex:       Fetching file:///Users/ericwang/.pex/build/cffi-1.5.2-cp27-cp27m-macosx_10_6_intel.whl: 1.3ms
pex:     Translating /private/var/folders/lm/mknz0lm54jxc8sf76q_j27nc0000gn/T/tmp_XG2ZA/cffi-1.5.2-cp27-cp27m-macosx_10_6_intel.whl into distribution: 2.6ms
pex:     Fetching file:///Users/ericwang/.pex/build/pycparser-2.14.tar.gz: 2.5ms
pex:       Fetching file:///Users/ericwang/.pex/build/pycparser-2.14.tar.gz: 1.5ms
pex:     Translating /private/var/folders/lm/mknz0lm54jxc8sf76q_j27nc0000gn/T/tmpk3USWt/pycparser-2.14.tar.gz into distribution: 1248.4ms
pex:       Packaging pycparser: 1138.1ms
pex:         Installing /var/folders/lm/mknz0lm54jxc8sf76q_j27nc0000gn/T/tmpSC0TWz: 1133.2ms
Running PEX file at /var/folders/lm/mknz0lm54jxc8sf76q_j27nc0000gn/T/tmpfUyc4S with args []
pex: PEX.run invoking /Users/ericwang/workspace/py_envs/dev/bin/python /var/folders/lm/mknz0lm54jxc8sf76q_j27nc0000gn/T/tmpfUyc4S
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> 
```

**Comment by burrows-labs** [comment]
I'm on OS X 10.10.5, cpython 2.7.11.

```
Box:abc burr0ws$ pex -vvvvv https://pypi.python.org/packages/cp27/P/PyNaCl/PyNaCl-1.0.1-cp27-none-macosx_10_6_intel.whl#md5=3d24d6e9786fb079c6b31634aa587fc2
pex: Building pex :: Resolving interpreter :: Setting up interpreter /usr/local/pex: Building pex :: Resolving distributions                                    pex: Constructed RequestsContext context <pex.http.RequestsContext object at 0x10f37d410>
pex: Building pex :: Resolving distributions :: Fetching file:///Users/burr0ws/.pex: Building pex :: Resolving distributions :: Fetching file:///Users/burr0ws/.pex/build/PyNaCl-1.0.1-cp27-none-macosx_10_6_intel.whl :: Fetching file:///Userspex: Building pex :: Resolving distributions :: Translating /private/var/folders/ph/ccypy1wd3px4r00xh39287vm0000gr/T/tmpYazsGn/PyNaCl-1.0.1-cp27-none-macosx_10_Traceback (most recent call last):                              
  File "/usr/local/bin/pex", line 9, in <module>
    load_entry_point('pex==1.1.4', 'console_scripts', 'pex')()
  File "build/bdist.macosx-10.10-x86_64/egg/pex/bin/pex.py", line 509, in main
  File "build/bdist.macosx-10.10-x86_64/egg/pex/bin/pex.py", line 471, in build_pex
  File "build/bdist.macosx-10.10-x86_64/egg/pex/resolver.py", line 200, in resolve
  File "build/bdist.macosx-10.10-x86_64/egg/pex/resolver.py", line 257, in build
  File "build/bdist.macosx-10.10-x86_64/egg/pex/resolver.py", line 168, in build
pex.resolver.Untranslateable: Package WheelPackage('file:///Users/burr0ws/.pex/build/PyNaCl-1.0.1-cp27-none-macosx_10_6_intel.whl') is not translateable by ChainedTranslator(WheelTranslator, EggTranslator, SourceTranslator)
```

**Comment by burrows-labs** [comment]
Tried running the command on OS X 10.11 and it worked fine.

**Comment by kwlzn** [comment]
seems odd that the OS version would be the thing affecting this. any chance you have a repro or can write an xfail test to expose the breakage?

**Comment by kwlzn** [comment]
closing this one - feel free to reopen if you have a repro.
