### ISSUE TITLE
pex on Windows; issues getting started

### ISSUE THREAD

**Issue by burrows-labs** [pantsbuild/pex#230]
Install and create a pex.

```
PS C:\Users\Administrator\code\core> pip uninstall wheel
Uninstalling wheel-0.29.0:
Proceed (y/n)? y
  Successfully uninstalled wheel-0.29.0
PS C:\Users\Administrator\code\core> pip install --no-cache-dir pex
Collecting pex
  Downloading pex-1.1.4-py2.py3-none-any.whl (98kB)
    100% |################################| 102kB 5.4MB/s
Requirement already satisfied (use --upgrade to upgrade): setuptools<20,>=2.2 in c:\python27\lib\site-packages (from pex
)
Installing collected packages: pex
Successfully installed pex-1.1.4
You are using pip version 8.1.0, however version 8.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\Users\Administrator\code\core> pex -o abc.pex
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pex.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\pex\bin\pex.py", line 509, in main
    pex_builder = build_pex(reqs, options, resolver_options_builder)
  File "c:\python27\lib\site-packages\pex\bin\pex.py", line 444, in build_pex
    interpreter = interpreter_from_options(options)
  File "c:\python27\lib\site-packages\pex\bin\pex.py", line 437, in interpreter_from_options
    interpreter = resolve(interpreter, WHEEL_REQUIREMENT)
  File "c:\python27\lib\site-packages\pex\bin\pex.py", line 410, in resolve_interpreter
    installer_provider)
  File "c:\python27\lib\site-packages\pex\bin\pex.py", line 380, in _resolve_and_link_interpreter
    _safe_link(target_location, target_link)
  File "c:\python27\lib\site-packages\pex\bin\pex.py", line 355, in _safe_link
    os.symlink(src, dst)
AttributeError: 'module' object has no attribute 'symlink'
```

I fixed this issue using this snippet http://stackoverflow.com/a/4388195/2197765.

```
import os

__CSL = None
def symlink(source, link_name):
    '''symlink(source, link_name)
       Creates a symbolic link pointing to source named link_name'''
    global __CSL
    if __CSL is None:
        import ctypes
        csl = ctypes.windll.kernel32.CreateSymbolicLinkW
        csl.argtypes = (ctypes.c_wchar_p, ctypes.c_wchar_p, ctypes.c_uint32)
        csl.restype = ctypes.c_ubyte
        __CSL = csl
    flags = 0
    if source is not None and os.path.isdir(source):
        flags = 1
    if __CSL(link_name, source, flags) == 0:
        raise ctypes.WinError()

os.symlink = symlink
```

Try again with the snippet.

```
PS C:\Users\Administrator\code\core> pex -o abc.pex
PS C:\Users\Administrator\code\core> ls .\abc.pex


    Directory: C:\Users\Administrator\code\core


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         4/8/2016   9:49 AM         286363 abc.pex
```

But now if I try to create another pex I get an error.

```
PS C:\Users\Administrator\code\core> pex -o abc2.pex
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pex.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\pex\bin\pex.py", line 509, in main
    pex_builder = build_pex(reqs, options, resolver_options_builder)
  File "c:\python27\lib\site-packages\pex\bin\pex.py", line 444, in build_pex
    interpreter = interpreter_from_options(options)
  File "c:\python27\lib\site-packages\pex\bin\pex.py", line 437, in interpreter_from_options
    interpreter = resolve(interpreter, WHEEL_REQUIREMENT)
  File "c:\python27\lib\site-packages\pex\bin\pex.py", line 410, in resolve_interpreter
    installer_provider)
  File "c:\python27\lib\site-packages\pex\bin\pex.py", line 361, in _resolve_and_link_interpreter
    egg = EggPackage(os.path.realpath(target_link))
  File "c:\python27\lib\site-packages\pex\package.py", line 150, in __init__
    raise self.InvalidPackage('Not an egg: %s' % filename)
pex.package.InvalidPackage: Not an egg: wheel
```

I fixed this by uninstalling  wheel, then installing the version pex wants.

```
PS C:\Users\Administrator\code\core> pip uninstall wheel
Uninstalling wheel-0.29.0:
Proceed (y/n)? y
  Successfully uninstalled wheel-0.29.0
PS C:\Users\Administrator\code\core> pip install wheel==0.25
PS C:\Users\Administrator\code\core> pex -o abc4.pex
PS C:\Users\Administrator\code\core> pex -o abc5.pex
PS C:\Users\Administrator\code\core> pex -o abc6.pex
PS C:\Users\Administrator\code\core> ls .\abc*


    Directory: C:\Users\Administrator\code\core


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         4/8/2016   9:49 AM         286363 abc.pex
-a----         4/8/2016   9:52 AM         286298 abc4.pex
-a----         4/8/2016   9:52 AM         286310 abc5.pex
-a----         4/8/2016   9:54 AM         286364 abc6.pex
```

It looks like there are two separate issues.
+ Windows symlink support
+ Some confusion with the wheel package where pex expects an egg, but it looks like something else (a wheel?)

Confirming that both of these problems exist in master as of,

```
commit cfcfe708989b53ef790bd2733ed7a85cfd6e4e18
Merge: 118bd6d 198ce2f
Author: Kris Wilson <kwlzn@users.noreply.github.com>
Date:   Wed Mar 16 15:31:25 2016 -0700

    Merge pull request #221 from kwlzn/kwlzn/pex/issue_220

    Repair issue #220.
```

**Comment by salimfadhley** [comment]
Is there any releases version that actually does work on windows?

**Comment by jsirois** [comment]
@burrows-labs and @salimfadhley - there should not be - no.  Pex assumes symlinks (as you found out) and hardlinks:
```
$ git grep -E "os.(sym)?link"
pex/bin/pex.py:  os.symlink(src, dst)
pex/common.py:      os.link(source, dest)
pex/common.py:    May raise anything os.link can raise, e.g.
tests/test_integration.py:      os.symlink(sys.executable, symlink_path)
tests/test_pex.py:    os.symlink(site_packages, site_packages_link)
```

Beyond that, I'm sure there are more issues.  At a base we'd need a volunteer with a windows box to fixup issues and then setup an [AppVeyor](https://www.appveyor.com/) CI job to make sure we stay working on Windows going forward.

Are either or both of you on a position to do this sort of work?

**Comment by jsirois** [comment]
I'm going to close this issue as "answered" since pex does not currently support Windows, but I'm hoping you're willing to start contributing patches to get it working going forward.

**Comment by binhex** [comment]
i know this issue is closed, but i would just like to say thanks for the patches above, this does indeed allow pex to run on windows by simply installing the specific version of the wheel package and adding in the missing symlink function for windows, nice work!!. i tested this on windows 10 running python 2.6.6 and had good success with creating pex files.
