### ISSUE TITLE
Bdist_pex failure

### ISSUE THREAD

**Issue by ariscn** [pantsbuild/pex#239]
Seeing the following error:

    Traceback (most recent call last):
      File "setup.py", line 29, in <module>
        zip_safe=False,
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/site-packages/pex/commands/bdist_pex.py", line 68, in run
        for script in self.distribution.entry_points.get('console_scripts', []))
    AttributeError: 'str' object has no attribute 'get'

This is happening because of the following in setup.py:

    setup(
        <...>,
        entry_points='''
            [console_scripts]
            foo = foo.cli:cli
       ''',
    )

This usage is valid. From https://pythonhosted.org/setuptools/setuptools.html#dynamic-discovery-of-services-and-plugins: "The entry_points argument to setup() accepts either a string with .ini-style sections, or a dictionary mapping entry point group names to either strings or lists of strings containing entry point specifiers."

There may be a more robust way to get the list of entry points from setuptools. Otherwise, I can PR a graceful `die()`?

**Comment by jsirois** [comment]
A graceful die would be welcome, handling strings with ConfigParser even better.  Thanks in advance for either!

**Comment by jsirois** [comment]
Fix by @ariscn is in master @ https://github.com/pantsbuild/pex/commit/c7651f02140e607caaaf2d4e007f196dd15d02c3
