### ISSUE TITLE
Bdist_pex from setup.cfg

### ISSUE THREAD

**Issue by pikeas** [pantsbuild/pex#241]
Spinning off from #233, pex-args seems to treat everything as a requirement:

    # setup.cfg
    [bdist_pex]
    pex-args = '-v'

    $ python setup.py bdist_pex
    Traceback (most recent call last):
      File "setup.py", line 29, in <module>
        zip_safe=False,
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/pikeas/code/pex/pex/commands/bdist_pex.py", line 84, in run
        pex_builder = build_pex(reqs, options, options_builder)
      File "/Users/pikeas/code/pex/pex/bin/pex.py", line 457, in build_pex
        resolvables = [Resolvable.get(arg, resolver_option_builder) for arg in args]
      File "/Users/pikeas/code/pex/pex/bin/pex.py", line 457, in <listcomp>
        resolvables = [Resolvable.get(arg, resolver_option_builder) for arg in args]
      File "/Users/pikeas/code/pex/pex/resolvable.py", line 61, in get
        raise cls.InvalidRequirement('Unknown requirement type: %s' % resolvable_string)
    pex.resolvable.InvalidRequirement: Unknown requirement type: '-v'

**Comment by ariscn** [comment]
Working around this with `python setup.py bdist_pex --pex-args='-v -r requirements/base.txt --platform linux-x86_64 -f ~/.pip-wheelhouse'`, but I'd prefer to push this into setup.cfg.

**Comment by jsirois** [comment]
@ariscn and @pikeas : If either of you is up for it, a pull request is welcome.  This would be nice to support.

**Comment by pikeas** [comment]
I'm @ariscn and @pikeas, jumping between work handle and personal handle. I may have some time early next week to review the source and see about a PR.

**Comment by jsirois** [comment]
The `setup.cfg` option values are treated as bare strings, and as a result, your quoting hides the `-` from `ArgParse`. So, I repro given your example `setup.cfg` above, but solve via the following setup.cfg edit in the pex repo (no single-quotes around `-v` - also added a second arg):
```diff
$ git diff -U1 setup.cfg
diff --git a/setup.cfg b/setup.cfg
index 5e40900..8a490f0 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -2 +2,4 @@
 universal = 1
+
+[bdist_pex]
+pex-args = -v --python=python3
```

Which finds success:
```
$ python2.7 setup.py bdist_pex
running bdist_pex
pex: Resolving distributions: 2309.4ms       
pex:     Packaging pex: 503.1ms
  pex 1.1.10
  setuptools 20.10.1
Writing pex to /home/jsirois/dev/pantsbuild/jsirois-pex/dist/pex-1.1.10.pex
$ head -1 dist/pex-1.1.10.pex 
#!/usr/bin/env python3.5
```
