### ISSUE TITLE
Incorrect capitalisation of "ConfigParser"

### ISSUE THREAD

**Issue by tjwalton** [pantsbuild/pex#243]
Having upgraded pex from 1.1.4 to 1.1.5, my build now fails with:

```
pex: Building pex :: Resolving distributions :: Translating /var/lib/jenkins/home/jobs/deploy_dashboard/workspace/build/platforms/dashboard/tmp/tmptJvrim/python-jenkins-0.4.12.tar.gz into distribution
pex: Building pex :: Resolving distributions :: Translating /var/lib/jenkins/home/jobs/deploy_dashboard/workspace/build/platforms/dashboard/tmp/tmptJvrim/python-jenkins-0.4.12.tar.gz into distribution :: Packaging python-jenkins
pex: Building pex :: Resolving distributions :: Translating /var/lib/jenkins/home/jobs/deploy_dashboard/workspace/build/platforms/dashboard/tmp/tmptJvrim/python-jenkins-0.4.12.tar.gz into distribution :: Packaging python-jenkins :: Installing /var/lib/jenkins/home/jobs/deploy_dashboard/workspace/build/platforms/dashboard/tmp/tmpbRO1kr
**** Failed to install python-jenkins-0.4.12. stdout:

**** Failed to install python-jenkins-0.4.12. stderr:
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/var/lib/jenkins/home/jobs/deploy_dashboard/workspace/build/platforms/dashboard/venv2/lib/python2.7/site-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/var/lib/jenkins/home/jobs/deploy_dashboard/workspace/build/platforms/dashboard/venv2/lib/python2.7/site-packages/pbr/util.py", line 264, in cfg_to_args
    wrap_commands(kwargs)
  File "/var/lib/jenkins/home/jobs/deploy_dashboard/workspace/build/platforms/dashboard/venv2/lib/python2.7/site-packages/pbr/util.py", line 566, in wrap_commands
    cmdclass = ep.resolve()
  File "/var/lib/jenkins/home/jobs/deploy_dashboard/workspace/build/platforms/dashboard/venv2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/var/lib/jenkins/home/jobs/deploy_dashboard/workspace/build/platforms/dashboard/venv2/lib/python2.7/site-packages/pex/commands/bdist_pex.py", line 4, in <module>
    from configparser import ConfigParser
ImportError: No module named configparser
error in setup command: Error parsing /var/lib/jenkins/home/jobs/deploy_dashboard/workspace/build/platforms/dashboard/tmp/tmpHgSLc5/python-jenkins-0.4.12/setup.cfg: ImportError: No module named configparser
```

Surely this line should be "from ConfigParser import ConfigParser" not "from configparser import ConfigParser"?

**Comment by jsirois** [comment]
Sorry about this, I should have demanded a test for bdist_pex.  We CI against 2.6 - 3.5 which would have caught this python3-only import.  I'll whip up a test and fix later today unless you beat me to it.

**Comment by jsirois** [comment]
@tjwalton @pikeas - if either of you have bandwidth to review #246 I'd be grateful.

**Comment by jsirois** [comment]
Fix is in master @ https://github.com/pantsbuild/pex/commit/a255b3ad7f0c72e6588be1059f70d14cdc94c7ce

**Comment by tjwalton** [comment]
@jsirois Thanks for this.  Looks good and is working for me now.
