### ISSUE TITLE
PicklingError hangs flake8 pex

### ISSUE THREAD

**Issue by rouge8** [pantsbuild/pex#283]
If I build a pex of flake8, by default, it picks up the 3.0.0b2 version. Running this pex on any Python file hangs indefinitely after a `PicklingError`. `flake8==3.0.0b2` installed in a virtualenv does not have the same behavior.

```console
$ pex 'flake8==3.0.0b2' -c flake8 -- any_python_file.py
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
PicklingError: Can't pickle <class 'pkg_resources._vendor.packaging._structures.NegativeInfinity'>: it's not the same object as pkg_resources._vendor.packaging._structures.NegativeInfinity
```

**Comment by kwlzn** [comment]
the hang seems to be related to the flake8 implementations usage of a multiprocessing queue - I'd bet if you hit a similar `PicklingError` in a worker in the venv context you'd probably see a likewise hang.

at least one topical workaround seems to be:

`$ pex 'flake8==3.0.0b2' -c flake8 -- -j1 setup.py`

which instructs flake8 to use a single core and runs successfully - this seems to confirm a multiprocess related bug.

as to the cause of the PicklingError itself, I'm guessing there's some fundamental difference in the way the class is loaded in the main runtime vs in multiprocessing worker.

if you run `pex 'flake8==3.0.0b2' -c flake8 -- -j2 setup.py` on your laptop then hit control-c, what does the raw traceback look like?

**Comment by rouge8** [comment]
Traceback:

```console
$ pex 'flake8==3.0.0b2' -c flake8 -- -j2 setup.py
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
PicklingError: Can't pickle <class 'pkg_resources._vendor.packaging._structures.NegativeInfinity'>: it's not the same object as pkg_resources._vendor.packaging._structures.NegativeInfinity
^CProcess Process-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
... stopped while processing files
    self._target(*self._args, **self._kwargs)
  File "/private/var/folders/bw/ghklm2fs6bx_x9x_f0wg5kph0000gn/T/tmpvbDNGA/.deps/flake8-3.0.0b2-py2.py3-none-any.whl/flake8/checker.py", line 220, in _run_checks_from_queue
    self.run()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    for checker in iter(self.process_queue.get, 'DONE'):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 115, in get
    self._rlock.acquire()
KeyboardInterrupt
  File "/private/var/folders/bw/ghklm2fs6bx_x9x_f0wg5kph0000gn/T/tmpvbDNGA/.deps/flake8-3.0.0b2-py2.py3-none-any.whl/flake8/checker.py", line 220, in _run_checks_from_queue
    for checker in iter(self.process_queue.get, 'DONE'):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 117, in get
    res = self._recv()
KeyboardInterrupt
```

**Comment by rafaelcaricio** [comment]
I was investigating online references to this bug and I found [this](https://gitlab.com/pycqa/flake8/issues/164), that might help you too to understand what is going on.

**Comment by rouge8** [comment]
Flake8 3.0.4 was released with a fix. Per https://gitlab.com/pycqa/flake8/issues/164, looks like it was not a pex-specific issue.
