### ISSUE TITLE
Unhandled `TypeError` when passing non-local platform without `-o`.

### ISSUE THREAD

**Issue by kwlzn** [pantsbuild/pex#295]
repro:

```
[illuminati tensorflow_resolve]$ pex --platform=linux-x86_64 ordered_set
Traceback (most recent call last):
  File "/Users/kwilson/Python/CPython-2.7.11/bin/pex", line 11, in <module>
    sys.exit(main())
  File "/Users/kwilson/Python/CPython-2.7.11/lib/python2.7/site-packages/pex/bin/pex.py", line 551, in main
    log('WARNING: attempting to run PEX with differing platform!')
TypeError: __call__() takes exactly 3 arguments (2 given)
```

yet works when `-o` is used:

```
[illuminati tensorflow_resolve]$ pex --platform=linux-x86_64 ordered_set -o /tmp/throwaway.pex
[illuminati tensorflow_resolve]$
```

**Comment by Eric-Arellano** [comment]
I can't reproduce this anymore. I suspect it was fixed some time ago.
