### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by Hateman31** [pantsbuild/pex#319]
Hello!
I built pex-file from my project ( https://github.com/Hateman31/RD).
I run 'pex RD -o RD.pex'. When i do "python RD.pex" i get next error:
Traceback (most recent call last):

> `  File ".bootstrap\_pex\pex.py", line 320, in execute
  File ".bootstrap\_pex\pex.py", line 78, in _activate
  File ".bootstrap\_pex\environment.py", line 135, in activate
  File ".bootstrap\_pex\environment.py", line 179, in _activate
  File ".bootstrap\_pex\environment.py", line 124, in update_candidate_distributions
  File ".bootstrap\_pex\environment.py", line 110, in load_internal_cache
  File ".bootstrap\_pex\environment.py", line 97, in write_zipped_internal_cache
  File ".bootstrap\_pex\util.py", line 176, in cache_distribution
  File ".bootstrap\_pex\common.py", line 125, in safe_open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MyPC\\.pex\\install\\Kivy-1.9.1-cp34-none-win32.w
hl.eede4757567c219d7f99978091a446b258778859.aff7e4a3de1a4c60b2fb907744e38d83\\Kivy-1.9.1-cp34-none-win32.whl\\Kivy-1.9.1
.data/data/share/kivy-examples/demo/kivycatalog/container_kvs/AnchorLayoutContainer.kv'`

What i do wrong?
Thanks!

**Comment by jsirois** [comment]
Windows is the issue here, pex has no support for it. The only hint I think we give is here: https://github.com/pantsbuild/pex/blob/master/setup.py#L38-L40

We have had some folks spend some time to get parts of ex prepped for Windows, but no concerted effort which would necessarily end in an AppVeyor CI job being wired up so we stay green and, further, continued involvement by win devs to keep things moving forward. Let us know if you're the person to help kick this off, that would be very welcome!

**Comment by chrisjbremner** [comment]
@Hateman31 it looks like the path in your error message is 261 characters long, which exceeds the [maximum path length in Windows](https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file#maximum-path-length-limitation). See https://github.com/pantsbuild/pex/pull/596 for a proposed fix.
