### ISSUE TITLE
OSError: [Errno 13] Permission denied: '/home/.pex' errors with pex

### ISSUE THREAD

**Issue by apurva-sharma** [pantsbuild/pex#359]
Hi All,

I have a python script that is used as a reducer script in hive and the whole setup works nicely.
 Now, I am instead packaging the python file as a pex via pants, and the same hive script now throws:
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 321, in execute
  File ".bootstrap/_pex/pex.py", line 78, in _activate
  File ".bootstrap/_pex/environment.py", line 135, in activate
  File ".bootstrap/_pex/environment.py", line 179, in _activate
  File ".bootstrap/_pex/environment.py", line 124, in update_candidate_distributions
  File ".bootstrap/_pex/environment.py", line 110, in load_internal_cache
  File ".bootstrap/_pex/environment.py", line 97, in write_zipped_internal_cache
  File ".bootstrap/_pex/util.py", line 176, in cache_distribution
  File ".bootstrap/_pex/common.py", line 124, in safe_open
  File ".bootstrap/_pex/common.py", line 112, in safe_mkdir
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/.pex'
org.apache.hadoop.hive.ql.metadata.HiveException: [Error 20003]: An error occurred when trying to close the Operator running your custom script.

seems similar to the bug that was hit in https://github.com/twitter/heron/issues/1103  but i don't understand the resolution

**Comment by kwlzn** [comment]
pex requires a write path for caching and other on-disk operations. it defaults to using `$HOME/.pex`. if you don't have a writable $HOME dir, you can override this at runtime with the `PEX_ROOT` environment variable.

e.g.

`PEX_ROOT=/tmp/pex_cache ./the.pex`

or

```
export PEX_ROOT=/tmp/pex_cache
./the.pex
```

etc.
