### ISSUE TITLE
Ambiguous Resolvable raised on transitive dep

### ISSUE THREAD

**Issue by butlern** [pantsbuild/pex#366]
This always fails:

```
$ tox -e py27-package
$ ./dist/pex27 botocore awscli==1.11.54 -o test.pex
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 339, in execute
  File ".bootstrap/_pex/pex.py", line 267, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 299, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 382, in _execute
  File ".bootstrap/_pex/pex.py", line 440, in execute_entry
  File ".bootstrap/_pex/pex.py", line 458, in execute_pkg_resources
  File "/Users/nate/.pex/install/pex-1.2.3-py2.py3-none-any.whl.97a3e8c0f7213b5f56931db5cbda8074a8f4973a/pex-1.2.3-py2.py3-none-any.whl/pex/bin/pex.py", line 578, in main
    pex_builder = build_pex(reqs, options, resolver_options_builder)
  File "/Users/nate/.pex/install/pex-1.2.3-py2.py3-none-any.whl.97a3e8c0f7213b5f56931db5cbda8074a8f4973a/pex-1.2.3-py2.py3-none-any.whl/pex/bin/pex.py", line 527, in build_pex
    resolveds = resolver.resolve(resolvables)
  File "/Users/nate/.pex/install/pex-1.2.3-py2.py3-none-any.whl.97a3e8c0f7213b5f56931db5cbda8074a8f4973a/pex-1.2.3-py2.py3-none-any.whl/pex/resolver.py", line 205, in resolve
    raise self.Error('Ambiguous resolvable: %s' % resolvable)
pex.resolver.Error: Ambiguous resolvable: botocore
```

It looks like this happens because botocore is unbounded and https://github.com/pantsbuild/pex/blob/master/pex/resolver.py#L201 grabs the first SourcePackage from the list of packages which happens to be the latest, 1.5.18. However, awscli==1.11.54 transitively depends upon botocore==1.5.17 but this isn't found until the second round of `while resolvables` so botocore has already been added to https://github.com/pantsbuild/pex/blob/master/pex/resolver.py#L215 and then this gets raised https://github.com/pantsbuild/pex/blob/master/pex/resolver.py#L204-L205

Note, this is different if we pin botocore==1.5.18 which correctly raises Unsatisfiable because that gets raised when trying to do resolvable_set.merge(). In this case, resolvable_set.merge() works because the unbounded botocore contains all SourcePackages for botocore, including the 1.5.17 version that awscli==1.11.54 requires.

```
$ ./dist/pex27 --cache-ttl=60 awscli==1.11.54 botocore==1.5.18 -o test.pex
Could not satisfy all requirements for botocore==1.5.18:
    botocore==1.5.18, botocore==1.5.17(from: awscli==1.11.54)
```

I have a unit test proving this bug. The potential workaround I've thought up would be to instead of doing this: https://github.com/pantsbuild/pex/blob/master/pex/resolver.py#L222, we need to probably loop back through resolvable_set.packages() and match them up with whats in distributions because by this time the .merge() method should have created the correct set of dependencies or raised Unsatisfiable.

Open to suggestions though. The original code suggests using backtracking.

**Comment by andrask** [comment]
I ran into the seemingly same error with the Openstack Heat client:

    pex python-heatclient

The applied patch resolved the issue.
