### ISSUE TITLE
Numpy fails when built into pex

### ISSUE THREAD

**Issue by nckturner** [pantsbuild/pex#368]
I have a pex with timezonefinder that fails when timezonefinder tries to import numpy.

```
Traceback (most recent call last):
  File "/root/.pex/install/raven-5.10.1-py2.py3-none-any.whl.e595fa40399451d545ed2611069b53ff57fb1a25/raven-5.10.1-py2.py3-none-any.whl/raven/middleware.py", line 35, in __call__
    iterable = self.application(environ, start_response)
  File "/root/.pex/install/Django-1.8.12-py2.py3-none-any.whl.5d6af2ca454320d166bcd084edf34c49de2cc5c4/Django-1.8.12-py2.py3-none-any.whl/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/root/.pex/install/Django-1.8.12-py2.py3-none-any.whl.5d6af2ca454320d166bcd084edf34c49de2cc5c4/Django-1.8.12-py2.py3-none-any.whl/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/root/.pex/install/Django-1.8.12-py2.py3-none-any.whl.5d6af2ca454320d166bcd084edf34c49de2cc5c4/Django-1.8.12-py2.py3-none-any.whl/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/root/.pex/install/Django-1.8.12-py2.py3-none-any.whl.5d6af2ca454320d166bcd084edf34c49de2cc5c4/Django-1.8.12-py2.py3-none-any.whl/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "meetup_server/urls.py", line 17, in <module>
  File "meetup_server/svc_handlers.py", line 6, in <module>
  File "meetup_server/services/__init__.py", line 1, in <module>
  File "meetup_server/services/meetup_service.py", line 12, in <module>
  File "/root/.pex/install/timezonefinder-1.5.7-py2.py3-none-any.whl.556d75090b8bf1daf295e54f61831b8e7babd075/timezonefinder-1.5.7-py2.py3-none-any.whl/timezonefinder/__init__.py", line 3, in <module>
    from .timezonefinder import TimezoneFinder
  File "/root/.pex/install/timezonefinder-1.5.7-py2.py3-none-any.whl.556d75090b8bf1daf295e54f61831b8e7babd075/timezonefinder-1.5.7-py2.py3-none-any.whl/timezonefinder/timezonefinder.py", line 8, in <module>
    from numpy import array, empty, fromfile
  File "/root/.pex/install/numpy-1.12.0-cp27-cp27mu-linux_x86_64.whl.288a6792cf3d92253dc50b91d4bebd9f5bf1590e/numpy-1.12.0-cp27-cp27mu-linux_x86_64.whl/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
ImportError: cannot import name add_newdocs
```

Not sure how to debug this.  This environment is in a debian 8 docker container (the official python2.7 image).  Can anyone help me understand where to start?

**Comment by kwlzn** [comment]
I'm not able to repro this issue based on a quick poke at `timezonefinder`. can you provide a repro?

```
[omerta ~]$ pex --version
pex 1.2.8
[omerta ~]$ pex timezonefinder==1.5.7 numpy==1.12.0
Python 2.7.10 (default, Dec 16 2015, 14:09:45) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from timezonefinder import TimezoneFinder
>>> TimezoneFinder
<class timezonefinder.timezonefinder.TimezoneFinder at 0x1047a32c0>
>>> 
```
