### ISSUE TITLE
ImportError: No module named engine

### ISSUE THREAD

**Issue by y2kenny** [pantsbuild/pex#380]
I try to package a script like this:
```
$ pex -v . plumbum flake8 -e gerritcheck.check:main -o gerritcheck.pex
  pyflakes 1.5.0x :: Resolving distributions :: Packaging gerrit-check
  enum34 1.1.6
  plumbum 1.6.3
  cpplint 1.3.0
  mccabe 0.6.1
  pycodestyle 2.3.1
  gerrit-check 0.1.1
  configparser 3.5.0
  flake8 3.3.0
pex: Building pex: 881.3ms                                            
pex:   Resolving distributions: 653.9ms
pex:       Packaging gerrit-check: 195.5ms
Saving PEX file to gerritcheck.pex
```

But when I try to run the pex file, I get:
```
$ ./gerritcheck.pex 
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 360, in execute
  File ".bootstrap/_pex/pex.py", line 288, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 320, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 403, in _execute
  File ".bootstrap/_pex/pex.py", line 461, in execute_entry
  File ".bootstrap/_pex/pex.py", line 478, in execute_pkg_resources
  File ".bootstrap/pkg_resources.py", line 2088, in load
  File "/home/yuho/.pex/install/gerrit_check-0.1.1-py2-none-any.whl.ba911aee073bfc5485a00464029246321499e8fb/gerrit_check-0.1.1-py2-none-any.whl/gerritcheck/check.py", line 18, in <module>
    from flake8.engine import get_style_guide
ImportError: No module named engine
```

What am I missing?

**Comment by kwlzn** [comment]
looks like your `gerrit_check` application is importing from the wrong namespace for the version of flake8 you're targeting (latest):

```
[omerta ~]$ pex "flake8<3.0.0"
Python 2.7.13 (default, Mar  2 2017, 16:22:01) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from flake8.engine import get_style_guide
>>> 
[omerta ~]$ pex "flake8>=3.0.0"
Python 2.7.13 (default, Mar  2 2017, 16:22:01) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from flake8.engine import get_style_guide
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: No module named engine
>>>
```

**Comment by y2kenny** [comment]
Ah my bad, sorry about that.
