### ISSUE TITLE
minimum_sys_modules blows up when there is a namespaced package in the system

### ISSUE THREAD

**Issue by benjaoming** [pantsbuild/pex#393]
Running a Pex file with Python3 on a clean Ubuntu 17.04 system gave me this:

```
python3 kolibri_buildkite_build-1672_1405_kolibri-v0.4.0-beta10-348-g15069d7.pex
Traceback (most recent call last):
  File "/home/test/Downloads/kolibri_buildkite_build-1672_1405_kolibri-v0.4.0-beta10-348-g15069d7.pex/.bootstrap/_pex/pex.py", line 310, in execute
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/test/Downloads/kolibri_buildkite_build-1672_1405_kolibri-v0.4.0-beta10-348-g15069d7.pex/.bootstrap/_pex/pex.py", line 243, in patch_sys
  File "/home/test/Downloads/kolibri_buildkite_build-1672_1405_kolibri-v0.4.0-beta10-348-g15069d7.pex/.bootstrap/_pex/pex.py", line 202, in minimum_sys
  File "/home/test/Downloads/kolibri_buildkite_build-1672_1405_kolibri-v0.4.0-beta10-348-g15069d7.pex/.bootstrap/_pex/pex.py", line 139, in minimum_sys_modules
TypeError: '_NamespacePath' object does not support indexing
```

Our own issue can be found here: https://github.com/learningequality/kolibri/issues/1710

Started debugging directly using code of `minimum_sys_modules` from pex and extracted from https://github.com/pantsbuild/pex/blob/master/pex/pex.py#L147:

```
>>> for module_name, module in sys.modules.items():
...     if not hasattr(module, '__path__'):
...         continue
...     for k in reversed(range(len(module.__path__))):
...         module.__path__[k]
... 
'/usr/lib/python3.5/xml/dom'
'/usr/lib/python3/dist-packages/apport'
'/usr/lib/python3/dist-packages/apt/progress'
'/usr/lib/python3.5/urllib'
'/usr/lib/python3.5/http'
'/usr/lib/python3.5/xml/parsers'
'/usr/lib/python3/dist-packages/apt'
'/usr/lib/python3.5/json'
'/usr/lib/python3.5/xml'
'/usr/lib/python3.5/collections'
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
TypeError: '_NamespacePath' object does not support indexing
```

Going a bit deeper, we can find:

```
>>> for module_name, module in sys.modules.items():
...     if not hasattr(module, '__path__'):
...         continue
...     print(module.__name__)
...     for k in reversed(range(len(module.__path__))):
...         module.__path__[k]
... 
xml.dom
'/usr/lib/python3.5/xml/dom'
apport
'/usr/lib/python3/dist-packages/apport'
apt.progress
'/usr/lib/python3/dist-packages/apt/progress'
urllib
'/usr/lib/python3.5/urllib'
http
'/usr/lib/python3.5/http'
xml.parsers
'/usr/lib/python3.5/xml/parsers'
apt
'/usr/lib/python3/dist-packages/apt'
json
'/usr/lib/python3.5/json'
xml
'/usr/lib/python3.5/xml'
collections
'/usr/lib/python3.5/collections'
keyrings
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
TypeError: '_NamespacePath' object does not support indexing
```

What seems to be happening is that while pex is introspecting available sys modules, it starts addressing properties of namespaced packages in the wrong way.

```
>>> keyrings.__name__
'keyrings'
>>> keyrings.__path__
_NamespacePath(['/usr/lib/python3/dist-packages/keyrings'])
```

Looking at the `keyrings` package, we find that it indeed doesn't have an `__init__.py` which is allowed

```
ls  -l /usr/lib/python3/dist-packages/keyrings
total 4
drwxr-xr-x 3 root root 4096 Apr 12 05:14 alt
```

The concept of namespaced packages is described here: https://packaging.python.org/guides/packaging-namespace-packages/

**Comment by kwlzn** [comment]
can you provide a minimal repro to create a pex that exhibits this problem? I wasn't able to find a `keyrings` package on pypi.

possibly related to #338

**Comment by kwlzn** [comment]
ah, maybe it's one of the `keyrings.*` packages on pypi?

fwiw, with pex 1.2.8:

```
[omerta ~]$ pex keyring keyrings.alt
Python 3.6.0 (default, Feb 13 2017, 11:02:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import keyrings
>>> keyrings.__path__
_NamespacePath(['/private/var/folders/bb/msvj_4_s741g93nzgrj19twc0000gn/T/tmp_klrnil0/.deps/keyrings.alt-2.2-py2.py3-none-any.whl/keyrings'])
```

so maybe this has been inadvertently fixed since filing?

**Comment by kwlzn** [comment]
marking closed until we hear otherwise.
