### ISSUE TITLE
raised pex.resolver.Untranslateable when trying to use lxml library

### ISSUE THREAD

**Issue by askaliuk** [pantsbuild/pex#397]
On OSX El Captain 10.11.6

```
$ pex lxml==3.7.3 --platform linux-x86_64
Traceback (most recent call last):
  File "/Users/test/.virtualenvs/gagarin/bin/pex", line 9, in <module>
    load_entry_point('pex==1.2.9', 'console_scripts', 'pex')()
  File "/Users/test/.virtualenvs/gagarin/lib/python2.7/site-packages/pex/bin/pex.py", line 596, in main
    pex_builder = build_pex(reqs, options, resolver_options_builder)
  File "/Users/test/.virtualenvs/gagarin/lib/python2.7/site-packages/pex/bin/pex.py", line 547, in build_pex
    for dist in resolveds:
  File "/Users/test/.virtualenvs/gagarin/lib/python2.7/site-packages/pex/resolver.py", line 438, in resolve_multi
    allow_prereleases):
  File "/Users/test/.virtualenvs/gagarin/lib/python2.7/site-packages/pex/resolver.py", line 376, in resolve
    return resolver.resolve(resolvables_from_iterable(requirements, builder))
  File "/Users/test/.virtualenvs/gagarin/lib/python2.7/site-packages/pex/resolver.py", line 209, in resolve
    dist = self.build(package, resolvable.options)
  File "/Users/test/.virtualenvs/gagarin/lib/python2.7/site-packages/pex/resolver.py", line 282, in build
    dist = super(CachingResolver, self).build(package, options)
  File "/Users/test/.virtualenvs/gagarin/lib/python2.7/site-packages/pex/resolver.py", line 177, in build
    raise Untranslateable('Package %s is not translateable by %s' % (package, translator))
pex.resolver.Untranslateable: Package SourcePackage(u'file:///Users/test/.pex/build/lxml-3.7.3.tar.gz') is not translateable by ChainedTranslator(WheelTranslator, EggTranslator, SourceTranslator)
```

**Comment by jsirois** [comment]
In order to build a pex that supports a platform other than the current platform, you need to point pex at pre-built binary packages (wheel or egg) for the foreign platform. Your command line suggests you haven't done this since there are no flags customizing resolution (ie: pex is trying to find a linux-x86_64 lxml on pypi and failing).

**Comment by jsirois** [comment]
Closing this as `answered` but please re-open if this explanation is not enough to help you get past this problem.
