### ISSUE TITLE
Trying to upgrade pex to 1.12.11 for bazel in Heron gives error

### ISSUE THREAD

**Issue by kramasamy** [pantsbuild/pex#414]
I am trying to upgrade Twitter Heron code base to use the new version of pex 1.2.11. The pex code is embedded into Heron code base and we use bazel py_binary to run the pex on python files to generate pex files. When using pex 1.2.11, I am getting the following error.

ERROR: /Users/karthikz/workspace/heron23/heron/examples/src/python/BUILD:39:1: PexPython heron/examples/src/python/custom_grouping.pex failed (Exit 1).
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_karthikz/f8e9a360cd450b19009ba7543f62ceea/execroot/__main__/bazel-out/host/bin/third_party/pex/_pex.runfiles/__main__/third_party/pex/_pex.py", line 211, in <module>
    sys.exit(main())
  File "/private/var/tmp/_bazel_karthikz/f8e9a360cd450b19009ba7543f62ceea/execroot/__main__/bazel-out/host/bin/third_party/pex/_pex.runfiles/__main__/third_party/pex/_pex.py", line 151, in main
    interpreter = resolve_or_die(interpreter, SETUPTOOLS_REQUIREMENT, poptions)
  File "/private/var/tmp/_bazel_karthikz/f8e9a360cd450b19009ba7543f62ceea/execroot/__main__/bazel-out/host/bin/third_party/pex/_pex.runfiles/__main__/third_party/pex/_pex.py", line 81, in resolve_or_die
    interpreter = resolve(interpreter, requirement)
  File "/private/var/tmp/_bazel_karthikz/f8e9a360cd450b19009ba7543f62ceea/execroot/__main__/bazel-out/host/bin/third_party/pex/_pex.runfiles/__main__/third_party/pex/pex/bin/pex.py", line 471, in resolve_interpreter
    installer_provider)
  File "/private/var/tmp/_bazel_karthikz/f8e9a360cd450b19009ba7543f62ceea/execroot/__main__/bazel-out/host/bin/third_party/pex/_pex.runfiles/__main__/third_party/pex/pex/bin/pex.py", line 428, in _resolve_and_link_interpreter
    links = [link for link in iterator.iter(requirement) if isinstance(link, SourcePackage)]
  File "/private/var/tmp/_bazel_karthikz/f8e9a360cd450b19009ba7543f62ceea/execroot/__main__/bazel-out/host/bin/third_party/pex/_pex.runfiles/__main__/third_party/pex/pex/iterator.py", line 38, in iter
    if package.satisfies(req, allow_prereleases=self.__allow_prereleases):
  File "/private/var/tmp/_bazel_karthikz/f8e9a360cd450b19009ba7543f62ceea/execroot/__main__/bazel-out/host/bin/third_party/pex/_pex.runfiles/__main__/third_party/pex/pex/package.py", line 87, in satisfies
    return requirement.specifier.contains(self.raw_version, prereleases=allow_prereleases)
AttributeError: Requirement instance has no attribute 'specifier'

**Comment by kwlzn** [comment]
this strikes me as a setuptools version issue, but it'd be good to provide a minimal repro outside of bazel with just the pex invocations to help determine if this is a pex bug vs a bazel rule implementation bug (we're unequipped to handle the latter).
