### ISSUE TITLE
pex packaging code from git? (git+https support?)

### ISSUE THREAD

**Issue by itdaniher** [pantsbuild/pex#439]
Like #429, I'm trying to use pex with Pipenv. Unlike #429, I'm trying package code from an upstream git repo into a pex file.

```shell
pipenv lock -r | awk -F ' --' '{print $1}' > requirements.txt
```

giving me a requirements.txt including lines like:

```
git+https://github.com/Blosc/python-blosc.git#egg=blosc
git+https://github.com/pyca/pynacl.git#egg=pynacl
```

which pex chokes on:

```python
Traceback (most recent call last):
  File "/home/name/.pex/install/pex-1.2.15-py2.py3-none-any.whl.c57747ed87261721509db19020b7431dec741af3/pex-1.2.15-py2.py3-none-any.whl/pex/requirements.py", line 80, in requirements_from_lines
    resolvables.append(Resolvable.get(resolvable, builder))
  File "/home/name/.pex/install/pex-1.2.15-py2.py3-none-any.whl.c57747ed87261721509db19020b7431dec741af3/pex-1.2.15-py2.py3-none-any.whl/pex/resolvable.py", line 71, in get
    raise cls.InvalidRequirement('Unknown requirement type: %s' % resolvable_string)
pex.resolvable.InvalidRequirement: Unknown requirement type: git+https://github.com/Blosc/python-blosc.git#egg=blosc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 365, in execute
  File ".bootstrap/_pex/pex.py", line 293, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 325, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 408, in _execute
  File ".bootstrap/_pex/pex.py", line 466, in execute_entry
  File ".bootstrap/_pex/pex.py", line 484, in execute_pkg_resources
  File "/home/name/.pex/install/pex-1.2.15-py2.py3-none-any.whl.c57747ed87261721509db19020b7431dec741af3/pex-1.2.15-py2.py3-none-any.whl/pex/bin/pex.py", line 648, in main
    pex_builder = build_pex(reqs, options, resolver_options_builder)
  File "/home/name/.pex/install/pex-1.2.15-py2.py3-none-any.whl.c57747ed87261721509db19020b7431dec741af3/pex-1.2.15-py2.py3-none-any.whl/pex/bin/pex.py", line 576, in build_pex
    resolvables.extend(requirements_from_file(requirements_txt, resolver_option_builder))
  File "/home/name/.pex/install/pex-1.2.15-py2.py3-none-any.whl.c57747ed87261721509db19020b7431dec741af3/pex-1.2.15-py2.py3-none-any.whl/pex/requirements.py", line 98, in requirements_from_file
    return requirements_from_lines(fp.readlines(), builder=builder, relpath=relpath)
  File "/home/name/.pex/install/pex-1.2.15-py2.py3-none-any.whl.c57747ed87261721509db19020b7431dec741af3/pex-1.2.15-py2.py3-none-any.whl/pex/requirements.py", line 82, in requirements_from_lines
    raise UnsupportedLine('Could not resolve line: %s (%s)' % (resolvable, e))
pex.requirements.UnsupportedLine: Could not resolve line: git+https://github.com/Blosc/python-blosc.git#egg=blosc (Unknown requirement type: git+https://github.com/Blosc/python-blosc.git#egg=blosc)
```

Is this a desired feature of pex? Am I doing something wrong?

Thanks!

**Comment by jcrowgey** [comment]
+1

**Comment by kevinkjt2000** [comment]
This would help out tremendously!  Sometimes it is necessary to install from a git version of a package until a release is made available.  Even worse, when a package is abandoned and it takes weeks to get control over it.

**Comment by TheoLechemia** [comment]
+1

**Comment by jsirois** [comment]
I think like for #429 a PR implementing this support would be welcome.

**Comment by jaraco** [comment]
Today I wanted to test [this branch of importlib_metadata](https://gitlab.com/python-devs/importlib_metadata/tree/feature/find-local-distribution) against pex, but couldn't readily due to this issue. I'd love to see this.
