### ISSUE TITLE
AttributeError: 'UUID' object has no attribute 'get_hex'

### ISSUE THREAD

**Issue by LeMeteore** [pantsbuild/pex#56]
Was trying to follow the [pex introduction](https://www.youtube.com/watch?v=NmpnGhRwsu0), and after the ```$ pex -r flask -p flask.pex``` I had an exception:
```
Traceback (most recent call last):
  File "/home/nsukami/envs/pex/bin/pex", line 11, in <module>
    sys.exit(main())
  File "/home/nsukami/envs/pex/lib/python3.4/site-packages/pex/bin/pex.py", line 310, in main
    pex_builder = build_pex(args, options)
  File "/home/nsukami/envs/pex/lib/python3.4/site-packages/pex/bin/pex.py", line 277, in build_pex
    platform=options.platform)
  File "/home/nsukami/envs/pex/lib/python3.4/site-packages/pex/resolver.py", line 110, in resolve
    new_requirements.update(requires(highest_package, requirement))
  File "/home/nsukami/envs/pex/lib/python3.4/site-packages/pex/resolver.py", line 82, in requires
    dist = obtainer.obtain(package)
  File "/home/nsukami/envs/pex/lib/python3.4/site-packages/pex/obtainer.py", line 156, in obtain
    dist = super(CachingObtainer, self).obtain(req_or_package)
  File "/home/nsukami/envs/pex/lib/python3.4/site-packages/pex/obtainer.py", line 106, in obtain
    return self._translate_from([req_or_package])
  File "/home/nsukami/envs/pex/lib/python3.4/site-packages/pex/obtainer.py", line 94, in _translate_from
    dist = self._translator.translate(package)
  File "/home/nsukami/envs/pex/lib/python3.4/site-packages/pex/translator.py", line 43, in translate
    dist = tx.translate(package)
  File "/home/nsukami/envs/pex/lib/python3.4/site-packages/pex/translator.py", line 112, in translate
    target_path_tmp = target_path + uuid4().get_hex()
AttributeError: 'UUID' object has no attribute 'get_hex'

```
This is my virtualenv:
```
 > pip list
pex (0.7.0)
pip (1.5.6)
setuptools (3.6)
twitter.common.python (0.7.0)
wheel (0.24.0)
```
Thanks for any suggestions on how to fix this.

**Comment by wickman** [comment]
This was fixed at 3cd05640.  The 'WTF is PEX' talk is sadly out of date here -- the package has been renamed to 'pex' from 'twitter.common.python.'  If you pip uninstall twitter.common.python and pip install pex, this should be fixed.
