### ISSUE TITLE
unhandled AttributeError during pex bootstrapping with PEX_PATH

### ISSUE THREAD

**Issue by kwlzn** [pantsbuild/pex#598]
I don't have a minimal repro yet, but in some internal code that uses PEX_PATH with two other pex files that contain namespace packages we seem to be seeing the following unhandled exception on startup:

{code}
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 364, in execute
  File ".bootstrap/_pex/pex.py", line 90, in _activate
  File ".bootstrap/_pex/environment.py", line 147, in activate
  File ".bootstrap/_pex/environment.py", line 198, in _activate
  File ".bootstrap/_pex/environment.py", line 64, in update_module_paths
AttributeError: '_NamespacePath' object has no attribute 'insert'
{code}

I think this points to a setuptools version problem, but I've ensured uniform alignment across setuptools 33.1.1 with no luck.

**Comment by jsirois** [comment]
This is not a setuptools symbol, its a python 3 symbol via https://www.python.org/dev/peps/pep-0420/
On my machine, for example I find:
```
$ find /usr/lib/python{2.7,3.4,3.5,3.6,3.7}/ -type f -name "*.py" | xargs grep "class _NamespacePath"
/usr/lib/python3.4/importlib/_bootstrap.py:class _NamespacePath:
/usr/lib/python3.5/importlib/_bootstrap_external.py:class _NamespacePath:
/usr/lib/python3.6/importlib/_bootstrap_external.py:class _NamespacePath:
/usr/lib/python3.7/importlib/_bootstrap_external.py:class _NamespacePath:
```

These things become the `__path__` value only when python3-style implicit namespace packages are detected (interveining dirs with no `__init__.py`): https://www.python.org/dev/peps/pep-0420/
For normal packages, `__path__` is a plain old `list` - which has insert.

So... I think you must be running:
1. Under python3
2. In a project that purposefully (or inadvertantly?!) uses implicit namespace packages.

**Comment by jsirois** [comment]
As a small piece of the test puzzle, I have confirmed that a wheel built from:
1. An old style `pkg_resources` namespace tree
2. Using a setup.py that declares `namespace_packages`

Generates a `*nspkg.pth` file that is imported on dist activation, from which new style `_NamespacePath`.

**Comment by kwlzn** [comment]
> So... I think you must be running:
>
> Under python3
> In a project that purposefully (or inadvertantly?!) uses implicit namespace packages.

sorry for the late response - been swamped this week and just noticed your response. indeed we're running under python3 and for the latter definitely inadvertently - I saw this choke on both `google` and `mpl_toolkits` related handling.

here's a snippit w/ debug logging (sorry, I meant to include this when circling back w/ a repro):

```
pex: PEX is not zip safe, exploding to /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0
pex: Adding to the head of sys.path: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0
pex: Adding to the head of encodings.__path__: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0/encodings
pex: Adding to the head of collections.__path__: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0/collections
pex: Adding to the head of importlib.__path__: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0/importlib
pex: Adding to the head of _pex.__path__: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0/_pex
pex: Adding to the head of ctypes.__path__: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0/ctypes
pex: Adding to the head of ctypes.macholib.__path__: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0/ctypes/macholib
pex: Adding to the head of urllib.__path__: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0/urllib
pex: Adding to the head of email.__path__: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0/email
pex: Adding to the head of http.__path__: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0/http
pex: Adding to the head of pkg_resources.__path__: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0/pkg_resources
pex: Adding to the head of xml.__path__: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0/xml
pex: Adding to the head of xml.parsers.__path__: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0/xml/parsers
pex: Adding to the head of pkg_resources.extern.__path__: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0/pkg_resources/extern
pex: Adding to the head of pkg_resources._vendor.__path__: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0/pkg_resources/_vendor
pex: Adding to the head of pkg_resources._vendor.packaging.__path__: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0/pkg_resources/extern/packaging
pex: Adding to the head of distutils.__path__: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0/distutils
pex: Adding to the head of logging.__path__: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0/logging
pex: Adding to the head of json.__path__: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0/json
pex: Adding to the head of mpl_toolkits.__path__: /Users/kwilson/.pex/code/3abed9b0e11a4a550f42f3de7c47d7987a659cd0/mpl_toolkits
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 364, in execute
  File ".bootstrap/_pex/pex.py", line 90, in _activate
  File ".bootstrap/_pex/environment.py", line 147, in activate
  File ".bootstrap/_pex/environment.py", line 198, in _activate
  File ".bootstrap/_pex/environment.py", line 64, in update_module_paths
AttributeError: '_NamespacePath' object has no attribute 'insert'
```

the only reference to `mpl_toolkits` I found comes from `matplotlib` - which declares a conditional implicit namespace package: https://github.com/matplotlib/matplotlib/blob/2eb26ee356d908f5eb31282e077c264ff759be76/lib/mpl_toolkits/__init__.py

**Comment by kwlzn** [comment]
here's a minimal repro (using an older pex36 release, but should still be helpful):

```
[omerta show]$ pex36 matplotlib==2.0.2 -o matplotlib.pex --not-zip-safe
[omerta show]$ pex36 requests -o requests.pex --not-zip-safe
[omerta show]$ pex36 flask -o flask.pex --not-zip-safe
[omerta show]$ PEX_PATH=./matplotlib.pex:./requests.pex ./flask.pex
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 359, in execute
  File ".bootstrap/_pex/pex.py", line 87, in _activate
  File ".bootstrap/_pex/environment.py", line 135, in activate
  File ".bootstrap/_pex/environment.py", line 182, in _activate
  File ".bootstrap/_pex/environment.py", line 63, in update_module_paths
AttributeError: '_NamespacePath' object has no attribute 'insert'
```

the odd bit to me here is the exact repro requirement - passing only a singular pex on `PEX_PATH` does not repro:

```
[omerta show]$ PEX_PATH=./matplotlib.pex ./flask.pex
Python 3.6.0 (default, Feb 13 2017, 11:02:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> 
now exiting InteractiveConsole...
```

**Comment by jsirois** [comment]
Thanks Chris! Yeah, so all that is needed:
1. runtime is python3.5+
2. an item on the pex path contains a distribution with namespace packages
3. a later item on the pex path is not zip-safe

1. puts implicit namespace packages in play
2. gets `_NamespacePath` namespace package `__path__`'s installed in one or more `sys.modules` - and this doesn't actually require implicit namespaces, just a dist_info with `namespace_packages.txt`.
3. triggers the pex explode code that assumes `__path__` is a list with an insert method.

We have:
```
$ unzip -qc matplotlib-2.0.2-cp36-cp36m-manylinux1_x86_64.whl matplotlib-2.0.2.dist-info/namespace_packages.txt
mpl_toolkits
mpl_toolkits
```
As such, the example can be shrunk to:
```
$ ./dist/pex36 matplotlib==2.0.2 -o matplotlib.pex
$ ./dist/pex36 requests -o requests.pex --not-zip-safe
$ PEX_PATH=requests.pex ./matplotlib.pex 
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 349, in execute
  File ".bootstrap/_pex/pex.py", line 90, in _activate
  File ".bootstrap/_pex/environment.py", line 174, in activate
  File ".bootstrap/_pex/environment.py", line 229, in _activate
  File ".bootstrap/_pex/environment.py", line 86, in update_module_paths
AttributeError: '_NamespacePath' object has no attribute 'insert'
```

**Comment by jsirois** [comment]
Super compact:
```
$ ./dist/pex36 twitter.common.lang==0.3.9 -o tcl.pex

**Comment by jsirois** [comment]
Noting some problems that make it hard to test the failing code, whose intent is to ensure any namespace package with components internal to a zipped pex are subsequently imported from the exploded zip contents:

1. `load_internal_cache`, which is called 1st in the PEXEnvironment activation process, unpacks all pex `.deps/` to disk, leaving only the loose source in a zipped pex o be `__path__` adjusted by the original code.
2. Loose code added to a pex (via `PEXBuilder`) w/o `__init__.py` has them automatically added by `_prepare_inits` - as such new-style implicit namespace packages in PEX loose sources are impossible today.
3. There is a bug in `PEXEnvironment` activation where new style implicit `_NamespacePath` namespace packages are wiped out by `pkg_resources`.

I do have a fix for 3 though and this allows a test for the case the broken code was attempting to handle. That case is legit! Without a fix to the broken code in this issue's backtrace (and a fix to 3) otherwise legitimate pex loose source code with namespaces that is not zip safe is in fact broken by pex.

Fixes coming...
