### ISSUE TITLE
pex 1.5.1 bombs with unhandled `pkg_resources._vendor.packaging.markers.UndefinedEnvironmentName` on certain resolves

### ISSUE THREAD

**Issue by kwlzn** [pantsbuild/pex#615]
repro:

```
[omerta show]$ wget -q https://github.com/pantsbuild/pex/releases/download/v1.5.1/pex27 -O pex27-1.5.1
[omerta show]$ ./pex27-1.5.1 apache-beam[gcp]==2.7.0
Traceback (most recent call last):
  File "/private/var/folders/kd/k5b__qgs0gl5yzp48gctmhz80000gn/T/tmp_XY7Uj/.bootstrap/_pex/pex.py", line 349, in execute
    working_set = self._activate()
  File "/private/var/folders/kd/k5b__qgs0gl5yzp48gctmhz80000gn/T/tmp_XY7Uj/.bootstrap/_pex/pex.py", line 90, in _activate
    for dist in env.activate():
  File "/private/var/folders/kd/k5b__qgs0gl5yzp48gctmhz80000gn/T/tmp_XY7Uj/.bootstrap/_pex/environment.py", line 152, in activate
    self._working_set = self._activate()
  File "/private/var/folders/kd/k5b__qgs0gl5yzp48gctmhz80000gn/T/tmp_XY7Uj/.bootstrap/_pex/environment.py", line 211, in _activate
    resolved = self._resolve(working_set, all_reqs)
  File "/private/var/folders/kd/k5b__qgs0gl5yzp48gctmhz80000gn/T/tmp_XY7Uj/.bootstrap/_pex/environment.py", line 165, in _resolve
    if req.marker and not req.marker.evaluate(environment=self._target_interpreter_env):
  File "/private/var/folders/kd/k5b__qgs0gl5yzp48gctmhz80000gn/T/tmp_XY7Uj/.bootstrap/pkg_resources/_vendor/packaging/markers.py", line 301, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/private/var/folders/kd/k5b__qgs0gl5yzp48gctmhz80000gn/T/tmp_XY7Uj/.bootstrap/pkg_resources/_vendor/packaging/markers.py", line 226, in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
  File "/private/var/folders/kd/k5b__qgs0gl5yzp48gctmhz80000gn/T/tmp_XY7Uj/.bootstrap/pkg_resources/_vendor/packaging/markers.py", line 208, in _get_env
    "{0!r} does not exist in evaluation environment.".format(name)
pkg_resources._vendor.packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.
```

vs 1.4.4:

```
[omerta show]$ wget -q https://github.com/pantsbuild/pex/releases/download/v1.4.4/pex27 -O pex27-1.4.4
[omerta show]$ ./pex27-1.4.4 apache-beam[gcp]==2.7.0
Python 2.7.15 (default, Jun 20 2018, 17:40:09) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> 
```

**Comment by kwlzn** [comment]
noting the shape of the markers in the failure case is (from the apache-beam wheel):

```
Provides-Extra: gcp
Requires-Dist: google-apitools (<=0.5.20,>=0.5.18); extra == 'gcp'
Requires-Dist: proto-google-cloud-datastore-v1 (<=0.90.4,>=0.90.0); extra == 'gcp'
Requires-Dist: googledatastore (==7.0.1); extra == 'gcp'
Requires-Dist: google-cloud-pubsub (==0.26.0); extra == 'gcp'
Requires-Dist: proto-google-cloud-pubsub-v1 (==0.15.4); extra == 'gcp'
Requires-Dist: google-cloud-bigquery (==0.25.0); extra == 'gcp'
```

**Comment by jsirois** [comment]
OK - thanks for the report. Easy repro and the fix appears to be tiny.

**Comment by jsirois** [comment]
The bug is not on the resolution side, but in the activation side where we filter out embedded dists not appropriate to the current enviornment the pex is running in.

**Comment by jsirois** [comment]
Opps - wrong re-open.
