### ISSUE TITLE
joblib not found when Parallel is executed inside a pex

### ISSUE THREAD

**Issue by yetanotherion** [pantsbuild/pex#675]
Posted at https://github.com/joblib/joblib/issues/849 too.
Don't know whether it's a bug in pex or joblib yet.
TL;DR: `joblib.Parallel` raises an exception inside a pex, even though `from joblib import Parallel` runs fine.
The script below reproduces the issue
```bash
#!/bin/bash
python3.6 -m venv .
. bin/activate
# gets pip 19.0.3
pip install --upgrade pip
pip install pex
pex joblib -o ./pex
cat <<EOF > test.py
from joblib import Parallel, delayed

def func(k):
    return k

jobs = (delayed(func)(k) for k in range(2))
print(Parallel(n_jobs=2)(jobs))

EOF
deactivate
./pex test.py
```
Additional information is available at https://github.com/joblib/joblib/issues/849.

**Comment by jsirois** [comment]
The problem seems to lie here:
https://github.com/joblib/joblib/blob/a99273bb0fe1d77c5e5b1b5512c6a9fa1285a125/joblib/externals/loky/backend/popen_loky_posix.py#L144-L155

Worker processes are spawned using sys.executable but sys.path is not passed on (e.g. via altering the PYTHONPATH via os.execve - instead os.execv is used). Since a pex alters the sys.path at runtime (on boot) instead of using the standard sys.executable sys.path construction - this leads to the problem you observe of spawned jobs not being able to find the dependencies contained within the original pex.

If I hand-hack popen_loky_posix.py to `os.environ['PYTHONPATH'] = os.pathsep.join(sys.path)` before calling `fork_exec` in the snippet pointed to above, ie:
```diff
$ diff /home/jsirois/.pex/install/joblib-0.13.2-py2.py3-none-any.whl.71f5159401747e872566d2974ae0d2afcc42332d/joblib-0.13.2-py2.py3-none-any.whl/joblib/externals/loky/backend/popen_loky_posix.py.orig /home/jsirois/.pex/install/joblib-0.13.2-py2.py3-none-any.whl.71f5159401747e872566d2974ae0d2afcc42332d/joblib-0.13.2-py2.py3-none-any.whl/joblib/externals/loky/backend/popen_loky_posix.py
143c143
< 
---
>                 os.environ['PYTHONPATH'] = os.pathsep.join(sys.path)
```

I then get partial success:
```
$ ./joblib.pex test.py 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'joblib'
[0, 1]
$ Traceback (most recent call last):
  File "/home/jsirois/.pex/install/joblib-0.13.2-py2.py3-none-any.whl.71f5159401747e872566d2974ae0d2afcc42332d/joblib-0.13.2-py2.py3-none-any.whl/joblib/externals/loky/backend/semaphore_tracker.py", line 177, in main
    cache.remove(name)
KeyError: '/loky-458-ends8ioi'
Traceback (most recent call last):
  File "/home/jsirois/.pex/install/joblib-0.13.2-py2.py3-none-any.whl.71f5159401747e872566d2974ae0d2afcc42332d/joblib-0.13.2-py2.py3-none-any.whl/joblib/externals/loky/backend/semaphore_tracker.py", line 177, in main
    cache.remove(name)
KeyError: '/loky-458-4l8crg7s'
Traceback (most recent call last):
  File "/home/jsirois/.pex/install/joblib-0.13.2-py2.py3-none-any.whl.71f5159401747e872566d2974ae0d2afcc42332d/joblib-0.13.2-py2.py3-none-any.whl/joblib/externals/loky/backend/semaphore_tracker.py", line 177, in main
    cache.remove(name)
KeyError: '/loky-458-9cpw4xj7'
Traceback (most recent call last):
  File "/home/jsirois/.pex/install/joblib-0.13.2-py2.py3-none-any.whl.71f5159401747e872566d2974ae0d2afcc42332d/joblib-0.13.2-py2.py3-none-any.whl/joblib/externals/loky/backend/semaphore_tracker.py", line 177, in main
    cache.remove(name)
KeyError: '/loky-458-3obo797i'
Traceback (most recent call last):
  File "/home/jsirois/.pex/install/joblib-0.13.2-py2.py3-none-any.whl.71f5159401747e872566d2974ae0d2afcc42332d/joblib-0.13.2-py2.py3-none-any.whl/joblib/externals/loky/backend/semaphore_tracker.py", line 177, in main
    cache.remove(name)
KeyError: '/loky-458-1sqj6w_a'
Traceback (most recent call last):
  File "/home/jsirois/.pex/install/joblib-0.13.2-py2.py3-none-any.whl.71f5159401747e872566d2974ae0d2afcc42332d/joblib-0.13.2-py2.py3-none-any.whl/joblib/externals/loky/backend/semaphore_tracker.py", line 177, in main
    cache.remove(name)
KeyError: '/loky-458-gogv0s97'
Traceback (most recent call last):
  File "/home/jsirois/.pex/install/joblib-0.13.2-py2.py3-none-any.whl.71f5159401747e872566d2974ae0d2afcc42332d/joblib-0.13.2-py2.py3-none-any.whl/joblib/externals/loky/backend/semaphore_tracker.py", line 177, in main
    cache.remove(name)
KeyError: '/loky-458-0hslf3eo'
Traceback (most recent call last):
  File "/home/jsirois/.pex/install/joblib-0.13.2-py2.py3-none-any.whl.71f5159401747e872566d2974ae0d2afcc42332d/joblib-0.13.2-py2.py3-none-any.whl/joblib/externals/loky/backend/semaphore_tracker.py", line 177, in main
    cache.remove(name)
KeyError: '/loky-458-dl1yj41e'

$ echo $?
0
```

It's not clear to me there is any way to both keep the principles of pex - a hermetic python execution enviornment contained in a single file - and still have it work in situations like these. I have not put the joblib/loky hats on and thought hard about whether taking efforts to pass on sys.path explicitly to spawned python processes makes sense, but after this quick investigation it seems like the right way to go here.

**Comment by jsirois** [comment]
I'm going to close this as answered, but feel free to re-open with further ideas or if you find the failure explanation wanting.

**Comment by jsirois** [comment]
To further drive towards this being an issue with the way loky sets up its subprocess workers, I've modified your sample so that it can work with the multiprocessing backend.

test.sh:
```bash 
#!/bin/bash
python3.6 -m venv .
. bin/activate
pip -q install --upgrade pip pex
cat <<EOF > func.py
def func(k):
    return k

EOF
cat <<EOF > test.py
import sys

from joblib import Parallel, delayed

from func import func

backend = sys.argv[1] if len(sys.argv) == 2 else 'loky'
jobs = (delayed(func)(k) for k in range(2))
print(f'Launching parallel with backend {backend}')
print(Parallel(n_jobs=2, backend=backend)(jobs))

EOF
pex -D . -m test joblib -o ./pex
deactivate
./pex "$@"
```

Using the default `loky` backend:
```
$ ./test.sh 
Launching parallel with backend loky
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'joblib'
/usr/bin/python3.6: Error while finding module specification for 'joblib.externals.loky.backend.popen_loky_posix' (ModuleNotFoundError: No module named 'joblib')
/home/jsirois/.pex/install/joblib-0.13.2-py2.py3-none-any.whl.71f5159401747e872566d2974ae0d2afcc42332d/joblib-0.13.2-py2.py3-none-any.whl/joblib/externals/loky/backend/semaphore_tracker.py:74: UserWarning: semaphore_tracker: process died unexpectedly, relaunching.  Some semaphores might leak.
  warnings.warn('semaphore_tracker: process died unexpectedly, '
Traceback (most recent call last):
  File ".bootstrap/pex/pex.py", line 352, in execute
  File ".bootstrap/pex/pex.py", line 284, in _wrap_coverage
  File ".bootstrap/pex/pex.py", line 315, in _wrap_profiling
  File ".bootstrap/pex/pex.py", line 397, in _execute
  File ".bootstrap/pex/pex.py", line 495, in execute_entry
  File ".bootstrap/pex/pex.py", line 502, in execute_module
  File "/usr/lib/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "test.py", line 10, in <module>
    print(Parallel(n_jobs=2, backend=backend)(jobs))
  File "/home/jsirois/.pex/install/joblib-0.13.2-py2.py3-none-any.whl.71f5159401747e872566d2974ae0d2afcc42332d/joblib-0.13.2-py2.py3-none-any.whl/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/home/jsirois/.pex/install/joblib-0.13.2-py2.py3-none-any.whl.71f5159401747e872566d2974ae0d2afcc42332d/joblib-0.13.2-py2.py3-none-any.whl/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/jsirois/.pex/install/joblib-0.13.2-py2.py3-none-any.whl.71f5159401747e872566d2974ae0d2afcc42332d/joblib-0.13.2-py2.py3-none-any.whl/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {EXIT(1)}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'joblib'
```

And using `multiprocessing`:
```
$ ./test.sh multiprocessing
Launching parallel with backend multiprocessing
[0, 1]
```

This should be pinpointed enough to help push https://github.com/joblib/joblib/issues/849 where it needs to go.

**Comment by yetanotherion** [comment]
Thanks for these very precious informations. I'll continue in https://github.com/joblib/joblib/issues/849, as you've proven the bug is not in pex.

**Comment by jsirois** [comment]
@yetanotherion there was just activity on https://github.com/joblib/joblib/issues/849 which prompted my attention here again. Since you reported Pex has grown a `--venv` mode of execution that is generally more compatible with more libraries.

To whit, your OP with the sole change of `--venv` added to the PEX creation line:
```bash
#!/bin/bash
python3.6 -m venv .
. bin/activate
# gets pip 19.0.3
pip install --upgrade pip
pip install pex
pex joblib -o ./pex --venv
cat <<EOF > test.py
from joblib import Parallel, delayed

def func(k):
    return k

jobs = (delayed(func)(k) for k in range(2))
print(Parallel(n_jobs=2)(jobs))

EOF
deactivate
./pex test.py
```

Yields:
```console
$ chmod +x test.sh
$ ./test.sh
Collecting pip
  Downloading https://files.pythonhosted.org/packages/a4/6d/6463d49a933f547439d6b5b98b46af8742cc03ae83543e4d7688c2420f8b/pip-21.3.1-py3-none-any.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 8.6MB/s
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-21.3.1
Collecting pex
  Using cached pex-2.1.129-py2.py3-none-any.whl (2.9 MB)
Installing collected packages: pex
Successfully installed pex-2.1.129
[0, 1]
```
