### ISSUE TITLE
pex 1.5.3 -> 1.6.0 introduces pkg_resources() error at import time

### ISSUE THREAD

**Issue by cosmicexplorer** [pantsbuild/pex#729]
Gist with repro information: https://gist.github.com/cosmicexplorer/e6908a1af816351944a4584e1db7f89c. pantsbuild/pants#7695 was created to work around this issue we found with importing requirements that depended on setuptools at install time, but after bisecting the failure in that PR to have been introduced in https://github.com/pantsbuild/pants/commit/4dafc870ece338be7bbba4e44ee1e416e27e9afb, I ended up quickly finding that just changing the pex version was causing the error at import time described in pantsbuild/pants#7695. I've been reviewing the pex git history from 1.5.3 -> 1.6.0, but haven't been able to find what caused this behavior change yet.

**Comment by cosmicexplorer** [comment]
Talked with @Eric-Arellano and this is apparently probably because of the vendoring in #624. The stack trace in the errors from pantsbuild/pants#7695 show an error in a version of setuptools which I suspect is because it's not using the vendored setuptools which are available at build time. Vaguely, the strategy would seem to be to use the vendored setuptools at runtime too, but I can't figure out how to do that -- I'm assuming it will invoke some pex changes right now.

**Comment by cosmicexplorer** [comment]
Ok, managed to get pex running from source and the repro above is actually fixed after making this change:
```diff
diff --git a/pex/pex_builder.py b/pex/pex_builder.py
index 0e6ba3a..86f729c 100644
--- a/pex/pex_builder.py
+++ b/pex/pex_builder.py
@@ -41,7 +41,7 @@ if __entry_point__ is None:
 sys.path[0] = os.path.abspath(sys.path[0])
 sys.path.insert(0, os.path.abspath(os.path.join(__entry_point__, {bootstrap_dir!r})))

-from pex.third_party import VendorImporter
+from pex.third_party import VendorImporter, install as install_vendored
 VendorImporter.install(uninstallable=False,
                        prefix={legacy_bootstrap_pkg!r},
                        path_items=['pex'],
@@ -49,6 +49,8 @@ VendorImporter.install(uninstallable=False,
                                'package is deprecated and will be removed in pex 2.0.0. Please '
                                'switch to the `pex` package for runtime API access.')

+install_vendored(expose=['setuptools'])
+
 from pex.pex_bootstrapper import bootstrap_pex
 bootstrap_pex(__entry_point__)
 """.format(bootstrap_dir=BOOTSTRAP_DIR, legacy_bootstrap_pkg=LEGACY_BOOSTRAP_PKG)
```

This mostly makes sense, I think. I'm looking into how `google-cloud-bigquery` interacts with setuptools in the first place to see what the appropriate change to make here is.

**Comment by cosmicexplorer** [comment]
Ok, managed to get a repro without involving pants:
```
> # creating the file `pex/aaa/bigquery_print.py` as below...
> ls pex/aaa
total 4.1k
-rw-r--r-- 1 dmcclanahan staff 94 May 11 15:09 bigquery_print.py
> cat pex/aaa/bigquery_print.py
from google.cloud import bigquery

print('bigquery version: {}'.format(bigquery.__version__))
> tox -e py27-run -- google-cloud-bigquery==1.10.0 -o goog.pex && tox -e py27-run -- 'pytest>=3.4,<4.0' -o pytest.pex && tox -e py27-run -- --pex-path="$(pwd)/pytest.pex:$(pwd)/goog.pex" -D pex/aaa --entry-point bigquery_print
...output...
Traceback (most recent call last):
  File "/private/var/folders/l_/3k9sqfqn5_z5v1zbxgrnxtyh0000gn/T/tmpX0o4uE/.bootstrap/pex/pex.py", line 352, in execute
    exit_code = self._wrap_coverage(self._wrap_profiling, self._execute)
  File "/private/var/folders/l_/3k9sqfqn5_z5v1zbxgrnxtyh0000gn/T/tmpX0o4uE/.bootstrap/pex/pex.py", line 284, in _wrap_coverage
    return runner(*args)
  File "/private/var/folders/l_/3k9sqfqn5_z5v1zbxgrnxtyh0000gn/T/tmpX0o4uE/.bootstrap/pex/pex.py", line 315, in _wrap_profiling
    return runner(*args)
  File "/private/var/folders/l_/3k9sqfqn5_z5v1zbxgrnxtyh0000gn/T/tmpX0o4uE/.bootstrap/pex/pex.py", line 397, in _execute
    return self.execute_entry(self._pex_info.entry_point)
  File "/private/var/folders/l_/3k9sqfqn5_z5v1zbxgrnxtyh0000gn/T/tmpX0o4uE/.bootstrap/pex/pex.py", line 495, in execute_entry
    return runner(entry_point)
  File "/private/var/folders/l_/3k9sqfqn5_z5v1zbxgrnxtyh0000gn/T/tmpX0o4uE/.bootstrap/pex/pex.py", line 502, in execute_module
    runpy.run_module(module_name, run_name='__main__')
  File "/opt/twitter_mde/package/eepython27/e4cdee382b83e4185a42b54120b1b11021cec1d8285cc9023ef2dabf8c9af24d/lib/python2.7/runpy.py", line 192, in run_module
    fname, loader, pkg_name)
  File "/opt/twitter_mde/package/eepython27/e4cdee382b83e4185a42b54120b1b11021cec1d8285cc9023ef2dabf8c9af24d/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/private/var/folders/l_/3k9sqfqn5_z5v1zbxgrnxtyh0000gn/T/tmpX0o4uE/bigquery_print.py", line 1, in <module>
    from google.cloud import bigquery
  File "/Users/dmcclanahan/.pex/install/google_cloud_bigquery-1.10.0-py2.py3-none-any.whl.e29583692511e990b985694010d762329f3e867a/google_cloud_bigquery-1.10.0-py2.py3-none-any.whl/google/cloud/bigquery/__init__.py", line 33, in <module>
    __version__ = get_distribution("google-cloud-bigquery").version
  File "/Users/dmcclanahan/.pex/install/setuptools-41.0.1-py2.py3-none-any.whl.ffa66c57fd90eee9c21efeb1d3d918a7b960fa4f/setuptools-41.0.1-py2.py3-none-any.whl/pkg_resources/__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "/Users/dmcclanahan/.pex/install/setuptools-41.0.1-py2.py3-none-any.whl.ffa66c57fd90eee9c21efeb1d3d918a7b960fa4f/setuptools-41.0.1-py2.py3-none-any.whl/pkg_resources/__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/Users/dmcclanahan/.pex/install/setuptools-41.0.1-py2.py3-none-any.whl.ffa66c57fd90eee9c21efeb1d3d918a7b960fa4f/setuptools-41.0.1-py2.py3-none-any.whl/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/dmcclanahan/.pex/install/setuptools-41.0.1-py2.py3-none-any.whl.ffa66c57fd90eee9c21efeb1d3d918a7b960fa4f/setuptools-41.0.1-py2.py3-none-any.whl/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'google-cloud-bigquery' distribution was not found and is required by the application
```

Then after applying the diff in https://github.com/pantsbuild/pex/issues/729#issuecomment-491545479, it succeeds and prints `bigquery version: 1.10.0`.

I'm currently looking to see whether/how we can register the distributions that we have in the pex vendored setuptools with the setuptools version in the stack trace.

**Comment by cosmicexplorer** [comment]
#730 fixed this!
