### ISSUE TITLE
Prevent create files on PEX ROOT as root when pex file is run with sudo

### ISSUE THREAD

**Issue by carlosduelo** [pantsbuild/pex#816]
Run a pex with sudo the first time:

```
sudo my-pex.pex
```
It creates files under in my HOME `~/.pex/install/` with root as owner, 

```
$ ls -la ~/.pex/install/
total 0
drwxr-xr-x 1 root   root   3818 Nov 28 17:03 .
drwxrwxr-x 1 user user   14 Nov 28 17:03 ..
drwxr-xr-x 1 root   root     76 Nov 28 17:03 attrs-19.3.0-py2.py3-none-any.whl.e91da08a7091c46772d87f0c961a63ac85d4a810
drwxr-xr-x 1 root   root     82 Nov 28 17:03 requests-2.22.0-py2.py3-none-any.whl.9523c112783d316b50f5bfd5d4bcad40736336aa
.........
```

Later when the same pex is run without sudo it produces `PermissionError`

```
Traceback (most recent call last):
  File "/usr/bin/my-pex.pex/.bootstrap/pex/pex.py", line 395, in execute
  File "/usr/bin/my-pex.pex/.bootstrap/pex/pex.py", line 93, in _activate
  File "/usr/bin/my-pex.pex/.bootstrap/pex/environment.py", line 249, in activate
  File "/usr/bin/my-pex.pex/.bootstrap/pex/environment.py", line 357, in _activate
  File "/usr/bin/my-pex.pex/.bootstrap/pex/environment.py", line 238, in _update_candidate_distributions
  File "/usr/bin/my-pex.pex/.bootstrap/pex/environment.py", line 203, in _load_internal_cache
  File "/usr/bin/my-pex.pex/.bootstrap/pex/environment.py", line 190, in _write_zipped_internal_cache
  File "/usr/bin/my-pex.pex/.bootstrap/pex/util.py", line 166, in cache_distribution
  File "/usr/lib/python3.7/zipfile.py", line 1599, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/bin/my-pex.pex/.bootstrap/pex/common.py", line 121, in _extract_member
  File "/usr/lib/python3.7/zipfile.py", line 1662, in _extract_member
    os.makedirs(upperdirs)
  File "/usr/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/user/.pex/install/pyrsistent-0.15.6-cp37-cp37m-linux_x86_64.whl.5e52dba7dab3ea7ab9594ad73326d31baf150835.a8407da79a3145ad8d2ed53f8f654852'
```
Maybe this files can be created with the real user ownership

**Comment by jsirois** [comment]
@carlosduelo I don't think Pex ever wants to learn sudo, ie check for:
```
$ sudo /usr/bin/env | grep SUDO_
SUDO_COMMAND=/usr/bin/env
SUDO_USER=jsirois
SUDO_UID=1000
SUDO_GID=1000
```
There is a can of worms here. If the user did intend to run with sudo then ..., etc.

#929 provides the best relief I can think of, which is to warn when pex can't write to PEX_ROOT (~/.pex by default) and instead write to a temporary directory. WIth this feature, pex will now work in the scenario you describe, but like so:
```
$ ./dist/pex --pex-root=/root/.pex -o empty.pex
/home/jsirois/.pex/installed_wheels/0038e7d1e7d68a69b212b2cbe3915b17a83355b7/pex-2.1.6-py2.py3-none-any.whl/pex/variables.py:281: PEXWarning: PEX_ROOT is configured as /root/.pex but that path is un-writeable, falling back to a temporary PEX_ROOT of /tmp/tmpk4mwqwvn which will hurt performance.
  pex_warnings.warn('PEX_ROOT is configured as {pex_root} but that path is un-writeable, '
```

So, your PEX will run with a bit worse performance and you'll get a warning about the problem. You still have to clean up your `~/.pex` dir, but hopefully this helps.
