### ISSUE TITLE
PEX 2.1.0 regression: pex file won't build inside a running docker image as user

### ISSUE THREAD

**Issue by struegamer** [pantsbuild/pex#850]
Good Day,

first of all, thanks for your good work on `pex`, we use it in our daily work, and it's a great tool to deliver single file python app distributions.

Sadly, when updating our build images, we encountered a new issue with pex 2.1.0 release.

Given this `Dockerfile`:

```
FROM ubuntu:18.04

ARG user=jenkins
ARG group=jenkins
ARG uid=10000
ARG gid=10000
ARG AGENT_WORKDIR=/home/${user}/agent

ENV HOME /home/${user}
ENV AGENT_WORKDIR=${AGENT_WORKDIR}

RUN apt -y update && \
  apt -y --no-install-recommends install python3 python3-pip python3-distutils \
    python3-distutils-extra python3-venv git \
    python3-setuptools python3-requests \
    openssh-client build-essential libpython3-dev && \
    pip3 install pex && \
    groupadd -g ${gid} ${group} && useradd -c "Jenkins user" -d /home/${user} -u ${uid} -g ${gid} -m ${user} && \
    mkdir /home/${user}/.jenkins && mkdir -p ${AGENT_WORKDIR} && chown -R ${uid}:${gid} /home/${user}

VOLUME /home/${user}/.jenkins
VOLUME ${AGENT_WORKDIR}
```
you can create a stripped down build image, as we are running in our environment, i.e. 

```
docker build -t py-pex-test:foo .
```

Now, when created, execute the image like this:

```
docker run -ti -u jenkins py-pex-test:foo bash
```

and inside the running image execute `pex` like this:

```
pex -vvv --disable-cache -o black.pex -c black black
```

Now you will see the following error message:

```
jenkins@b922415fef8e:/$ pex -vvv --disable-cache -o black -c black black
pex: Building pex :: Resolving distributions (['black']) :: Resolving for:
Traceback (most recent call last):ex to /home/jenkins/.pex/isolated/0edff9f980790256c0e238e65ccca12cffa9085b
  File "/usr/local/bin/pex", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pex/bin/pex.py", line 662, in main
    pex_builder = build_pex(reqs, options)
  File "/usr/local/lib/python3.6/dist-packages/pex/bin/pex.py", line 594, in build_pex
    ignore_errors=options.ignore_errors)
  File "/usr/local/lib/python3.6/dist-packages/pex/resolver.py", line 778, in resolve_multi
    return list(resolve_request.resolve_distributions(ignore_errors=ignore_errors))
  File "/usr/local/lib/python3.6/dist-packages/pex/resolver.py", line 490, in resolve_distributions
    raise_type=Unsatisfiable):
  File "/usr/local/lib/python3.6/dist-packages/pex/resolver.py", line 363, in _run_parallel
    for result in execute_parallel(self._max_parallel_jobs, inputs, spawn_func, raise_type):
  File "/usr/local/lib/python3.6/dist-packages/pex/jobs.py", line 228, in execute_parallel
    raise error
  File "/usr/local/lib/python3.6/dist-packages/pex/jobs.py", line 211, in spawn_jobs
    resut = spawn_func(item)
  File "/usr/local/lib/python3.6/dist-packages/pex/resolver.py", line 368, in _spawn_resolve
    download_job = get_pip().spawn_download_distributions(
  File "/usr/local/lib/python3.6/dist-packages/pex/pip.py", line 243, in get_pip
    _PIP = Pip.create()
  File "/usr/local/lib/python3.6/dist-packages/pex/pip.py", line 29, in create
    isolated_pip_environment = third_party.pkg_resources.Environment(search_path=pythonpath)
  File "/usr/local/lib/python3.6/dist-packages/pex/vendor/_vendored/setuptools/pkg_resources/__init__.py", line 1016, in __init__
    self.scan(search_path)
  File "/usr/local/lib/python3.6/dist-packages/pex/vendor/_vendored/setuptools/pkg_resources/__init__.py", line 1047, in scan
    for item in search_path:
  File "/usr/local/lib/python3.6/dist-packages/pex/third_party/__init__.py", line 436, in expose
    for path in VendorImporter.expose(dists, root=isolated()):
  File "/usr/local/lib/python3.6/dist-packages/pex/third_party/__init__.py", line 358, in isolated
    safe_copy(os.path.join(root, f), os.path.join(chroot, 'pex', relroot, f))
  File "/usr/local/lib/python3.6/dist-packages/pex/common.py", line 44, in safe_copy
    os.link(source, dest)
PermissionError: [Errno 1] Operation not permitted: '/usr/local/lib/python3.6/dist-packages/pex/pex_info.py' -> '/home/jenkins/.pex/isolated/0edff9f980790256c0e238e65ccca12cffa9085b.a62d3de2cec04d3683f8178794351eba/pex/./pex_info.py'
```

I can reproduce this everywhere.

You don't see this happening when running inside the image as default `root` user.

The path `$HOME/.pex/isolated` was created automatically, but the directory `<hash>` was not. 

This is a regression from `pex` 2.0.3, where all this worked nicely.

Any ideas how to workaround this?

Thanks for your help, and keep up the good work.

**Comment by jsirois** [comment]
@bradhowes found the fix for this in #852
