### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by wickman** [pantsbuild/pex#97]
Something must be broken with PEX_IGNORE_ERRORS

```
$ pex flask -o /tmp/flask.pex
$ PEX_PYTHON=pypy /tmp/flask.pex
Traceback (most recent call last):
  File "/tmp/flask.pex/.bootstrap/_pex/pex.py", line 311, in execute
    working_set = self._activate()
  File "/tmp/flask.pex/.bootstrap/_pex/pex.py", line 76, in _activate
    for dist in env.activate():
  File "/tmp/flask.pex/.bootstrap/_pex/environment.py", line 132, in activate
    self._working_set = self._activate()
  File "/tmp/flask.pex/.bootstrap/_pex/environment.py", line 179, in _activate
    resolved = self._resolve(working_set, all_reqs)
  File "/tmp/flask.pex/.bootstrap/_pex/environment.py", line 150, in _resolve
    reqs.remove(unresolved_req)
ValueError: list.remove(x): x not in list

```

**Comment by wickman** [comment]
This is an issue with DistributionNotFound from pkg_resources providing wonky exception arguments.  e.args[0] is the actual Requirement and e.args[1] is the set of project_names of the last hop of projects requiring e.args[0].  This means that deleting e.args[0] from the reqs will not be sufficient to prevent an infinite loop here.  I think the only way around this is to resolve one req at a time.

**Comment by Yasumoto** [comment]
I hit this same stack trace when I build a pex on OS X, but then tried to run it on linux without any linux-specific bdists included.
