### ISSUE TITLE
pex safe copy files failure

### ISSUE THREAD

**Issue by asherf** [pantsbuild/pex#984]
This happened in CI.
pants was running pex to build a requirements.pex file for a test.

```
 Process 'Building requirements.pex with 36 requirements: Django==3.0.6, ansicolors==1.1.8
```

```
                stderr:
                Traceback (most recent call last):
  File "/home/toolchain/.cache/pants/named_caches/pex_root/unzipped_pexes/5c7bc45e8fc51b4727f7d062b6d1d5e0ad0faf9d/.bootstrap/pex/pex.py", line 396, in execute
    exit_code = self._wrap_coverage(self._wrap_profiling, self._execute)
  File "/home/toolchain/.cache/pants/named_caches/pex_root/unzipped_pexes/5c7bc45e8fc51b4727f7d062b6d1d5e0ad0faf9d/.bootstrap/pex/pex.py", line 328, in _wrap_coverage
    return runner(*args)
  File "/home/toolchain/.cache/pants/named_caches/pex_root/unzipped_pexes/5c7bc45e8fc51b4727f7d062b6d1d5e0ad0faf9d/.bootstrap/pex/pex.py", line 359, in _wrap_profiling
    return runner(*args)
  File "/home/toolchain/.cache/pants/named_caches/pex_root/unzipped_pexes/5c7bc45e8fc51b4727f7d062b6d1d5e0ad0faf9d/.bootstrap/pex/pex.py", line 447, in _execute
    return self.execute_entry(self._pex_info.entry_point)
  File "/home/toolchain/.cache/pants/named_caches/pex_root/unzipped_pexes/5c7bc45e8fc51b4727f7d062b6d1d5e0ad0faf9d/.bootstrap/pex/pex.py", line 544, in execute_entry
    return runner(entry_point)
  File "/home/toolchain/.cache/pants/named_caches/pex_root/unzipped_pexes/5c7bc45e8fc51b4727f7d062b6d1d5e0ad0faf9d/.bootstrap/pex/pex.py", line 559, in execute_pkg_resources
    return runner()
  File "/home/toolchain/.cache/pants/named_caches/pex_root/unzipped_pexes/5c7bc45e8fc51b4727f7d062b6d1d5e0ad0faf9d/.deps/pex-2.1.11-py2.py3-none-any.whl/pex/bin/pex.py", line 786, in main
    pex_builder = build_pex(reqs, options, cache=ENV.PEX_ROOT)
  File "/home/toolchain/.cache/pants/named_caches/pex_root/unzipped_pexes/5c7bc45e8fc51b4727f7d062b6d1d5e0ad0faf9d/.deps/pex-2.1.11-py2.py3-none-any.whl/pex/bin/pex.py", line 711, in build_pex
    pex_builder.add_distribution(resolved_dist.distribution)
  File "/home/toolchain/.cache/pants/named_caches/pex_root/unzipped_pexes/5c7bc45e8fc51b4727f7d062b6d1d5e0ad0faf9d/.deps/pex-2.1.11-py2.py3-none-any.whl/pex/pex_builder.py", line 375, in add_distribution
    dist_hash = self._add_dist_dir(dist.location, dist_name)
  File "/home/toolchain/.cache/pants/named_caches/pex_root/unzipped_pexes/5c7bc45e8fc51b4727f7d062b6d1d5e0ad0faf9d/.deps/pex-2.1.11-py2.py3-none-any.whl/pex/pex_builder.py", line 347, in _add_dist_dir
    self._copy_or_link(filename, target)
  File "/home/toolchain/.cache/pants/named_caches/pex_root/unzipped_pexes/5c7bc45e8fc51b4727f7d062b6d1d5e0ad0faf9d/.deps/pex-2.1.11-py2.py3-none-any.whl/pex/pex_builder.py", line 434, in _copy_or_link
    self._chroot.link(src, dst, label)
  File "/home/toolchain/.cache/pants/named_caches/pex_root/unzipped_pexes/5c7bc45e8fc51b4727f7d062b6d1d5e0ad0faf9d/.deps/pex-2.1.11-py2.py3-none-any.whl/pex/common.py", line 464, in link
    safe_copy(abs_src, abs_dst, overwrite=False)
  File "/home/toolchain/.cache/pants/named_caches/pex_root/unzipped_pexes/5c7bc45e8fc51b4727f7d062b6d1d5e0ad0faf9d/.deps/pex-2.1.11-py2.py3-none-any.whl/pex/common.py", line 44, in safe_copy
    os.link(source, dest)
FileNotFoundError: [Errno 2] No such file or directory: '/home/toolchain/.cache/pants/named_caches/pex_root/installed_wheels/d0f9e0791b74e702309155afd4c9c88d564264fa/kubernetes-11.0.0-py3-none-any.whl/kubernetes/client/api/__pycache__/auditregistration_v1alpha1_api.cpython-38.pyc.140613335570880' -> '/tmp/tmpfnzzu622/.deps/kubernetes-11.0.0-py3-none-any.whl/kubernetes/client/api/__pycache__/auditregistration_v1alpha1_api.cpython-38.pyc.140613335570880'
```

@benjyw @stuhood @jsirois

**Comment by stuhood** [comment]
@benjyw : Well, the new caches are being used at least =)

@asherf : Thanks for the report! Just to confirm: nothing is concurrently or partially cleaning the `~/.cache/pants` directory?

**Comment by asherf** [comment]
It's CI, so I don't think so.

**Comment by asherf** [comment]
But it might be the case that we are running multiple pex processes to build `requirements.pex` files so they might step on each other toes.

**Comment by stuhood** [comment]
> But it might be the case that we are running multiple pex processes to build `requirements.pex` files so they might step on each other toes.

Yea, we definitely should be. But pex's cache is supposed to be concurrency safe.

**Comment by jsirois** [comment]
NB this build time (PEXBuilder). The resolve cache is definitely concurrency safe. Concurrent building of the PEX file clearly not.

**Comment by stuhood** [comment]
Interesting... so should we be avoiding mutably caching one of these, but not the other then: https://github.com/stuhood/pants/blob/67cf9ef799977cc91d501d71f06a6aab8adb6c81/src/python/pants/backend/python/rules/hermetic_pex.py#L54-L55 ...?

**Comment by benjyw** [comment]
Looking into this. That file is under a `__pycache__` directory that got created in the pex cache for some reason. I'm not at all clear on why that would happen, or what would then delete it. A python interpreter should only be running on chrooted code, not directly on the cache, AFAIK.

**Comment by benjyw** [comment]
Well, what deletes it is I guess fairly obvious: this is a tmpfile (as evidenced by the `.140613335570880` suffix) which gets moved to its final name. But still unclear why any .pyc files are created at all. We install wheels with `--no-compile`.

**Comment by benjyw** [comment]
Hmm, the contents under `installed_wheels` *are* written atomically: https://github.com/pantsbuild/pex/blob/d628bd64fd6dee204528f7f543dfcd9291067460/pex/util.py#L146

**Comment by jsirois** [comment]
@stuhood was on the right track. Without hardening the PEX buildtime system against the runtime system, setting `RUNTIME_PEX_ROOT`
https://github.com/pantsbuild/pants/blob/9dd457e3e667a32e4c525b7832e4c82e7e7b37cd/src/python/pants/backend/python/rules/hermetic_pex.py#L55
to point to the Pants controlled cache invites trouble racing the python bytecode compiler. That env var should simply be left unset.

**Comment by benjyw** [comment]
Ah, thanks for the pointer. That explains entirely why bytecode compilation is happening in the pex cache.

**Comment by benjyw** [comment]
To clarify my understanding:

If we leave RUNTIME_PEX_ROOT unset then it'll default to `~/.pex`. There may still be race conditions there, but since we're not copying from there at build time, we won't encounter this specific problem. And since writing `__pycache__` itself is presumably concurrency safe, this is probably fine.

However when remoting, I assume `~/.pex` may not be writeable, in which case we'll fall back to using a tmpdir, which is documented as hurting performance:

https://github.com/pantsbuild/pex/blob/da71661b35f1935d296b49f8ac375481760ae400/pex/pex_info.py#L317

I believe that the performance impact referred to is that we can't re-use compiled code? But I guess that would be true anyway in a remoting environment, since every execution is in a clean container.  If we want to pre-compile dists, we should do so at build time.

**Comment by benjyw** [comment]
An alternative might be to modify the copying code to ignore `__pycache__` directories, if for some reason we want to have the ability to compile code directly in the pex cache.

**Comment by benjyw** [comment]
Addressed in https://github.com/pantsbuild/pants/pull/9958.

**Comment by jsirois** [comment]
The diagnosis is correct but lots of chaff here still. I spoke too soon.
1. RUNTIME_PEX_ROOTis not even a thing - it should be deleted to not show further confusion: https://github.com/pantsbuild/pex/blob/master/pex/variables.py
2. The runtime PEX_ROOT is set by PEX_ROOT. We should set that to ./pex_root or nothing at all.
3. The build time pex root which we do still want to use the mutable cache for should be set using the CLI `--pex-root` flag.

We currently use the PEX_ROOT env var to do both 2 and 3 in HermeticPex. This will need to change.

**Comment by asherf** [comment]
yay!
